"""Apply round-2 minor fixes to the two owned literature reports."""
from pathlib import Path
import json,re
P=Path(__file__).resolve().parents[2];issues=json.loads((P/'reviews/minor-fixes/issues.json').read_text())
def edit(track,changes,rows):
 f=P/track/'report.md';s=(P/'reviews/minor-fixes/before'/(track.replace('/','__')+'.txt')).read_text()
 for old,new in changes:
  assert old in s,(track,old[:100]);s=s.replace(old,new)
 s+='\n## Response to review\n\nReview: `../../reviews/lit-'+ ('control' if track.endswith('control') else 'network')+'-review-r2.md`. Checked and resolved on 2026-10-03. Round-1 resolutions remain in the report.\n\n| issue | resolution and evidence |\n|---|---|\n'
 for i,title,res,integration in rows:s+=f'| {i}. {title} | {res} |\n'
 s+=f'\nTargeted check: `OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 PYTHONDONTWRITEBYTECODE=1 python3 research-20260929/publication/{track}/checks/minor_review_check.py > research-20260929/publication/{track}/checks/minor_review_check.log` (from the repository root). All checks pass. Additional source-copy, metadata and text-extraction commands are recorded in `publication/reviews/minor-fixes/commands.md`. No solver, main certificate computation, project-wide verification or CI check was run for this revision.\n'
 f.write_text(s);issues[track]=rows
 (P/'reviews/minor-fixes/issues.json').write_text(json.dumps(issues,indent=2)+'\n')

edit('literature/control',[
('Date: 2026-10-01; revised 2026-10-02 after review round 1 (see Section 7).','Date: 2026-10-01; revised 2026-10-02 after review round 1 (see Section 7), and 2026-10-03 after review round 2 (Response to review).'),
('M ≤ 1000','M = 600–1000'),
('largest relative bound difference 2.4e-10','largest relative bound difference 4.7e-10 (4.708e-10 before display rounding, at camshape400 x1.up)'),
('ε_feas values: −2.2e-10 to −8.1e-10.','ε_feas values: −2.2e-10, −8.1e-10, −1.6e-10, −6.8e-10 and −2.7e-10; the range is −1.6e-10 to −8.1e-10.'),
('camshape100 −4.908 (PDF p. 41)','camshape100 −4.908 (Table 4, PDF p. 40; camshape200–800 are on p. 41)'),
('appendix tables (PDF pp. 41, 46, 58)','appendix tables (PDF pp. 40–41, 46, 58)'),
('The MINLPLib optimizer violates the QPLIB model','MINLPLib point p1 violates the QPLIB model'),
('its incumbent was 8.7e-6 infeasible.','CONOPT reports 8.7007237331E-06 in its aggregate "Infeasibility" column for the input point. The log does not identify that point as ANTIGONE\'s incumbent, although that is the natural reading.'),
('CONOPT then reports the incumbent infeasible by 8.7e-6 and polishes it to −4.28414626579.','CONOPT then reports aggregate Infeasibility 8.7007237331E-06 for its input point and polishes it to −4.28414626579. The input is naturally read as ANTIGONE\'s incumbent but the log does not state that identity; this is not necessarily the largest row violation.'),
('with an incumbent that CONOPT measures as 8.7e-6 infeasible.','with CONOPT\'s input point having aggregate Infeasibility 8.7007237331E-06. The log does not explicitly identify the input as ANTIGONE\'s incumbent.'),
('ANTIGONE\'s camshape100 "Global minimum" rests on an incumbent that CONOPT reports as 8.7e-6 infeasible.','ANTIGONE\'s camshape100 "Global minimum" is followed by a CONOPT input point with aggregate Infeasibility 8.7007237331E-06; identifying the input with ANTIGONE\'s incumbent is an inference.'),
('**Rigour of the camshape800 refutation**','**Rigour of the camshape800 refutation**\n- "False" here means incompatible with exact feasibility for the certified MINLPLib model. A reported tolerance-feasible value can lie below the exact optimum; ANTIGONE\'s camshape100 value is another example. For rounded QPLIB_3177, the evidence is strong but the MINLPLib certificate alone is not a rigorous refutation.'),
('The observed sensitivity makes a 3.1e-3 shift implausible.','The MINOTAUR 0.4.1 log provides stronger evidence of a solver error: QPLIB_3177 closes at the root (1 node, 2.89 s), with the remaining-node bound reported as +∞. On the smaller copies the same version reaches its 10800 s limit with bounds −4.5374 (2738), −4.8494 (2480) and −5.1678 (2703), and gaps 5.9%, 13.3% and 20.8%. Root closure on the largest copy is therefore not credible. A tolerance-feasible value by itself is still possible: COPT\'s incumbent −4.277371 has quadratic violation 2.98e-8 (r2 evidence). The observed sensitivity makes a 3.1e-3 shift implausible.'),
('Whether the rounding moves the camshape optimum at all,','MINLPLib point p1 also violates MINLPLib camshape800 itself by 3.9e-10 at e1562, so it is not the exactly feasible optimizer. The QPLIB reference points for 2480 and 2703 violate MINLPLib\'s r1 upper bound by 2.481e-11 and 4.7078e-10, respectively (`checks/minor_review_check.log`).\n- Whether the rounding moves the camshape optimum at all,'),
('The claim therefore concerns an artificially bounded box, and it is a floating-point claim.','The claim therefore concerns an artificially bounded box, and it is a floating-point claim. The master-source rule in `QuadHandler::addDefaultBounds` scales the largest applicable finite bound magnitude by 100 (or uses ±1000 when none exists). For QPLIB_8585\'s sole finite bound x50001 = 1, this gives [−100, 100]. The r2 check reports max |x| = 8.06 for the QPLIB reference point, within that box. The benchmarked revision v0.4-50-g456fd8cc may differ from the saved master source, so the inference does not prove which default values that run used. Its one-node closure is plausible because our convex Lagrangian relaxation is exact to the certified precision.'),
('the values of the assumed default bounds are not stated in the log.','the log does not state the default values. Saved master source implies [−100, 100] from x50001 = 1, containing the reference point (max |x| = 8.06); the exact benchmark revision may differ.'),
('The default bound values it assumed are not stated in its log.','Master source implies [−100, 100] from x50001 = 1, but its log does not state the values and the exact benchmark revision may differ.'),
('the default values are not stated.','the log does not state the values; master source implies [−100,100], with a benchmark-revision caveat.')],[
('2.1','Missed upper bounds','Dropped only the regex start anchor in `qplib_camshape_compare.py`. Rechecked every bound in all four pairs; corrected the largest reported difference to 4.7e-10. Added the two reference-point r1 upper-bound violations.','Use 4.7e-10 if quoting the maximum over all four camshape copies; QPLIB_3177 alone remains about 2.5e-10.'),
('2.2','Waki Table 12 range and tested sizes','Read Table 12 (printed p. 31, PDF p. 33): feasibility range −1.6e-10 to −8.1e-10 and tested M = 600,700,800,900,1000. Corrected every M ≤ 1000 statement.','Use M = 600–1000 and the corrected feasibility range.'),
('2.3','Müller camshape100 page','Checked PDF p. 40 and corrected both the body and bibliography page location; camshape200–800 remain on p. 41.','Use PDF p. 40 for camshape100.'),
('2.4','Evidence for spurious camshape800 closure','Read all four MINOTAUR logs. Added root-only closure/+∞ bound versus smaller-copy timeouts, defined false under exact feasibility, and retained the QPLIB-copy caveat.','Keep the exact-feasibility meaning and distinguish rigorous MINLPLib refutation from evidence for rounded QPLIB_3177.'),
('2.5','MINOTAUR dtoc5 default bounds','Read the saved master `QuadHandler.cpp` rule; explained inference [−100,100], reference-point scale 8.06, revision caveat and plausible root-only convex closure.','Narrow the open issue to the benchmarked revision, rather than saying no default values can be inferred.'),
('2.6','MINLPLib optimizer wording','Changed to MINLPLib point p1 and stated its own 3.9e-10 MINLPLib row violation; p1 is not the exactly feasible optimizer.','Use point p1, not optimizer, for this comparison.'),
('2.7','CONOPT aggregate measure','Reworded every 8.7e-6 discussion as CONOPT\'s aggregate Infeasibility for its input; incumbent identity is an inference, not explicit log evidence.','Do not call 8.7e-6 a maximum row violation or an explicitly identified ANTIGONE incumbent violation.')])

network_changes=[
('Status: partial.','Status: complete.'),
('Revised after review round 1: 2026-10-02 (Section 11).','Revised after review round 1: 2026-10-02 (Section 11), and round 2: 2026-10-03 (Response to review).'),
('Two key sources could not be obtained, besides the publisher versions','Three sources remain unobtained, besides the publisher versions'),
('How this file came about: the tool environment blocks subagents from writing this file. This happened in the first version and again in the revision. The full text is therefore returned to the root, which must save it at `publication/literature/network/report.md` exactly as given. The reviewer saw only a truncated copy of the first author\'s text. In the revision, the full text was recovered from the author\'s returned output, and the corrections from review round 1 were worked into the body. Section 11 lists every review issue and what was done about it.','The full report is now on disk, including all per-instance sections, assumptions, source limits and commands. Section 11 records round-1 resolutions; Response to review records the remaining round-2 issues. Historical failed-write entries in Section 12 describe the earlier workflow only.'),
('0030p is 0030r plus angle-difference rows, so any dual bound for 0030r is also a dual bound for 0030p. The instance was therefore closed in floating point.','The models have the same data up to coefficient rounding in the 15th–16th significant digit, with additional angle-difference rows in 0030p (r2 check, Section 3.2). This supports FP closure via the twin at solver tolerance. It does not establish exact transport of rigorous dual bounds between the two stored models.'),
('Our exact-arithmetic certificate is the first rigorous one found.','Our exact-arithmetic certificate is the first rigorous one found for this MINLPLib model. Certified ACOPF bounds on different PGLib models predate it (Oustry et al. 2022, Section 8).'),
('None of the runs with 5 or more periods closed the gap; with the author\'s extra cuts, the relative gaps are 0.18 to 1.14.','None of the runs with 5 or more periods closed the gap. The extended-model gap is 0.000470589 at 5 periods (above the 1e-5 stopping limit); the range 0.18–1.14 applies to 6–24 periods.'),
('In Schweidtmann & Mitsos 2019 (Table 4, Fig. 6),','In arXiv:1801.07114v2 by Schweidtmann & Mitsos (Table 4, Fig. 6),'),
('MAiNGO\'s best reduced-space run ended with an absolute gap of 1e5.','MAiNGO\'s best reduced-space run ended with an absolute gap of 1e5. The 2021 dissertation\'s Table 2.8 instead gives MAiNGO gaps 2930, 444 and 328; neither version converged, and the JOTA full-text table remains unchecked.'),
('(same data, no angle rows), which is also a dual for 0030p.','(same data up to 15th–16th-significant-digit rounding, no angle rows), supporting tolerance-level closure of 0030p; exact bound transport is not proved.'),
('ours is the first rigorous certificate and the first bound that closes the gap on 0030p as listed','ours is the first rigorous certificate found for this MINLPLib model and the first bound that closes the gap on 0030p as listed'),
('not closed (gap 0.18)','not closed (extended-model gap 0.18)'),
('related model not closed (gap 0.53)','related model not closed (extended-model gap 0.53)'),
('related model not closed (gap 0.84)','related model not closed (extended-model gap 0.84)'),
('related model not closed (gap 0.90)','related model not closed (extended-model gap 0.90)'),
('related model not closed (gap 1.03)','related model not closed (extended-model gap 1.03)'),
('The rectangular twin 0030r has the same data as 0030p: the reviewer checked this, and its OSIL has no shunt terms either. It has no angle rows. Every feasible point of 0030p maps to a feasible point of 0030r with the same cost, so dual bounds for 0030r are dual bounds for 0030p.','The rectangular twin 0030r has the same data up to rounding in the 15th–16th significant digit (checked by reviewer r2); its OSIL has no shunt terms or angle rows. Under u_i = V_i cos θ_i and w_i = −V_i sin θ_i, the objective agrees. At two random rational test points, 214 of 391 rectangular rows match exactly, 60 voltage rows match through V², and the reference row w_1 = 0 corresponds to θ_1 = 0. The other 116 rows differ by up to 1.03e-13. For example, branch 27–29 stores 1.86832740213523 in 0030p versus 2 × 0.934163701067616 in a 0030r coefficient. The row tests are evidence, not a symbolic identity proof. The ideal formulation map therefore does not prove exact transfer of a bound for the rounded files.'),
('Wave 3 also certified 0030r rigorously at 576.8934126255.','Wave 3 also certified 0030r rigorously at 576.8934126255. This bound cannot be transferred to 0030p (certificate 576.8934122988) without a perturbation argument.'),
('SCIP 9.0.1 via ASL/Pyomo, gap tolerance 0, 2 h limit, with SCIP\'s default 1e-6 feasibility tolerance.','SCIP 9.0.1 via ASL/Pyomo, gap tolerance 0 and 2 h limit. The 1e-6 feasibility tolerance is inferred from the Default logs, not stated on p. 16: R3_H1_N4.log reads only limits/time = 7200 from scip.set, so the SCIP default applies.'),
('The 1- and 2-period optima agree with MINLPLib\'s to the printed digits.','The "original" column\'s 1- and 2-period optima agree with MINLPLib\'s to the printed digits. The extended-model column gives 19.38 and 39.5 instead, so its equivalence to the original model is not established.'),
('Huang\'s 6-period dual, 343.41, exceeds waterno2_06\'s primal, 282.888. This confirms that they are different models.','Huang\'s extended-model 6-period dual 343.41 is not used as evidence against the MINLPLib model: the relation between the extended and original feasible sets is not established. The original 3-period closed value 215 versus 115.0045 already establishes a model mismatch.'),
('Mittelmann\'s 200-instance MINLPLib benchmark and the SCIP 8 paper\'s test set contain only waterno2_02 and waterno2_03.','Mittelmann\'s 200-instance MINLPLib benchmark and the JOGO SCIP 8 paper\'s test set contain only waterno2_02 and waterno2_03 from this family. The separate SCIP Optimization Suite 8.0 report does include 06/09/12/18/24; SCIP 7 / SCIP 8 time-limit gaps are 326% / 128%, >1000% / 321%, >1000% / 571%, >1000% / 638%, and >1000% / 750% (Appendix A, p. 112). Müller, Serrano, Gleixner 2020 also report waterno2_04–24 at the 1800 s limit in all tested settings (arXiv:1903.05521v2, per-instance tables pp. 42,48,56,59,69,72). These are checked FP results with no closure.'),
('related model: dual 343.41, gap 0.18','extended related model: dual 343.41, gap 0.18'),
('**Results in the source paper (FP).** Table 4 (p. 21) and Fig. 6 (p. 22):','**Results in arXiv:1801.07114v2 (FP).** Table 4 (p. 21) and Fig. 6 (p. 22); these figures are not attributed to the unchecked JOTA publisher table:'),
('So in 2018 no method closed the problem.','The 2021 dissertation, "Global Optimization of Processes through Machine Learning" (DOI 10.18154/RWTH-2021-05536), says Chapter 2 is based on the JOTA paper and reprints it with permission. Table 2.8 (printed p. 29, PDF p. 43) reports different MAiNGO results after 100000 s: F3 4,671,260 iterations / gap 2930; envelope 6,329,810 / 444; envelope* 10,033,800 / 328. BARON gaps remain 1e20. The arXiv iteration counts are 4,772,133 / 5,683,103 / 12,939,508. The publisher full text is still unchecked, so neither set is called "the JOTA result" here. Both sources report no convergence, so the status is unchanged.\n  - In both checked versions no method closed the problem.'),
('the SCIP 8 test set: none of our 15;','the JOGO SCIP 8 paper\'s test set: none of our 15. The separate SCIP Optimization Suite 8.0 report includes the five water instances and powerflow0030r/0039r with time-limit gaps, so "SCIP 8 test set" without a source qualifier is too broad;'),
('QPLIB: original names are not shown, so this check is incomplete;','QPLIB: original names are not shown; r2 found no solution value near 576.89 or 41869.05 in qplib.solu. This is evidence only, not an identity proof;'),
('**The publisher versions of the JOTA, IEEE and NACO papers** (preprints were used instead).','**The publisher versions of the JOTA, IEEE and NACO papers** (preprints were used instead). The Schweidtmann 2021 dissertation is obtained and checked, but its table does not settle which numbers the publisher version prints.\n  - **The AIChE 2025 Annual Meeting abstract "Multi-layer perceptrons or Kolmogorov–Arnold networks…"** from the KAN source group (proceedings.aiche.org): the review encountered a Cloudflare check and found no Internet Archive copy. It may report further Rosenbrock-surrogate runs, so it remains an explicit search limitation.'),
('**Method to cite.** VSDP','**Prior certified OPF work to cite.** Oustry, D\'Ambrosio, Liberti, Ruiz, "Certified and accurate SDP bounds for the ACOPF problem", PSCC 2022 / Electr. Power Syst. Res. 212:108278, DOI 10.1016/j.epsr.2022.108278, HAL hal-03613385. It reports certified SDP lower bounds for PGLib-OPF v21.07 TYP cases. The [authors\' result table](https://github.com/aoustry/dualACOPFsolver) gives certified lower bounds 803.127 (case30_as), 7896.87 (case30_ieee) and 137254 (case39_epri), different from MINLPLib\'s 576.89 / 41869.05 models. This is relevant prior certified-bound work, not a closure of these MINLPLib instances. We have not audited its control of rounding errors.\n- **Method to cite.** VSDP'),
('Call it "the first rigorous certificate"','Call it "the first rigorous certificate found for this MINLPLib model"'),
('Cite ANTIGONE on 0030r for the FP closure of the model as written.','Cite ANTIGONE on 0030r for FP closure via the nearly identical rounded twin; state the coefficient-rounding caveat and do not transfer a rigorous bound without a perturbation argument. Cite Oustry et al. 2022 for prior certified bounds on different PGLib models.'),
('Cite Schweidtmann & Mitsos (Table 4, Fig. 6) for the 2018 baseline.','Cite Schweidtmann & Mitsos arXiv v2 (Table 4, Fig. 6) for that baseline, alongside the different 2021 dissertation Table 2.8. The publisher table remains unchecked.'),
('since any dual for 0030r is a dual for 0030p.','as tolerance-level evidence from the nearly identical rounded twin. Round 2 supersedes the exact bound-transport claim: the files differ in the 15th–16th significant digit, so rigorous transport needs a perturbation argument.'),
('Publisher versions (JOTA 2019, IEEE TPS papers, NACO 2012) were not accessed; preprints were used. The QPLIB check remains incomplete.','Publisher versions (JOTA 2019, IEEE TPS papers, NACO 2012) were not accessed; preprints were used. The 2021 dissertation is now checked but the JOTA table is unresolved. The QPLIB objective-value scan is evidence only.')]
# Remove the duplicated appended command list, while retaining all original Section 12 entries.
f=P/'reviews/minor-fixes/before/literature__network.txt';original=f.read_text();duplicate=original[original.index('## Commands run (from the agent\'s structured return)'):original.index('## Open issues (from the agent\'s structured return)')]
network_changes.append((duplicate,''))
stale=next(x for x in original.splitlines() if x.startswith('- report.md is still NOT on disk:'))
network_changes.append((stale,'- The complete report is on disk; source-access limits below remain.'))
# Add benchmarks in the instance discussion and search list.
network_changes += [
('### 3.2 powerflow0030p','**Additional per-instance FP benchmarks, checked after review r2.** The SCIP Optimization Suite 8.0 report (arXiv:2112.08872v1, Appendix A, p. 105) gives SCIP 7 / SCIP 8 gaps ∞ / 0.54% for powerflow0030r and >1000% / 0.23% for powerflow0039r, at the time limit. Müller, Serrano, Gleixner 2020 (arXiv:1903.05521v2, tables pp. 42,48,56,59,69,72) reports both rectangular instances at the 1800 s limit in every setting. Göß 2026 (arXiv:2603.16505v1, Appendix B Table 4, p. 32) reports powerflow0039p with PARA, ε = 1e-4, time limit, dual and reported dual 4.0e2, gap and reported gap 9.90%. That scale does not match MINLPLib\'s primal 41869.05 and best dual 41818.28; no explanation is established and it is not used as a bound for our stored model. None of these results closes our instances.\n\n### 3.2 powerflow0030p'),
('Octeract: its claims concern other instances.','Octeract: its claims concern other instances.\n  - SCIP Optimization Suite 8.0 Appendix A, Müller–Serrano–Gleixner 2020 and Göß 2026 were checked for our instance names and added to the relevant power-flow and water sections above. All are time-limit FP results; none gives a closure. The inconsistent Göß powerflow0039p scale is explicitly retained as a caveat.')]
# Complete the bibliography from saved paper headers and checked DOI metadata.
bib=original[original.index('## 10. Bibliography'):original.index('## 11. Revision')]
newbib='''## 10. Bibliography

- Bestuzheva, Chmiela, Müller, Serrano, Vigerske, Wegscheider, "Global Optimization of Mixed-Integer Nonlinear Programs with SCIP 8", J. Global Optim. 91:287–310 (2025); arXiv:2301.00587v1.
- Bestuzheva et al., "The SCIP Optimization Suite 8.0", ZIB-Report 21-41 (2021); arXiv:2112.08872v1, Appendix A.
- Bingane, Anjos, Le Digabel, "Tight-and-Cheap Conic Relaxation for the AC Optimal Power Flow Problem", IEEE TPS 33(6):7181–7188 (2018), DOI 10.1109/TPWRS.2018.2848965; arXiv:1908.02319.
- Carrasco, Muñoz, "Tightening convex relaxations of trained neural networks: a unified approach for convex and S-shaped activations", arXiv:2410.23362v2 (2026; first version 2024).
- Coffrin, Gordon, Scott, "NESTA, The NICTA Energy System Test Case Archive", arXiv:1411.0359v6.
- D'Ambrosio, Lodi, Wiese, Bragalli, "Mathematical Programming techniques in Water Network Optimization", EJOR 243(3):774–788 (2015), DOI 10.1016/j.ejor.2014.12.039.
- Geißler, Morsi, Schewe, Schmidt, "Penalty Alternating Direction Methods for Mixed-Integer Optimization: A New View on Feasibility Pumps", SIAM J. Optim. 27(3):1611–1636 (2017), DOI 10.1137/16M1069687.
- Ghaddar, Mareček, Mevissen, "Optimal Power Flow as a Polynomial Optimization Problem", IEEE TPS 31(1):539–546 (2016), DOI 10.1109/TPWRS.2015.2390037.
- Gleixner, Held, Huang, Vigerske, "Towards globally optimal operation of water supply networks", NACO 2(4):695–711 (2012), DOI 10.3934/naco.2012.2.695; ZIB-Report 12-25.
- Gopalakrishnan, Raghunathan, Nikovski, Biegler, "Global Optimization of Optimal Power Flow Using a Branch & Bound Algorithm", Allerton 2012, pp. 609–616, DOI 10.1109/Allerton.2012.6483274.
- Göß, "Clash of MINLP Relaxations: Piecewise Linear vs. Global Parabolic", arXiv:2603.16505v1 (17 March 2026).
- Hijazi, Coffrin, Van Hentenryck, "Convex Quadratic Relaxations for Mixed-Integer Nonlinear Programs in Power Systems", Optimization Online 2013/09/4057. June 2014 revision read from the Internet Archive (snapshot 2015-12-24). Published as Math. Prog. Comp. 9(3):321–367 (2017), DOI 10.1007/s12532-016-0112-z.
- Huang W., "Operative Planning of Water Supply Networks by Mixed Integer Nonlinear Programming", MSc thesis, FU Berlin, 2011 (not obtained).
- Huang W., "Optimal Operation of Water Supply Networks by Mixed Integer Nonlinear Programming and Algebraic Methods", Dissertation, TU Darmstadt, 2019, urn:nbn:de:tuda-tuprints-86575, https://tuprints.ulb.tu-darmstadt.de/8657/.
- Izquierdo González, Adeogun, Yin, Charitopoulos, "Nonconvex Robust Optimization for Process Design with Artificial Neural Networks Embedded", Syst. Control Trans. 5:1793–1800 (2026), DOI 10.69997/sct.139045.
- Jansson, "VSDP: Verified SemiDefinite Programming", User's Guide (2006), and Jansson, Chaykin, Keil, "Rigorous error bounds for the optimal value in semidefinite programming" (2007). Official package: https://www.tuhh.de/ti3/jansson/vsdp_cj.html; paper preprint: https://optimization-online.org/wp-content/uploads/2005/01/1047.pdf.
- Josz, Maeght, Panciatici, Gilbert, "Application of the Moment–SOS Approach to Global Optimization of the OPF Problem", IEEE TPS (2015); arXiv:1311.6370v2.
- Karia, Lastrucci, Schweidtmann, "Deterministic Global Optimization over trained Kolmogorov Arnold Networks", arXiv:2503.02807v1 (2025), supplement Zenodo 14961066.
- Karia, Lastrucci, Schweidtmann, "Kolmogorov Arnold Networks (KANs) as surrogate models for global process optimization", Syst. Control Trans. 4:1371–1376 (2025), DOI 10.69997/sct.195815.
- Kocuk, Dey, Sun, "Inexactness of SDP Relaxation and Valid Inequalities for Optimal Power Flow", IEEE TPS 31(1):642–651 (2016), DOI 10.1109/TPWRS.2015.2402640.
- Lavaei, Low, "Zero Duality Gap in Optimal Power Flow Problem", IEEE TPS 27(1):92–107 (2012), DOI 10.1109/TPWRS.2011.2160974.
- Li, Ovalle, Poczos, Laird, Grossmann, Peña, "Efficient Convexification of Kolmogorov-Arnold Networks with Polynomial Functional Forms Via a Continuous Graham Scan Approach", arXiv:2604.03871v1 (2026).
- MATPOWER case files (github.com/MATPOWER/matpower, master); Zimmerman, Murillo-Sánchez, Thomas, "MATPOWER: Steady-State Operations, Planning, and Analysis Tools for Power Systems Research and Education", IEEE TPS 26(1):12–19 (2011).
- MINLPLib instance pages for ann_cumene_exp, ann_cumene_tanh, powerflow0030r and the 15 instances of this track (https://www.minlplib.org/<name>.html; copies in `sources/`).
- Mittelmann, "Mixed Integer Nonlinear Programming Benchmark", https://plato.asu.edu/ftp/minlp.html (snapshot checked 26 February 2026).
- Molzahn, Hiskens, "Sparsity-Exploiting Moment-Based Relaxations of the Optimal Power Flow Problem", IEEE TPS 30(6):3168–3180 (2015), DOI 10.1109/TPWRS.2014.2372478.
- Müller, Serrano, Gleixner, "Using Two-Dimensional Projections for Stronger Separation and Propagation of Bilinear Terms", SIAM J. Optim. 30(2):1339–1365 (2020), DOI 10.1137/19M1249825; arXiv:1903.05521v2.
- Oustry, D'Ambrosio, Liberti, Ruiz, "Certified and accurate SDP bounds for the ACOPF problem", PSCC 2022 / Electr. Power Syst. Res. 212:108278 (2022), DOI 10.1016/j.epsr.2022.108278; HAL hal-03613385; https://github.com/aoustry/dualACOPFsolver.
- Schweidtmann, Mitsos, "Deterministic Global Optimization with Artificial Neural Networks Embedded", JOTA 180(3):925–948 (2019), DOI 10.1007/s10957-018-1396-0; arXiv:1801.07114v2. Numerical Table 4 and Fig. 6 readings here are from arXiv v2; the publisher table was not obtained.
- Schweidtmann, "Global Optimization of Processes through Machine Learning", Dissertation, RWTH Aachen, 2021, DOI 10.18154/RWTH-2021-05536; Table 2.8, printed p. 29 / PDF p. 43 (Internet Archive 2026-01-28 copy).
- Vigerske, "Decomposition in Multistage Stochastic Programming and a Constraint Integer Programming Approach to Mixed-Integer Nonlinear Programming", dissertation, HU Berlin (2013), DOI 10.18452/16704.
- Wilhelm, Wang, Stuber, "Convex and Concave Envelopes of Artificial Neural Network Activation Functions for Deterministic Global Optimization", JOGO 85(3):569–594 (2023), DOI 10.1007/s10898-022-01228-x.

'''
network_changes.append((bib,newbib))
edit('literature/network',network_changes,[
(1,'Cumene source versions','Attributed 1e11/8e10/1e5 and Fig. 6 to arXiv v2; added the dissertation\'s 2930/444/328 gaps and iteration counts from Table 2.8. The JOTA publisher table remains explicitly unchecked.','Keep both checked versions distinct; status remains partly known via the identical exp twin.'),
(2,'Missing nonclosing benchmarks','Read the SCIP suite Appendix A, Müller–Serrano–Gleixner tables and Göß Table 4; added FP time-limit results in Sections 3,5,8 and qualified the JOGO SCIP 8 test-set statements. Preserved the inconsistent 0039p scale caveat.','Add these nonclosing FP precedents if literature coverage is summarized; no status change.'),
(3,'Prior certified OPF bounds','Read Oustry et al. and the authors\' PGLib result table; added the paper next to VSDP and restricted first-rigorous claims to these MINLPLib models.','Cite Oustry et al. 2022 in the paper; scope novelty to the stored MINLPLib models.'),
(4,'0030p/0030r rounding','Checked unequal exact decimal coefficients and r2\'s row-comparison evidence; corrected every exact bound-transport claim, including the r1 response history. FP closure via the twin remains tolerance-level evidence.','Do not transfer the rigorous 0030r bound 576.8934126255 to 0030p without a perturbation argument.'),
(5,'Huang extended model and gap range','Read Table 5.2; labelled extended-model gaps, removed the 343.41 mismatch argument, retained the original 3-period mismatch, and distinguished the 5-period gap 0.000470589 from the 6–24 range 0.18–1.14.','Use the original 3-period comparison for model mismatch; label extended-model values and correct the period range.'),
(6,'Incomplete bibliography','Added all missing titles and Li\'s six authors; added Josz, Carrasco–Muñoz, Mittelmann, SCIP 8, VSDP and new r2 sources. Checked paper headers and available DOI metadata; unavailable metadata requests are retained as such.','Use complete bibliography entries in the paper; no numerical change.'),
(7,'KAN feasibility tolerance','Changed attribution: 1e-6 is inferred from Default logs reading only limits/time = 7200, not stated on source p. 16.','Label the tolerance as inferred from logs.'),
(8,'Stale report and duplicate commands','The complete report is on disk; replaced stale introduction/open-status text and removed the duplicate appended command list, retaining Section 12.','None.'),
(9,'Unobtained sources list','Marked Schweidtmann 2021 obtained; listed the AIChE 2025 KAN abstract as unobtained, alongside Huang 2011 and the original Hijazi report.','Retain these source-access caveats when stating new as far as found.')])
state=json.loads((P/'reviews/minor-fixes/PROGRESS.json').read_text());state['done']=list(issues);state['remaining']=['final targeted validation and integration summary'];(P/'reviews/minor-fixes/PROGRESS.json').write_text(json.dumps(state,indent=2)+'\n')
