"""Apply reviewed wording corrections to the owned reports only.
Run once; source report snapshots are in before/.
"""
from pathlib import Path
import json
P=Path(__file__).resolve().parents[2]
ISSUES={}
def edit(track,changes,issues):
 f=P/track/'report.md';s=(P/'reviews/minor-fixes/before'/(track.replace('/','__')+'.txt')).read_text()
 for old,new in changes:
  assert old in s,(track,old[:100]);s=s.replace(old,new)
 # Historical commands retain the original outcomes. Remove obsolete current-status bullets.
 s='\n'.join(l for l in s.splitlines() if not (l.startswith('- ') and ('report.md was not written' in l or 'report.md is still NOT on disk' in l)))+'\n'
 s+='\n## Response to review\n\nReview: `'+ ('../../reviews/' if track.startswith('primal/') else '../reviews/' if '/' not in track else '../../reviews/') + {'primal/chain':'primal-chain-review-r1.md','primal/dtoc5-lukvle10':'primal-dtoc5-lukvle10-review-r1.md','primal/lnts':'primal-lnts-review-r1.md','primal/powerflow':'primal-powerflow-review-r1.md','primal/water-ann-kan':'primal-water-ann-kan-review-r1.md','audit-ir':'audit-ir-review-r1.md','eg-recheck':'eg-recheck-review-r1.md','scip-bug':'scip-bug-review-r1.md','literature/control':'lit-control-review-r2.md','literature/network':'lit-network-review-r2.md'}[track]+'`. Checked and resolved on 2026-10-03.\n\n'
 s+='| issue | resolution and evidence |\n|---|---|\n'
 for i,title,res,integration in issues:s+=f'| {i}. {title} | {res} |\n'
 check='code/minor_review_check.py' if track=='primal/water-ann-kan' else 'checks/minor_review_check.py' if track.startswith('literature/') else 'minor_review_check.py'
 log='checks/minor_review_check.log' if track.startswith('literature/') else 'logs/minor_review_check.log'
 s+=f'\nTargeted check: `OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 PYTHONDONTWRITEBYTECODE=1 python3 research-20260929/publication/{track}/{check} > research-20260929/publication/{track}/{log}` (from the repository root). Results are in `{log}`. No main computation, solver campaign, project-wide verification or CI check was run for this revision.\n'
 f.write_text(s);ISSUES[track]=issues

edit('primal/chain',[
('The environment blocked writing report.md, so this text is the report.','The report is on disk and includes the complete method, assumptions and command list. Independent review r1 verified the numerical claims.'),
("Because L < p, this equals MINLPLib's |p−d|/min(|p|,|d|).","Because L < p, this is an upper bound on the project's relative-gap convention |p−d|/min(|p|,|d|), checked against MINLPLib metadata. It uses f_hi rather than the exact primal objective p."),
('The summary and the wave-2 report display chain50 as 5.072261493982863 and chain200 as 5.068917341793162.','The overly rounded decimals 5.072261493982863 (chain50) and 5.068917341793162 (chain200) occur in `open-instances-wave2/cops/report.md` (two tables), `reviews/cops-verification/verification-report.md` (two tables), and `reviews/closing-audit-a.md`. The main summary table shows the valid compact range "5.06862 … 5.07226".'),
('This changes no conclusion. It matters only because the summary states that each displayed value is itself a valid bound.','This changes no conclusion. Integration should correct those older reports and use safe displays in the paper. Against the safe displays for chain50/100/200/400, gap upper bounds are 9.62e-15, 1.01e-14, 9.41e-15 and 1.01e-14; relative upper bounds are 1.90e-15, 1.99e-15, 1.86e-15 and 1.98e-15. The result table above instead uses exact binary64 L values. `logs/minor_review_check.log` checks both conventions with exact rational arithmetic.'),
('3.9e-15 (u)','4.0e-15 (u)')],[
(1,'Location of overly rounded displays','Corrected the integration note; the compact main-summary range is valid. Checked the three older documents and the exact binary64 bounds.','Use 5.0722614939828627 and 5.0689173417931616 in the wave-2 COPS report, COPS verification report, closing-audit-a and paper; no main-table range correction.'),
(2,'Which dual the gaps use','Added all four gaps against safe decimal displays; the main result table explicitly uses exact binary64 bounds. Exact recomputation: `logs/minor_review_check.log`.','State which L the paper uses; safe-display gaps 9.62e-15 / 1.01e-14 / 9.41e-15 / 1.01e-14, relative 1.90e-15 / 1.99e-15 / 1.86e-15 / 1.98e-15.'),
(3,'u-distance rounded down','Changed the conservative bound to 4.0e-15; stored chain200 build evidence has a distance about 3.943e-15.','Use 4.0e-15 if this distance is quoted.'),
(4,'Missing report and relative-gap wording','The full report is on disk, including its commands. Reworded the relative gap as an upper bound using the project convention; independent r1 review is cited.','Use upper bound, not equality, for a gap computed with f_hi.')])

edit('primal/dtoc5-lukvle10',[
('(report text; report.md could not be written)',''),
("That point's value is 4.8e-13 below MINLPLib point p5 (352.2380254064961, row violations 3.5e-15). The whole remaining gap is on the dual side, because our point is a KKT point to more than 600 digits.","That point's value is 4.8e-13 below p5's displayed objective 352.2380254064961. Evaluating the objective at p5's stored 15-digit coordinates instead gives 352.23802540649613695, about 5.14e-13 above f(x*); its objvar line is a third value, 352.238025406498025. The row violation is 3.48e-15. The exactly feasible x* agrees with the numerical KKT point to about 205 digits (max coordinate difference 5.8e-206; stationarity residual about 1.4e-205). KKT conditions do not prove global optimality. If that KKT point is the global minimizer, the remaining gap is on the dual side."),
('the statement that the remaining lukvle10 gap is entirely on the dual side. This rests on the KKT residual of 1e-638, not on a second-order proof.','the agreement of x* with the KKT point to about 205 digits. No proof of local or global optimality of that KKT point was attempted, so the remaining gap is not assigned entirely to the dual side.'),
('No reviewer has rechecked this track.','Independent review r1 rechecked the exact points, enclosures and gaps (`../../reviews/primal-dtoc5-lukvle10-review-r1.md`).'),
('The lukvle10 gap of 1.4e-9 is entirely on the dual side (branch-and-bound tolerances). Closing it further would need a sharper dual bound; that is outside this track.','It is not proved that the lukvle10 gap of 1.4e-9 lies entirely on the dual side; KKT agreement is numerical evidence only.')],[
(1,'Missing or truncated report','The full report is on disk, with complete construction, assumptions, proved/numerical labels and command list.','Remove dtoc5 and lukvle10 from the main summary sentence saying no exactly feasible point was constructed.'),
(2,'KKT overclaim','Removed the unconditional dual-side claim everywhere. Recorded 205-digit agreement of x* with the KKT vector and distinguished its residual from the unrounded vector; inspected r1 KKT evidence.','Do not claim that a KKT residual proves global optimality or places the whole lukvle10 gap on the dual side.'),
(3,'p5 comparison','Distinguished the displayed value, coordinate-evaluated objective and objvar entry, using the stored p5 file and r1 objective evaluation.','If quoted, 4.8e-13 is against the display; 5.14e-13 is against the objective evaluated at p5 coordinates.'),
(4,'sci_up carry','Fixed the mantissa carry with a minimal change in `gaps.py`; boundary cases in `minor_review_check.py` remain upper bounds. Current reported gaps were unaffected.','None.')])

edit('primal/lnts',[
('Each gap is the upper end of that enclosure minus our dual bound, computed exactly with Fractions and rounded up.','Each gap is the upper end of that enclosure minus our dual bound, computed exactly with Fractions and rounded up. The displayed absolute and relative gaps are rounded upward to three significant digits.'),
('It lies in a box less than 2.1e-106 wide, strictly inside the exact decimal box centre ± radius.','For a second Krawczyk step, y is reset to a point at the midpoint of the step-1 box Z. The original stored centre is outside Z and cannot be reused in that step. The valid two-step enclosure is less than 2.1e-106 wide and lies strictly inside the exact decimal box centre ± radius. The check on all four stored boxes is saved in `logs/minor_review_check.log`; it also confirms the objective width below 3e-109 without regenerating the points.'),
('The new points agree with the earlier tolerance-feasible vectors','The middle fixed control is a small exact rational (about 1e-112), inherited from rounding a numerical tangent-law solve. It is part of the stored point definition. Replacing it with zero would define a different point and require new enclosures, so it is retained. Its size does not affect the displayed objective or gaps.\n\nThe new points agree with the earlier tolerance-feasible vectors'),
('Neither is an independent review, so the results should not be called \'verified\' until someone else re-checks them.','These are author checks; independent review r1 subsequently verified the results, including an integer-only enclosure of sin and cos.'),
('inline python comparison with open-instances/logs/lnts_lnts<N>_primal.txt','inline python comparison (now saved in minor_review_check.py) with open-instances/logs/lnts_lnts<N>_primal.txt')],[
(1,'Invalid second Krawczyk step','Changed only the second-step centre to a point in Z. Rechecked the two steps on all four stored boxes: widths < 2.1e-106, objective width < 3e-109; 25-digit objective displays unchanged. No construction rerun.','None; gaps and displayed enclosures are unchanged.'),
(2,'Missing report','The full report is on disk with its commands and interval assumptions. Independent r1 evidence is acknowledged.','Remove lnts50–400 from the no-exactly-feasible-point sentence.'),
(3,'Missing old-vector comparison script','Saved the comparison in `minor_review_check.py`; exact binary64 inputs and stored coordinate enclosures give upper distances 3.25e-15–3.54e-15 and all but one matching rounding per instance.','None.'),
(4,'Conservative relative-gap rounding','Stated upward rounding to three significant digits in Section 1.','Against displayed summary duals use about 5.8e-13–6.2e-13; 5.5e-13 is against full verifier duals.'),
(5,'Tiny middle control','Kept the stored exact rational to preserve the certified point; explained its numerical origin and checked |control| < 1e-110 for all four instances.','No change needed; replacing it by zero would require a new point certificate.')])

edit('primal/powerflow',[
('ALL THREE INSTANCES PROVED. The only missing deliverable is the report.md file, which the harness would not let me write; its content follows. The results were checked only by this track\'s own code (certify.py) plus a SCIP floating-point cross-check. They have NOT been independently verified.','All three instances have proofs of exactly feasible points. The full report is on disk. Independent review r1 verified the enclosures and gaps with its own OSIL reader and interval code.'),
('Note that p1 violated x269 <= 5.8 by 9e-14.','p1 violates x269 <= 5.8 (e362) by 9e-14, x266 <= 6.52 (e359) by 4e-14 and x267 <= 5.08 (e360) by 3e-14. It also violates voltage rows e307, e309–e313 and e315 by 2.0e-14–6.7e-14.'),
('active slacks are at most 1e-13','active slacks in absolute value are at most 1.7e-16 (0030p), zero at p1\'s stored decimals (0039p), and 6.8e-13 (0039r). In 0039r, e363 has slack 6.8e-13 and e386 has slack 2.1e-13'),
('By the Krawczyk–Moore theorem (Krawczyk 1969; Moore 1977; Neumaier 1990, Ch. 5), S has a unique zero in X.','The Krawczyk inclusion gives existence (Moore 1977). Uniqueness follows separately because ||I − C J(X)||∞ < 1: a check of the stored boxes gives upper bounds 1.930e-12, 2.855e-12 and 5.376e-12 (`logs/minor_review_check.log`). If F(x) = F(y) = 0 in the convex box X, the mean-value matrix A belongs to J(X) and x − y = (I − C A)(x − y); the strict contraction forces x = y. The same bound makes C A invertible and hence makes C nonsingular. This supplies the needed argument without an unverified theorem number in Neumaier\'s book.'),
('osilx.py, the verification review\'s OSIL reader reused unchanged, parses the files correctly. The SCIP cross-check supports this.','osilx.py, the verification review\'s OSIL reader, parses the files correctly. Its dependency is `research-20260929/reviews/open-instances-verification/osilx.py`, SHA-256 `4bcdc1d830bd3fc0392756f10b3e5daccbce218198543e402158a24cf986a465` (checked for this revision). The SCIP cross-check and r1\'s independent reader support the reading.'),
('The results have not been independently verified. Checks so far: this track\'s certify.py, which reads only the stored files, and a SCIP floating-point cross-check.','Independent review r1 verified all three stored point certificates. The original author checks and SCIP floating-point cross-check are listed above.'),
('Integration should update it; this track did not edit it.','Integration should update it; this track did not edit it. For valid upper bounds, use primal displays 41869.0515113203 (0039p) and 41869.0515113210 (0039r). The relative gaps stay 6.3e-10 and 6.7e-10 at summary precision.')],[
(1,'Missing report and commands','The complete report is on disk, including the per-instance construction, radius checks, SCIP commands and mpmath assumptions.','None.'),
(2,'Active-slack bound','Corrected the 0039r maximum to 6.8e-13, with e363/e386 examples; recomputed slacks at stored p1 values.','None.'),
(3,'Incomplete p1 violations','Added x266/x267 violations and all seven violated voltage rows; `logs/minor_review_check.log` records them.','None.'),
(4,'External reader dependency','Recorded the exact path and verified SHA-256 of osilx.py; no copy or interface change needed.','Keep the reader dependency with reproduction materials.'),
(5,'Summary primal displays','Recorded upward displays 41869.0515113203 (0039p) and 41869.0515113210 (0039r); enclosures and relative gaps unchanged.','Apply those two primal displays and remove all three powerflow instances from the no-exactly-feasible-point sentence.'),
(6,'Uniqueness citation','Checked ||I − C J(X)||∞ < 1 on each stored box and gave the mean-value contraction argument. Moore 1977 is cited for existence; no inaccessible theorem number is asserted.','None.')])

edit('primal/water-ann-kan',[
('In relative terms this is 4e-9 to 5e-9.','In relative terms this is 3.7e-9 to 5.3e-9 (nearest one-decimal figures; exact ratios range from 3.6899e-9 to 5.3469e-9).'),
('The relative gaps to the dual are 10.82%, 6.89%, 4.87% and 5.90%, the same as in the summary at its precision.','The displayed relative gaps to the dual are conservative upper bounds 10.82%, 6.89%, 4.87% and 5.90%. Rounding is upward and can occur twice; for example the exact ratios for 09 and 24 are about 10.8115% and 5.8947%. The table\'s 1.647e-2 and 6.450e-2 likewise round upward from about 1.6464e-2 and 6.4493e-2. `logs/minor_review_check.log` records ratios before display rounding.'),
('All 728 finite variable bounds are proved; the bound x647 ≥ −1 has margin 1.25e-12.','All 728 finite variable bounds are proved; the bound x647 ≥ −1 has margin 1.25e-12. The log\'s smallest proved interval margin, 0 at x650 ≤ 1, comes from a saturated tanh neuron: its outward interval touches the upper bound 1. A nonnegative enclosure margin suffices for this non-strict bound; strict interior is not required.'),
('No independent review: all checks are this track\'s own code. For waterno2 there are two separately written exact checkers by the same author, and the OSIL reading was cross-checked against the earlier osilx.py reader at 60 digits.','Independent review r1 verified the numerical claims with its own exact algebraic and rational interval code. This revision also read the complete method, assumptions and command list omitted from the reviewer\'s truncated copy; the exact-row checks and forward-definition argument agree with the saved scripts. The original cross-checks above are author checks.'),
('## 2. waterno2: method (exact algebraic construction)','The earlier waterno2_09/12/18/24 vectors also violate variable bounds by up to 5.72648e-11, 3.09042e-10, 8.938913e-10 and 9.0018923e-10, respectively. The source-point comparison table reports only row violations; those entries do not imply that bounds held. The small bound check is in `code/minor_review_check.py`.\n\n## 2. waterno2: method (exact algebraic construction)')],[
(1,'Missing and truncated report','The complete report is on disk; read its previously omitted construction, forward-definition argument, assumptions and commands against the saved scripts. Independent r1 numerical verification is now acknowledged.','None.'),
(2,'Conservative and repeated gap rounding','Explained upward rounding in the text; recorded pre-rounding ratios in the log. Corrected the relative primal-change range to 3.7e-9–5.3e-9.','If quoted, use that relative-change range; treat displayed gaps as conservative upper bounds.'),
(3,'Old bound violations omitted','Checked source decimals against OSIL bounds; added the four maximum bound violations, including 9.0018923e-10 for waterno2_24.','Do not describe the earlier water vectors as satisfying all bounds.'),
(4,'Zero interval margin at x650','Explained the saturated tanh neuron and the validity of a nonnegative margin for x650 ≤ 1; checked its saved log and interval.','None.'),
(5,'Wrong interval-format description','Changed `nn_exact.py` and the seven stored point JSON descriptions from (mid, rad) to {lo, hi}. All numerical fields are unchanged.','None.')])

edit('audit-ir',[
('Note: the harness blocked writing report.md, so this summary is the full report. Nothing was committed and no one was contacted. Every check finished; only the report file is missing.','The full report is on disk, including the exact constructions, parser checks, assumptions and command list. Independent review r1 verified the substantive claims. Nothing was committed and no one was contacted.'),
('They are not solver errors.','They need not be solver errors: display rounding explains these listed values. The listing alone cannot establish that the underlying stored solver bounds were at most the exact optimum.'),
('35 values show 11 to 20 significant digits','35 values with a nonempty fractional part show 11 to 17 significant digits (first through last nonzero digit)')],[
(1,'Missing and truncated report','The full report is on disk and its complete method and commands have been read.','None.'),
(2,'Digit count definition','Recounted the saved pages: 35 with a nonempty fractional part (11–17 digits); 38 without that filter (11–19); 46 if trailing integer zeros count (11–20). Corrected Section 1.','Audit Section 2: keep the 8-decimal limit, drop the 10-significant-digit limit; state the definition of any >10-digit count. No class or flagged-pair count changes.'),
(3,'spring solver-error wording','Reworded as "need not be solver errors; display rounding explains them". The underlying stored solver bound remains unknown.','Use this qualified wording for spring\'s five (i-r) pairs.'),
(4,'spring SCIP objective tolerance','No further numerical change needed: the report already explains the bisection/tolerance origin of the 1.0e-9 difference; checked `logs/xcheck_scip.log`.','It is not an independent objective disagreement.')])
# Give the alternative definitions explicitly rather than leaving a partial correction.
f=P/'audit-ir/report.md';s=f.read_text().replace('- No class depends on this. None of the 35 is in a flagged pair;', '- Without the fractional-part filter there are 38 values with 11–19 digits; counting trailing integer zeros gives 46 with 11–20 digits. The extra integer-valued display −99999999809999994880. appears on gasoil50, gasoil100 and shiporig. `logs/minor_review_check.log` records all three definitions.\n- No class depends on this. None of these values is in a flagged pair;');f.write_text(s)

edit('eg-recheck',[
('is **verified on every leaf of all eight parts of run G** by code independent of the certificate author\'s code.','is **verified on every leaf of all eight parts of run G under assumptions A1 and A2** by the earlier review\'s independent certifier. Review r1 also certified 10,404 leaves of parts 0 and 2–7, including the 300 tightest per part, with outward-rounded interval arithmetic and no libm assumption; that stronger check is a sample only.'),
('98,234 leaves were proved to contain no feasible point.','98,234 leaves have no feasible point with F < θ*: 85,685 were proved infeasible by a side row at the leaf itself, 373 were closed by a Farkas test excluding F < θ*, and 12,176 were closed after splitting (their pieces can include Farkas certificates).'),
('+∞ for a leaf proved infeasible;','+∞ for a leaf with no feasible point having F < θ* (side infeasibility, Farkas, or certification after splitting);'),
('| proved infeasible |','| no feasible F < θ* (+∞ margin) |'),
('**Small margins outside part 1 are loose bounds, not near-optimal regions.**','**The tightest-margin leaves outside part 1 have loose bounds.**'),
('at part 5 leaf 69407.','at part 5 leaf 69407. Leaf numbers here and in `tight_leaves.log` and `inspect_leaf_p5_69407.log` are positions in the concatenation of chunk files, not positions in `verify_tree.py`\'s leaf list; this same box is leaf 56587 in that list.'),
('**Threshold.** θ* was passed','This observation concerns those selected leaves only. Independent r1 floating-point searches found a feasible point in part 0 at F − θ* ≈ 0.0066, near x = (0.3238, 1.0, 0.7863, 1.2655, 11, 35, 23). The smallest values found in parts 0, 2, 3, 4, 5, 6 and 7 were 0.0066, 0.30, 0.29, 0.51, 0.99, 1.77 and 2.77 (`../reviews/eg-recheck-r1/logs/local_min.log`). These are numerical evidence, not certified regional minima.\n\n**Threshold.** θ* was passed'),
('So this is an independent cross-check; the proof is item 1.','So this is an independent cross-check; the original proof is item 1. Review r1 subsequently supplied an exact tree-free guillotine coverage proof (`../reviews/eg-recheck-r1/own_cover.py`, `../reviews/eg-recheck-r1/logs/own_cover.log`; review Section 1.3). It checks disjointness and coverage by recursively partitioning the boxes, without using the recorded tree.'),
('This pass\'s new files are untracked: `coverage_check.py` and the logs `summarize.log`, `negative_control.log`, `tight_leaves.log`, `coverage_check.log` and `coverage_check_drop.log`.','The second-pass files are committed in 514a788f; this report and the current minor-fix files are working-tree changes. This revision made no commit.'),
('verified (all 1,114,361 leaves of all 8 parts of run G re-certified with independent code; publication/eg-recheck/report.md)','verified (all 1,114,361 leaves of all 8 parts of run G re-certified with the earlier review\'s independent certifier, rigorous under A1 and A2; coverage proved exactly, including the r1 tree-free proof; 10,404 leaves in parts 0 and 2–7 also certified with outward-rounded interval arithmetic and no libm assumption; publication/eg-recheck/report.md; publication/reviews/eg-recheck-review-r1.md)')],[
(1,'A1/A2 absent from headline and integration','Added A1/A2 at the first result claim and in proposed summary wording; distinguished the assumption-free 10,404-leaf r1 sample.','Use the qualified all-leaf claim; preserve the interval sample as a separate statement.'),
(2,'Infeasibility overclaim','Recounted saved results: 98,234 exclude F < θ*, of which 85,685 are directly side-infeasible, 373 Farkas and 12,176 split. Corrected text, margin definition and table heading.','Do not call all 98,234 leaves infeasible; use the objective-qualified statement.'),
(3,'Leaf numbering','Stated chunk-concatenation numbering and the equivalent part-5 leaf-list index 56587; inspected the review\'s box comparison.','Use an explicit numbering convention if quoting leaf 69407.'),
(4,'Stale Git bullet','Verified 514a788f contains second-pass files and updated the historical status.','None.'),
(5,'Near-optimal regions outside part 1','Qualified the statement to the selected tightest-margin leaves and added r1\'s numerical per-part minima.','Do not imply that every region outside part 1 is far from θ*.'),
(6,'Tree-free coverage proof','Added the independent exact guillotine proof and its code/log locations. The original volume/random-point check remains labelled a cross-check.','Coverage can cite both the tree and exact tree-free proofs.')])

edit('scip-bug',[
('In every traced wrong run, the first step that loses the witness is the same:','In every instrumented wrong run listed in Section 5.3, the first step that loses the witness is the same:'),
('0 of 102 runs are wrong. Under default settings, 70 of those 102 runs were wrong.','0 of 122 runs are wrong. Under default settings, 78 of those 122 runs were wrong. The raw-log recount includes the two later small-excess p4 checks missing from the older scan CSV (`logs/minor_review_check.log`).'),
('### 5.3 Every traced wrong run loses the witness at the same step','### 5.3 Every instrumented wrong run listed here loses the witness at the same step'),
('In every traced run, the first','In every instrumented run in the table, the first'),
('pair2236, 8 and 11 (65.1235, 65.1244)','pair2236, 8 (65.1235)'),
('`, `logs/dbgsol_expr_pair2236_seed8.log`, `logs/dbgsol_pair2236_seed11.log`','`, `logs/dbgsol_expr_pair2236_seed8.log`'),
('The root cutoffs (fm336, fm318, pumps_default) start the same way:','Seed 11 is not instrumented: `logs/dbgsol_pair2236_seed11.log` first reports an invalid local implication b35 ≥ 1 at node 2 with no recorded constraint or propagator source, then b47 ≥ 1. b35 belongs to the 0.85 station. Its first witness loss is untraced and cannot be assigned to the 0.7-station mechanism.\n\nThe root cutoffs (fm336, fm318, pumps_default) start the same way:'),
('**The low claims are a tolerance effect.**','**The low claims are not refuted.**'),
('Those claims are harmless.','They are consistent with tolerance effects or with the witness not being optimal; the cause and validity of those lower claims are not established.'),
('strong-branching child b47 = 0 declared infeasible (seeds 8, 11);','strong-branching child b47 = 0 declared infeasible (instrumented seed 8). Seed 11\'s first loss is untraced, as noted in Section 5.3;'),
('Whether a seed fails depends on whether the search reaches a pump-off node','A hypothesis, supported by instrumented seeds 8 and 14, is that seed failure depends on whether the search reaches a pump-off node'),
('SCIP\'s reported solutions are not exactly feasible for the binary64 data.','The examined SCIP solutions (pumps_default, p0 seed 0, tiny2, and pair2236 seeds 0 and 7) are not exactly feasible for the binary64 data. This was not checked for every solution in the scan tables.'),
('SCIP\'s own "optimal" solutions are not exactly feasible for the binary64 data either.','The examined SCIP "optimal" solutions are not exactly feasible for the binary64 data either (pumps_default, p0 seed 0, tiny2, and pair2236 seeds 0 and 7).'),
('  Problem name     : fm336\n','  Problem name     : fm336_reduced\n'),
('Expected: the optimum is at most 187/270','Expected for the exact decimal model: the optimum is 187/270'),
('This point satisfies every constraint exactly in rational arithmetic;','The exact optimum follows by cases: all pumps off violates demand; b1 = 1 costs at least 0.814125 and b0 = 1 at least 1.715; otherwise b2 = 1, q2 ≥ 0.5 and s2 ≥ 2/3 force cost at least 187/270. The point above attains it.\n\nThis point satisfies every constraint exactly in rational arithmetic;'),
('This was checked on master and on 10.1.0.','This was checked on master and on 10.1.0 by the author, and on 10.0.2 and 10.0.3 by review r1 (`../reviews/scip-bug-r1/rv_runs.log`).'),
('Expected: −1.337 at b = 0, s = 0.7, p = 0.343.','Expected for the exact decimal model: the optimum is exactly −1.337 at b = 0, s = 0.7, p = 0.343. For b = 1, minimizing 0.2 − 2.4s + s³ on [0.7, 1] gives 0.2 − 1.6√0.8 > −1.337. These exact case comparisons are recorded in `logs/minor_review_check.log`.'),
('Other channels were not searched.','Review r1 also found [#162, Suboptimal solution for multilinear relations](https://github.com/scipopt/scip/issues/162) (opened August 2025; developer discussion points toward orbitopal symmetry handling) and [#190, Presolving renders problem infeasible](https://github.com/scipopt/scip/issues/190) (February 2026, SCIP 10.0.1; discussion concerns coefficients near 1e-6). Both are related nonlinear wrong-result reports but apparently have different causes; neither establishes a match to this defect. Bodies and developer comments were checked through the GitHub API for this revision. Other channels were not searched.')],[
(1,'Inconsistent totals','Raw-log recount confirms 0/122 with b, versus 78/122 for matched default cases. Corrected the headline; the old CSV omits two later p4 tests.','Any quoted totals must use 122 and 78.'),
(2,'Uninstrumented seed 11','Restricted the trace table to seed 8 and all common-mechanism claims to instrumented runs; recorded seed 11\'s first b35 implication and 0.85-station caveat.','Do not attribute seed 11\'s first witness loss to the traced 0.7-station cutoff.'),
(3,'Low pair claims','Reworded as not refuted and consistent with either tolerance effects or a nonoptimal witness; retained the certified optimum interval.','Do not assert a demonstrated tolerance cause for 55.689773/55.689858.'),
(4,'Seed-failure explanation','Labelled the search-path explanation as a hypothesis supported by instrumented seeds 8 and 14.','Keep the hypothesis qualifier.'),
(5,'All-solution binary64 overclaim','Restricted the exact binary64 feasibility statement to the five examined solutions in the summary of proof claims.','Do not extrapolate the binary64 check to every scanned solution.'),
(6,'Related upstream issues','Read #162/#190 and developer comments; added links and apparently different causes in Section 8 and the unsubmitted draft.','Cite these related reports if the draft is later filed; no report was sent.'),
(7,'Draft consistency and exact optima','Matched the inline CIP name fm336_reduced to the attachment; gave exact case proofs for fm336 and tiny2; added r1 witness acceptance on 10.0.2/10.0.3. The optional untested n hypothesis is labelled below.','No submission authorized or performed.')])
f=P/'scip-bug/report.md';s=f.read_text();mark='We did not find out why `varboundrelax = n` avoids it.'
s=s.replace(mark,mark+' Review r1 proposed an untested explanation: without bound relaxation in round 0, the activity already misses zero, so an epsilon-tolerant intersection may retain a singleton residual rather than [0,0]. Later reverse propagation then has a different right-hand side. This is a hypothesis, not a tested fix.\n\nRelated reports checked: [SCIP #162](https://github.com/scipopt/scip/issues/162) (multilinear suboptimal result, discussion points toward orbitopal symmetry) and [SCIP #190](https://github.com/scipopt/scip/issues/190) (false presolve infeasibility with small coefficients). They appear to have different causes; no common cause was established.')
f.write_text(s)
(P/'reviews/minor-fixes/issues.json').write_text(json.dumps(ISSUES,indent=2)+'\n')
state=json.loads((P/'reviews/minor-fixes/PROGRESS.json').read_text());state['done']=list(ISSUES);state['remaining']=[x for x in state['remaining'] if x not in ISSUES];(P/'reviews/minor-fixes/PROGRESS.json').write_text(json.dumps(state,indent=2)+'\n')
