import Formal.NetworkSimplex.ThresholdCircuitReduction

/-! The nonnegative cancellation cone is generated by its positive circuit rays. -/
namespace NetworkSimplex.Chain.Threshold
open scoped BigOperators
noncomputable section
variable {I : Type*} [Fintype I] {m : ℕ}

/-- Membership in the nonnegative cancellation cone. -/
def InCancellationCone (A : I → Fin m → ℝ) (u : I → ℝ) : Prop :=
  (∀ i, 0 ≤ u i) ∧ ∑ i, u i • A i = 0

/-- Nonnegative coordinate cones contain no nonzero line. -/
theorem cancellation_cone_pointed (A : I → Fin m → ℝ) (u : I → ℝ)
    (hu : InCancellationCone A u) (hneg : InCancellationCone A (-u)) : u = 0 := by
  funext i
  have hp := hu.1 i
  have hn := hneg.1 i
  simp only [Pi.neg_apply] at hn
  simp only [Pi.zero_apply]
  linarith

/-- Positive coefficients multiplying the globally indexed circuit vectors. -/
def circuitSum {A : I → Fin m → ℝ} (L : List (ℝ × PositiveCircuit A)) : I → ℝ :=
  (L.map fun term => term.1 • term.2.weights).sum

/-- Every nonnegative cancellation vector is a finite positive sum of circuit
vectors. Each subtraction removes a support entry, bounding the number of terms. -/
theorem cancellation_cone_decomposition (A : I → Fin m → ℝ) (u : I → ℝ)
    (hu : InCancellationCone A u) :
    ∃ L : List (ℝ × PositiveCircuit A),
      (∀ term ∈ L, 0 < term.1) ∧ circuitSum L = u ∧
      L.length ≤ (Finset.univ.filter fun i => 0 < u i).card := by
  classical
  suffices hall : ∀ N : ℕ, ∀ v : I → ℝ,
      (Finset.univ.filter fun i => 0 < v i).card = N → InCancellationCone A v →
      ∃ L : List (ℝ × PositiveCircuit A),
        (∀ term ∈ L, 0 < term.1) ∧ circuitSum L = v ∧ L.length ≤ N from
    hall _ u rfl hu
  intro N
  induction N using Nat.strong_induction_on with
  | h N ih =>
    intro v hN hv
    by_cases hpos : ∃ i, 0 < v i
    · obtain ⟨C, hs⟩ := exists_positiveCircuit A v hv.1 hpos hv.2
      obtain ⟨t, ht, hr, j, hj, hjzero⟩ := C.subtract_step v hv.1 hs
      let r : I → ℝ := fun i => v i - t * C.weights i
      have hrc : InCancellationCone A r := ⟨hr, by
        simp only [r, sub_smul, mul_smul, Finset.sum_sub_distrib, ← Finset.smul_sum,
          hv.2, C.weights_cancel, smul_zero, sub_zero]⟩
      have hcard : (Finset.univ.filter fun i => 0 < r i).card < N := by
        rw [← hN]
        apply Finset.card_lt_card
        apply Finset.ssubset_iff_subset_ne.mpr
        refine ⟨?_, ?_⟩
        · intro i hi
          have hri := (Finset.mem_filter.mp hi).2
          have hn := mul_nonneg ht.le (C.weights_nonneg i)
          exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, by dsimp [r] at hri; linarith⟩
        · intro he
          have hjmem : j ∈ Finset.univ.filter (fun i => 0 < v i) :=
            Finset.mem_filter.mpr ⟨Finset.mem_univ _, hj⟩
          rw [← he] at hjmem
          have h := (Finset.mem_filter.mp hjmem).2
          change 0 < v j - t * C.weights j at h
          rw [hjzero] at h
          exact lt_irrefl _ h
      obtain ⟨L, hL, he, hlen⟩ := ih _ hcard r rfl hrc
      refine ⟨(t, C) :: L, ?_, ?_, by simp only [List.length_cons]; omega⟩
      · intro term hterm
        rcases List.mem_cons.mp hterm with rfl | hterm
        · exact ht
        · exact hL term hterm
      · change t • C.weights + circuitSum L = v
        rw [he]
        funext i
        change t * C.weights i + (v i - t * C.weights i) = v i
        ring
    · have hz : v = 0 := by
        funext i
        exact le_antisymm (not_lt.mp (not_exists.mp hpos i)) (hv.1 i)
      refine ⟨[], by simp, ?_, by simp⟩
      simpa [circuitSum] using hz.symm

/-- An extreme nonzero ray cannot be split into different nonnegative cancellation directions. -/
def ExtremeCancellationRay (A : I → Fin m → ℝ) (u : I → ℝ) : Prop :=
  InCancellationCone A u ∧ u ≠ 0 ∧
    ∀ v w, InCancellationCone A v → InCancellationCone A w → u = v + w →
      ∃ t : ℝ, 0 ≤ t ∧ v = t • u

/-- Every normalized positive circuit generates an extreme ray. -/
theorem PositiveCircuit.extreme_weights {A : I → Fin m → ℝ} (C : PositiveCircuit A) :
    ExtremeCancellationRay A C.weights := by
  classical
  refine ⟨⟨C.weights_nonneg, C.weights_cancel⟩, ?_, ?_⟩
  · intro hz
    have ht := C.weights_sum
    simp [hz] at ht
  · intro v w hv hw he
    have hs : ∀ i, i ∉ C.support → v i = 0 := by
      intro i hi
      have hz := C.weights_zero (by simpa only [C.mem_support, not_exists] using hi)
      have hei := congrFun he i
      have hvn := hv.1 i
      have hwn := hw.1 i
      simp only [Pi.add_apply] at hei
      linarith
    refine ⟨∑ i, v i, Finset.sum_nonneg (fun i _ => hv.1 i), ?_⟩
    funext i
    exact C.kernel_unique_global v hv.2 hs i

/-- Scaling an extreme ray by a positive number preserves extremality. -/
theorem ExtremeCancellationRay.smul {A : I → Fin m → ℝ} {u : I → ℝ}
    (hu : ExtremeCancellationRay A u) {t : ℝ} (ht : 0 < t) :
    ExtremeCancellationRay A (t • u) := by
  have hcone : InCancellationCone A (t • u) := ⟨fun i => mul_nonneg ht.le (hu.1.1 i), by
    simp only [Pi.smul_apply, smul_eq_mul, mul_smul, ← Finset.smul_sum, hu.1.2, smul_zero]⟩
  refine ⟨hcone, ?_, ?_⟩
  · intro hz
    apply hu.2.1
    funext i
    have hi := congrFun hz i
    simp only [Pi.smul_apply, smul_eq_mul, Pi.zero_apply] at hi
    exact (mul_eq_zero.mp hi).resolve_left (ne_of_gt ht)
  · intro v w hv hw he
    have hvc : InCancellationCone A (t⁻¹ • v) := ⟨fun i =>
      mul_nonneg (inv_nonneg.mpr ht.le) (hv.1 i), by
      simp only [Pi.smul_apply, smul_eq_mul, mul_smul, ← Finset.smul_sum, hv.2, smul_zero]⟩
    have hwc : InCancellationCone A (t⁻¹ • w) := ⟨fun i =>
      mul_nonneg (inv_nonneg.mpr ht.le) (hw.1 i), by
      simp only [Pi.smul_apply, smul_eq_mul, mul_smul, ← Finset.smul_sum, hw.2, smul_zero]⟩
    have hsum : u = t⁻¹ • v + t⁻¹ • w := by
      rw [← smul_add, ← he, smul_smul, inv_mul_cancel₀ (ne_of_gt ht), one_smul]
    obtain ⟨k, hk, hvk⟩ := hu.2.2 _ _ hvc hwc hsum
    refine ⟨k, hk, ?_⟩
    have h := congrArg (t • ·) hvk
    simpa only [smul_smul, mul_inv_cancel₀ (ne_of_gt ht), one_smul, mul_comm t k] using h

/-- Every extreme ray is generated by an actual positive circuit. -/
theorem extreme_ray_iff_positive_circuit (A : I → Fin m → ℝ) (u : I → ℝ) :
    ExtremeCancellationRay A u ↔
      ∃ C : PositiveCircuit A, ∃ t : ℝ, 0 < t ∧ u = t • C.weights := by
  classical
  constructor
  · intro hu
    have hpos : ∃ i, 0 < u i := by
      by_contra hn
      apply hu.2.1
      funext i
      exact le_antisymm (not_lt.mp (not_exists.mp hn i)) (hu.1.1 i)
    obtain ⟨C, hs⟩ := exists_positiveCircuit A u hu.1.1 hpos hu.1.2
    obtain ⟨t, ht, hr, _, _, _⟩ := C.subtract_step u hu.1.1 hs
    have htc : InCancellationCone A (t • C.weights) :=
      (C.extreme_weights.smul ht).1
    have hrc : InCancellationCone A (u - t • C.weights) := ⟨hr, by
      simp only [Pi.sub_apply, Pi.smul_apply, smul_eq_mul, sub_smul, mul_smul,
        Finset.sum_sub_distrib, ← Finset.smul_sum, hu.1.2, C.weights_cancel,
        smul_zero, sub_zero]⟩
    obtain ⟨k, hk, he⟩ := hu.2.2 _ _ htc hrc (by abel)
    have hkpos : 0 < k := by
      by_contra hn
      have hkzero : k = 0 := le_antisymm (not_lt.mp hn) hk
      rw [hkzero, zero_smul] at he
      exact (C.extreme_weights.smul ht).2.1 he
    refine ⟨C, t / k, div_pos ht hkpos, ?_⟩
    funext i
    have hei := congrFun he i
    simp only [Pi.smul_apply, smul_eq_mul] at hei ⊢
    rw [div_mul_eq_mul_div]
    exact (eq_div_iff (ne_of_gt hkpos)).mpr (by nlinarith [hei])
  · rintro ⟨C, t, ht, rfl⟩
    exact C.extreme_weights.smul ht

/-- Support minimality among nonzero nonnegative cancellations. Zero coordinates
express support inclusion without choosing an ordering of the ambient index set. -/
def MinimalPositiveCancellation (A : I → Fin m → ℝ) (u : I → ℝ) : Prop :=
  InCancellationCone A u ∧ u ≠ 0 ∧
    ∀ v, InCancellationCone A v → v ≠ 0 → (∀ i, u i = 0 → v i = 0) →
      ∀ i, v i = 0 ↔ u i = 0

private theorem sum_pos_of_nonnegative_ne_zero (u : I → ℝ)
    (hu : ∀ i, 0 ≤ u i) (hne : u ≠ 0) : 0 < ∑ i, u i := by
  have hpos : ∃ i, 0 < u i := by
    by_contra hn
    apply hne
    funext i
    exact le_antisymm (not_lt.mp (not_exists.mp hn i)) (hu i)
  obtain ⟨i, hi⟩ := hpos
  exact Finset.sum_pos' (fun j _ => hu j) ⟨i, Finset.mem_univ _, hi⟩

/-- Extreme rays and support-minimal positive cancellations are the same rays. -/
theorem extreme_ray_iff_minimal_positive (A : I → Fin m → ℝ) (u : I → ℝ) :
    ExtremeCancellationRay A u ↔ MinimalPositiveCancellation A u := by
  classical
  constructor
  · intro hu
    obtain ⟨C, t, ht, he⟩ := (extreme_ray_iff_positive_circuit A u).mp hu
    refine ⟨hu.1, hu.2.1, ?_⟩
    intro v hv hvne hs i
    have hsv : ∀ j, j ∉ C.support → v j = 0 := by
      intro j hj
      apply hs j
      rw [he]
      change t * C.weights j = 0
      rw [C.weights_zero (by simpa only [C.mem_support, not_exists] using hj), mul_zero]
    have hvscale := C.kernel_unique_global v hv.2 hsv i
    have hsum := sum_pos_of_nonnegative_ne_zero v hv.1 hvne
    have hui := congrFun he i
    simp only [Pi.smul_apply, smul_eq_mul] at hui
    rw [hvscale, hui, mul_eq_zero, mul_eq_zero]
    simp [ne_of_gt ht, ne_of_gt hsum]
  · intro hu
    have hsum := sum_pos_of_nonnegative_ne_zero u hu.1.1 hu.2.1
    have hpos : ∃ i, 0 < u i := by
      by_contra hn
      have hz : ∀ i, u i = 0 := fun i =>
        le_antisymm (not_lt.mp (not_exists.mp hn i)) (hu.1.1 i)
      simp [hz] at hsum
    obtain ⟨C, hs⟩ := exists_positiveCircuit A u hu.1.1 hpos hu.1.2
    have hsc : ∀ i, u i = 0 → C.weights i = 0 := by
      intro i hi
      apply C.weights_zero
      intro k hk
      have hposk := hs k
      rw [hk, hi] at hposk
      exact lt_irrefl _ hposk
    have hzeros := hu.2.2 C.weights C.extreme_weights.1 C.extreme_weights.2.1 hsc
    have hus : ∀ i, i ∉ C.support → u i = 0 := by
      intro i hi
      exact (hzeros i).mp
        (C.weights_zero (by simpa only [C.mem_support, not_exists] using hi))
    apply (extreme_ray_iff_positive_circuit A u).mpr
    refine ⟨C, ∑ i, u i, hsum, ?_⟩
    funext i
    exact C.kernel_unique_global u hu.1.2 hus i

/-- A positive circuit is also minimally linearly dependent: even a signed
cancellation on a proper subset of its support must vanish. -/
theorem PositiveCircuit.proper_supported_kernel_zero {A : I → Fin m → ℝ}
    (C : PositiveCircuit A) (v : I → ℝ)
    (hv : ∑ i, v i • A i = 0)
    (hs : ∀ i, i ∉ C.support → v i = 0)
    (hproper : ∃ i ∈ C.support, v i = 0) : v = 0 := by
  obtain ⟨i, hi, hvi⟩ := hproper
  obtain ⟨k, rfl⟩ := (C.mem_support i).mp hi
  have hki := C.kernel_unique_global v hv hs (C.index k)
  rw [C.weights_index, hvi] at hki
  have hsum : (∑ j, v j) = 0 :=
    (mul_eq_zero.mp hki.symm).resolve_right (ne_of_gt (C.positive k))
  funext j
  simpa only [hsum, zero_mul, Pi.zero_apply] using C.kernel_unique_global v hv hs j

end
end NetworkSimplex.Chain.Threshold
