"""Count power(x, 3) nodes whose base variable is exactly 0 in the exactly feasible points
(waterno2_06-24 exact points of R/publication/primal/water-ann-kan/points/*.exact.json;
pricing050 point regenerated by a /tmp copy of the verifier's v_pricing050.py, saved in
logs/pricing050_own_point.txt). Read-only."""
import json
import os
import sys
from fractions import Fraction

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import osilx_ro as osilx  # noqa: E402

P = os.path.expanduser('~/.cache/minlplib/minlplib/osil/')
REPO = os.environ.get("REPO", os.path.expanduser("~/repo/minlp-notes"))
PTS = os.path.join(REPO, "research-20260929/publication/primal/water-ann-kan/points")


def power_vars(I):
    pv = {}

    def walk(t):
        if t is None or t[0] in ('num', 'var'):
            return
        if t[0] == 'power':
            assert t[1][0] == 'var' and t[2][0] == 'num'
            pv[t[1][1]] = t[2][1]
        for c in t[1:]:
            walk(c)
    for c in I['cons'] + [I['obj']]:
        walk(c['nl'])
    return pv


for T in ('06', '09', '12', '18', '24'):
    I = osilx.read(P + f'waterno2_{T}.osil')
    pv = power_vars(I)
    x = json.load(open(os.path.join(PTS, f'waterno2_{T}.exact.json')))['x']
    z = [I['names'][j] for j in pv if x.get(I['names'][j]) == '0']
    print(f"waterno2_{T}: power nodes on {len(pv)} variables (exponents {sorted(set(pv.values()))}); "
          f"bases equal to 0 at the exact point: {len(z)}")
I = osilx.read(P + 'pricing050.osil')
pv = power_vars(I)
x = {}
for line in open(os.path.join(HERE, 'logs', 'pricing050_own_point.txt')):
    k, v = line.split()
    x[k] = Fraction(v)
z = [I['names'][j] for j in pv if x[I['names'][j]] == 0]
print(f"pricing050: power nodes on {len(pv)} variables (exponents {sorted(set(pv.values()))}); "
      f"bases equal to 0 at the verifier's point: {len(z)} {z}")
