"""optcdeg2: partial Lagrangian. The dynamics rows t = 0..m-1 (the "head", where the
KKT multiplier lam_t < 0 makes the full Lagrangian concave in v_t) are kept exact; rows
t >= m are dualized with the same multipliers as in optcdeg2_bound.py.

Lower bound = min_{u in [-0.2,0.2]^m} J(u) + (separable Lagrangian terms of t > m),
  J(u) = (h/2) sum_{t=0}^{m-1} y_t^2 + Phi(y_m, v_m),
  Phi(y, v) = (h/2) y^2 + (-mu_m + 0.02 h lam_m) y + (-h mu_m - lam_m) v + 0.2 h lam_m v^2,
where (y_t, v_t) is the exact head trajectory generated by u from (10, 0).
Monotonicity certificate: the gradient dJ/du_t = h p_v(t+1) is computed by the discrete
adjoint recursion in interval arithmetic over the forward reachable intervals of all
u in the box. If every p_v(t+1) > 0, J is nondecreasing in each coordinate on the box,
so min J = J(-0.2, ..., -0.2), which is evaluated by interval simulation.
"""
import json
import sys
import time

import numpy as np

import ivnp as I
from optcdeg2_blockdp import C02H, C02h2, H, U, coeffs, load_bounds
from optcdeg2_common import N


def head_forward(m, ctrl=None):
    """Interval states for t = 0..m. ctrl=None: u in [-0.2, 0.2]; else a point control value."""
    Y = [I.point(np.array([10.0]))]
    V = [I.point(np.array([0.0]))]
    uu = (np.array([U[0]]), np.array([U[1]])) if ctrl is None else I.const(ctrl)
    uu = (np.atleast_1d(uu[0]), np.atleast_1d(uu[1]))
    for t in range(m):
        y, v = Y[-1], V[-1]
        Y.append(I.add(y, I.mul(H, v)))
        acc = I.sub(I.sub(uu, I.mul(I.const("0.02"), y)), I.mul(I.const("0.2"), I.sqr(v)))
        V.append(I.add(v, I.mul(H, acc)))
    return Y, V


def run(m):
    mu, lam = np.load("logs/optcdeg2_mu.npy"), np.load("logs/optcdeg2_lam.npy")
    Vg, Yg = load_bounds()
    Mm, Lm = I.point(mu[m:m + 1]), I.point(lam[m:m + 1])
    cy = I.add(I.neg(Mm), I.mul(C02H, Lm))            # -mu_m + 0.02 h lam_m
    cv = I.sub(I.neg(I.mul(H, Mm)), Lm)               # -h mu_m - lam_m
    av = I.mul(C02h2, Lm)                             # 0.2 h lam_m
    # 1) reachable intervals over the head for all controls in the box
    Y, V = head_forward(m)
    # 2) interval adjoint
    py = I.add(I.mul(H, Y[m]), cy)
    pv = I.add(cv, I.mul(I.mul(I.const(2.0), av), V[m]))
    minpv = np.inf
    for t in range(m - 1, -1, -1):
        minpv = min(minpv, float(pv[0][0]))            # p_v(t+1) lower end
        one = I.point(np.array([1.0]))
        py_new = I.sub(I.add(I.mul(H, Y[t]) if t >= 1 else I.point(np.array([0.0])), py), I.mul(C02H, pv))
        pv_new = I.add(I.mul(H, py), I.mul(I.sub(one, I.mul(I.mul(I.const("0.4"), H), V[t])), pv))
        py, pv = py_new, pv_new
    monotone = minpv > 0
    # 3) J at the lower corner u = -0.2
    Yc, Vc = head_forward(m, ctrl="-0.2")
    J = I.mul(I.mul(I.const("0.5"), H), I.sqr(Yc[0]))
    for t in range(1, m):
        J = I.add(J, I.mul(I.mul(I.const("0.5"), H), I.sqr(Yc[t])))
    ym, vm = Yc[m], Vc[m]
    J = I.add(J, I.add(I.add(I.mul(I.mul(I.const("0.5"), H), I.sqr(ym)), I.mul(cy, ym)),
                       I.add(I.mul(cv, vm), I.mul(av, I.sqr(vm)))))
    Jlo = float(J[0][0])
    # 4) separable terms for t > m (y_t, v_t) and t >= m (u_t)
    parts = []
    b = I.add(I.sub(I.point(mu[m:N - 1]), I.point(mu[m + 1:N])), I.mul(C02H, I.point(lam[m + 1:N])))  # t = m+1..N-1
    parts.append(I.neg(I.div_pos(I.sqr(b), I.mul(I.const(2.0), H)))[0])
    parts.append(I.neg(I.div_pos(I.sqr(I.point(mu[-1:])), I.mul(I.const(2.0), H)))[0])
    parts.append(I.neg(I.mul(I.mul(I.const("0.2"), H), I.absval(I.point(lam[m:N]))))[0])
    A, Bv = coeffs(mu, lam)
    ts = np.arange(m + 1, N)
    parts.append(I.quad_min_lo((A[0][ts], A[1][ts]), (Bv[0][ts], Bv[1][ts]), Vg[0][ts], Vg[1][ts]))
    rest = np.float64(0.0)
    for p in parts:
        rest = I.dn(rest + I.sum_lo(p))
    total = float(I.dn(rest + Jlo)) if monotone else None
    return dict(m=m, monotone=bool(monotone), min_pv_lower=minpv, J_corner=Jlo, rest=float(rest), dual_bound=total,
                head_v_range=[float(V[m][0][0]), float(V[m][1][0])])


if __name__ == "__main__":
    out = []
    for m in [int(a) for a in sys.argv[1:]]:
        t0 = time.time()
        r = run(m)
        r["seconds"] = time.time() - t0
        print(json.dumps(r), flush=True)
        out.append(r)
    with open("logs/optcdeg2_head.jsonl", "a") as f:
        for r in out:
            f.write(json.dumps(r) + "\n")
