"""Exact checks of the certificate note's two scope counterexamples.

Run with Python's standard library only. These checks verify algebraic
witnesses; the universal conclusions are proved in the note.
"""

from fractions import Fraction as F


def quadratic(x, coefficients):
    a, b, c = coefficients
    return a * x * x + b * x + c


# f1 < 0 holds between -2 and 2; f2 < 0 holds outside -1 and 3.
f1, f2 = (1, 0, -4), (-1, 2, 3)
assert quadratic(-2, f1) == quadratic(2, f1) == 0
assert quadratic(-1, f2) == quadratic(3, f2) == 0
assert quadratic(F(-3, 2), f1) < 0 and quadratic(F(-3, 2), f2) < 0

# The convex-certificate cone is generated by (1,0) and (1,1).
# Both generators have PSD quadratic parts and strictly admit x=0.
for lam in ((1, 0), (1, 1)):
    assert lam[0] * f1[0] + lam[1] * f2[0] >= 0
    assert lam[0] * f1[2] + lam[1] * f2[2] < 0

# The Shor witness has x=0 and X=diag(7/2,0,0), so its lifted matrix is PSD.
lifted_diagonal = (F(1), F(7, 2), F(0), F(0))
assert all(value >= 0 for value in lifted_diagonal)
residuals = tuple(a * lifted_diagonal[1] + c for a, _, c in (f1, f2))
assert residuals == (F(-1, 2), F(-1, 2))
print("HHC does not make globally convex aggregations exact: witnesses passed")

# Perturbed images of e1 and e2 have midpoint (0,epsilon,0).
# Recover a=x1^2, b=x1*x2, c=x2^2 from a proposed midpoint preimage.
for epsilon in (F(1), F(1, 10), F(1, 10**6)):
    first, second = (F(1), 1 + epsilon, F(1)), (F(-1), -1 + epsilon, F(-1))
    midpoint = tuple((p + q) / 2 for p, q in zip(first, second))
    u, perturbed_sum, perturbed_product = midpoint
    square_sum = (perturbed_sum - u) / epsilon
    a, c = (square_sum + u) / 2, (square_sum - u) / 2
    b = (perturbed_product - u) / (2 * epsilon)
    assert (a, b, c) == (F(1, 2), F(0), F(1, 2))
    assert a * c - b * b == F(1, 4)  # A vector's 2x2 Gram determinant is zero.
print("HHC need not imply stable convexity: midpoint contradictions passed")
