import Formal.PotentialFlow.RationalData

/-! Generated by `topics/03-potential-flow/generate_example.py`.
Source: `code/potential_flow_mpd/envelope_certificate_example.json`.
SHA-256: 1abedf5775a147c9ad3cc699193ecb79c4948c99b0e489d86c5e715be5b38fa3
The generator only translates data; Lean proves all certificate conditions.
-/

namespace PotentialFlow.Example

def network : RationalNetwork 5 6 where
  tail := ![⟨0, by decide⟩,
    ⟨0, by decide⟩,
    ⟨0, by decide⟩,
    ⟨1, by decide⟩,
    ⟨1, by decide⟩,
    ⟨1, by decide⟩]
  head := ![⟨2, by decide⟩,
    ⟨3, by decide⟩,
    ⟨4, by decide⟩,
    ⟨2, by decide⟩,
    ⟨3, by decide⟩,
    ⟨4, by decide⟩]
  positive := ![(2 / 3 : ℚ),
    (7 / 3 : ℚ),
    (4 / 3 : ℚ),
    (5 / 3 : ℚ),
    (1 : ℚ),
    (4 / 3 : ℚ)]
  negative := ![(4 / 3 : ℚ),
    (4 / 3 : ℚ),
    (2 / 3 : ℚ),
    (1 : ℚ),
    (5 / 3 : ℚ),
    (2 : ℚ)]

def nominations : Fin 5 → ℚ := ![(1 : ℚ),
    (-4 / 3 : ℚ),
    (-1 / 3 : ℚ),
    (-1 : ℚ),
    (5 / 3 : ℚ)]

def certificate : RationalCertificate 5 6 where
  flow := ![(27935433837371281 / 27021597764222976 : ℚ),
    (6649598035570767 / 9007199254740992 : ℚ),
    (-10431315089930303 / 13510798882111488 : ℚ),
    (-18928234582630289 / 27021597764222976 : ℚ),
    (2357601219170225 / 9007199254740992 : ℚ),
    (-4028894348974059 / 4503599627370496 : ℚ)]
  potentials := ![(5026077258192023 / 9007199254740992 : ℚ),
    (-5811384347384031 / 9007199254740992 : ℚ),
    (-2783473059815251 / 18014398509481984 : ℚ),
    (-200889756828429 / 281474976710656 : ℚ),
    (4302757918804681 / 4503599627370496 : ℚ)]
  rootUpper := ![(445257557507992931123039 / 604462909807314587353088 : ℚ),
    (1134994152043844685830355 / 1208925819614629174706176 : ℚ),
    (370922347180901625812129 / 1208925819614629174706176 : ℚ),
    (103881090981868428988951 / 302231454903657293676544 : ℚ),
    (10839406856599222275367 / 604462909807314587353088 : ℚ),
    (865521462837545533821113 / 604462909807314587353088 : ℚ)]
  gap :=
    (97292779578702984337080334819373740393 /
      177572448935704704561747707175028386888195803971584 : ℚ)
  radius := (102885025499522195717 / 604462909807314587353088 : ℚ)

set_option maxRecDepth 10000 in
theorem accepted : network.Accepted (by decide : 0 < 6) nominations certificate := by
  decide +kernel

theorem radius_lt_one_five_thousandth : certificate.radius < (1 / 5000 : ℚ) := by
  norm_num [certificate]

end PotentialFlow.Example
