import Formal.PotentialFlow.Bregman
import Formal.PotentialFlow.Curvature
import Formal.PotentialFlow.Laplacian
import Formal.PotentialFlow.Support
import Formal.PotentialFlow.TwoPath

/-!
# Exact comparison of the three enclosures on the two-path example

This module finishes the worked example `ex:a-cert-paths` of the certified-computation
appendix on the network `PotentialFlow.TwoPath.net L` of `TwoPath.lean`.  Throughout,
`0 < L`, `0 < eps < 1`, the trial flow is `trial L eps = pathFlow L (1 + eps) (1 - eps)`,
its exact energy gap is `delta = 2 * L * eps ^ 2`, and `sel e0` is the selector of one
edge `e0` of the first path.

## Main results

* `circulation_iff`, `loads_gen`: the circulation space is one dimensional, generated by
  `gen L = pathFlow L 1 (-1)`.
* `mem_supportSet_iff`, `supportGoal_eq_Icc`, `isGreatest_supportGoal`,
  `isLeast_supportGoal`, `supportGoal_width`: the support set is exactly the part of the
  conserved family with path value within `eps` of one, so the exact support interval of a
  first-path edge is `[1 - eps, 1 + eps]`, of width `2 * eps` (CC34).
* `lam_consistency`, `drops_dualPotential`, `root_test_dual`, `supportBound_upper_eq`,
  `supportBound_lower_eq`, `supportBound_upper_sound`, `supportBound_lower_sound`: the
  explicit rational dual data with `lam = 1 / (4 * L * eps)` passes the support root test
  with equality and attains both exact endpoints (CC35).
* `edgeBregman_one_shift`, `existsUnique_bregShape_pos`, `existsUnique_bregShape_neg`,
  `gap_lt_cube`, `edgeBregman_aPos`, `edgeBregman_aNeg`, `existsUnique_edgeBregman_ge`,
  `existsUnique_edgeBregman_le`, `tendsto_bregmanWidth`: the separate-edge Bregman
  expansion, existence and uniqueness of the two boundary displacements for the divergence
  itself, and the asymptotic width (CC36).
* `optimalFactor_sel`, `factor_eq_of_optimalFactor`, `hEdge_pos`, `optimalFactor_hEdge`,
  `tendsto_hEdge`, `tendsto_hSum`, `tendsto_laplacianWidth`: the optimal Laplacian factor
  `1 / ∑ e, h e` for a positive curvature vector, its instance at the curvature floors of
  the example, and the asymptotics of the optimized Laplacian width (CC37).
* `edgeBregman_warning`, `gap_warning`, `delta_lt_edgeBregman_warning`,
  `mem_supportSet_warning`, `supportSet_violates_edgeBregman`: the `L = 1`, `eps = 1/10`
  warning (CC38).
-/

namespace PotentialFlow.TwoPath

noncomputable section

open Filter Topology

/-! ### Notation for the example -/

/-- The trial flow of `ex:a-cert-paths`: `1 + eps` on the first path, `1 - eps` on the
second. -/
def trial (L : ℕ) (eps : ℝ) : Fin (2 * L) → ℝ := pathFlow L (1 + eps) (1 - eps)

/-- Unfolding lemma for the trial flow. -/
theorem trial_apply (L : ℕ) (eps : ℝ) (e : Fin (2 * L)) :
    trial L eps e = if (e : ℕ) < L then 1 + eps else 1 - eps := rfl

/-- The generator of the circulation space: `+1` on the first path, `-1` on the second. -/
def gen (L : ℕ) : Fin (2 * L) → ℝ := pathFlow L 1 (-1)

/-- Unfolding lemma for the circulation generator. -/
theorem gen_apply (L : ℕ) (e : Fin (2 * L)) :
    gen L e = if (e : ℕ) < L then 1 else -1 := rfl

/-- The linear goal selecting the single edge `e0`. -/
def sel {L : ℕ} (e0 : Fin (2 * L)) : Fin (2 * L) → ℝ := fun e => if e = e0 then 1 else 0

/-- A selector goal reads off a single coordinate. -/
theorem sum_sel_mul {L : ℕ} (e0 : Fin (2 * L)) (x : Fin (2 * L) → ℝ) :
    ∑ e, sel e0 e * x e = x e0 := by
  simp only [sel, ite_mul, one_mul, zero_mul]
  rw [Finset.sum_ite_eq' Finset.univ e0 x, if_pos (Finset.mem_univ e0)]

/-- Path-constant flows add coordinatewise. -/
theorem pathFlow_add (L : ℕ) (a b c d : ℝ) :
    pathFlow L a b + pathFlow L c d = pathFlow L (a + c) (b + d) := by
  funext e
  simp only [Pi.add_apply, pathFlow_apply]
  split <;> rfl

/-! ### The circulation space -/

/-- The circulations of the two-path network are exactly the multiples of `gen L`. -/
theorem circulation_iff {L : ℕ} (hL : 0 < L) (z : Fin (2 * L) → ℝ) :
    (net L).loads z = 0 ↔ ∃ t : ℝ, z = pathFlow L t (-t) := by
  constructor
  · intro hz
    have hshift : (net L).Feasible (nom L) (pathFlow L 1 1 + z) := by
      have : (net L).loads (pathFlow L 1 1 + z)
          = (net L).loads (pathFlow L 1 1) + (net L).loads z :=
        map_add (net L).divergenceLinear _ _
      have hone : (net L).loads (pathFlow L 1 1) = nom L := feasible_one L hL
      simp only [Network.Feasible, this, hone, hz, add_zero]
    obtain ⟨t, ht⟩ := (feasible_iff hL _).mp hshift
    refine ⟨t - 1, ?_⟩
    funext e
    have hc := congrFun ht e
    simp only [Pi.add_apply, pathFlow_apply] at hc
    rw [pathFlow_apply]
    by_cases hlt : (e : ℕ) < L
    · simp only [if_pos hlt] at hc ⊢; linarith
    · simp only [if_neg hlt] at hc ⊢; linarith
  · rintro ⟨t, rfl⟩
    have hfe : (net L).Feasible (nom L) (pathFlow L (1 + t) (2 - (1 + t))) :=
      feasible_pathFlow hL (1 + t)
    have hsum : pathFlow L 1 1 + pathFlow L t (-t) = pathFlow L (1 + t) (2 - (1 + t)) := by
      rw [pathFlow_add, show (2 : ℝ) - (1 + t) = 1 + -t by ring]
    have hone : (net L).loads (pathFlow L 1 1) = nom L := feasible_one L hL
    have hadd : (net L).loads (pathFlow L 1 1 + pathFlow L t (-t))
        = (net L).loads (pathFlow L 1 1) + (net L).loads (pathFlow L t (-t)) :=
      map_add (net L).divergenceLinear _ _
    have h1 : (net L).loads (pathFlow L (1 + t) (2 - (1 + t))) = nom L := hfe
    rw [← hsum, hadd, hone] at h1
    funext v
    have hv := congrFun h1 v
    simp only [Pi.add_apply] at hv
    simp only [Pi.zero_apply]
    linarith

/-- The generator is a circulation. -/
theorem loads_gen (L : ℕ) (hL : 0 < L) : (net L).loads (gen L) = 0 :=
  (circulation_iff hL _).mpr ⟨1, rfl⟩

/-! ### CC34: the exact support set and the exact support interval -/

/-- The family energy depends on the path value only through its distance to one. -/
theorem familyEnergy_abs (L : ℕ) (t : ℝ) :
    familyEnergy L t = familyEnergy L (1 + |t - 1|) := by
  rcases le_or_gt 1 t with h | h
  · rw [abs_of_nonneg (by linarith : (0 : ℝ) ≤ t - 1), show (1 : ℝ) + (t - 1) = t by ring]
  · rw [abs_of_neg (by linarith : t - 1 < 0), familyEnergy_symm L (-(t - 1)),
      show (1 : ℝ) - -(t - 1) = t by ring]

/-- Along the conserved family the energy sublevel sets are the symmetric intervals
around the physical path value `1`. -/
theorem familyEnergy_le_iff (L : ℕ) (hL : 0 < L) {t r : ℝ} (hr : 0 ≤ r) :
    familyEnergy L t ≤ familyEnergy L (1 + r) ↔ |t - 1| ≤ r := by
  have hm1 : (1 : ℝ) + |t - 1| ∈ Set.Ici (1 : ℝ) :=
    Set.mem_Ici.mpr (by linarith [abs_nonneg (t - 1)])
  have hm2 : (1 : ℝ) + r ∈ Set.Ici (1 : ℝ) := Set.mem_Ici.mpr (by linarith)
  rw [familyEnergy_abs L t, (familyEnergy_strictMonoOn L hL).le_iff_le hm1 hm2]
  constructor <;> intro h <;> linarith

/-- The trial flow is the member of the conserved family with parameter `1 + eps`. -/
theorem energy_trial_eq (L : ℕ) (eps : ℝ) :
    (net L).energy (trial L eps) = familyEnergy L (1 + eps) := by
  change (net L).energy (pathFlow L (1 + eps) (1 - eps)) = _
  rw [pathFlow_trial]
  rfl

/-- **CC34.**  The support set of the trial flow is exactly the part of the conserved
family whose path value is within `eps` of the physical value `1`. -/
theorem mem_supportSet_iff {L : ℕ} (hL : 0 < L) {eps : ℝ} (hε : 0 ≤ eps)
    (x : Fin (2 * L) → ℝ) :
    x ∈ (net L).supportSet (nom L) (trial L eps) ↔
      ∃ t : ℝ, |t - 1| ≤ eps ∧ x = pathFlow L t (2 - t) := by
  rw [Network.mem_supportSet, energy_trial_eq]
  constructor
  · rintro ⟨hfeas, hE⟩
    obtain ⟨t, rfl⟩ := (feasible_iff hL x).mp hfeas
    exact ⟨t, (familyEnergy_le_iff L hL hε).mp hE, rfl⟩
  · rintro ⟨t, ht, rfl⟩
    exact ⟨feasible_pathFlow hL t, (familyEnergy_le_iff L hL hε).mpr ht⟩

/-- **CC34.**  The exact range of a first-path edge selector on the support set is the
interval `[1 - eps, 1 + eps]`. -/
theorem supportGoal_eq_Icc {L : ℕ} (hL : 0 < L) {eps : ℝ} (hε : 0 ≤ eps)
    {e0 : Fin (2 * L)} (he0 : (e0 : ℕ) < L) :
    {r : ℝ | ∃ x ∈ (net L).supportSet (nom L) (trial L eps), r = ∑ e, sel e0 e * x e}
      = Set.Icc (1 - eps) (1 + eps) := by
  ext r
  simp only [Set.mem_ofPred_eq, Set.mem_Icc]
  constructor
  · rintro ⟨x, hx, rfl⟩
    obtain ⟨t, ht, rfl⟩ := (mem_supportSet_iff hL hε x).mp hx
    obtain ⟨h1, h2⟩ := abs_le.mp ht
    rw [sum_sel_mul, pathFlow_first _ _ _ he0]
    exact ⟨by linarith, by linarith⟩
  · rintro ⟨hlo, hhi⟩
    refine ⟨pathFlow L r (2 - r), ?_, ?_⟩
    · exact (mem_supportSet_iff hL hε _).mpr
        ⟨r, abs_le.mpr ⟨by linarith, by linarith⟩, rfl⟩
    · rw [sum_sel_mul, pathFlow_first _ _ _ he0]

/-- **CC34.**  The upper endpoint `1 + eps` is the exact maximum of the selector goal. -/
theorem isGreatest_supportGoal {L : ℕ} (hL : 0 < L) {eps : ℝ} (hε : 0 ≤ eps)
    {e0 : Fin (2 * L)} (he0 : (e0 : ℕ) < L) :
    IsGreatest {r : ℝ | ∃ x ∈ (net L).supportSet (nom L) (trial L eps),
      r = ∑ e, sel e0 e * x e} (1 + eps) := by
  rw [supportGoal_eq_Icc hL hε he0]
  exact isGreatest_Icc (by linarith)

/-- **CC34.**  The lower endpoint `1 - eps` is the exact minimum of the selector goal. -/
theorem isLeast_supportGoal {L : ℕ} (hL : 0 < L) {eps : ℝ} (hε : 0 ≤ eps)
    {e0 : Fin (2 * L)} (he0 : (e0 : ℕ) < L) :
    IsLeast {r : ℝ | ∃ x ∈ (net L).supportSet (nom L) (trial L eps),
      r = ∑ e, sel e0 e * x e} (1 - eps) := by
  rw [supportGoal_eq_Icc hL hε he0]
  exact isLeast_Icc (by linarith)

/-- **CC34.**  The exact support interval of a first-path edge has width `2 * eps`. -/
theorem supportGoal_width {L : ℕ} (hL : 0 < L) {eps : ℝ} (hε : 0 ≤ eps)
    {e0 : Fin (2 * L)} (he0 : (e0 : ℕ) < L) :
    {r : ℝ | ∃ x ∈ (net L).supportSet (nom L) (trial L eps), r = ∑ e, sel e0 e * x e}
        = Set.Icc (1 - eps) (1 + eps) ∧ (1 + eps) - (1 - eps) = 2 * eps :=
  ⟨supportGoal_eq_Icc hL hε he0, by ring⟩

/-! ### CC35: the rational dual data attaining the exact support endpoints -/

/-- The dual scaling of the example, `lambda = 1 / (4 L eps)`. -/
def lam (L : ℕ) (eps : ℝ) : ℝ := 1 / (4 * L * eps)

/-- The dual scaling is strictly positive. -/
theorem lam_pos {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) : 0 < lam L eps := by
  have hLR : (0 : ℝ) < L := by exact_mod_cast hL
  unfold lam
  positivity

/-- The potential-consistency identity of `ex:a-cert-paths`: the two prescribed path sums
of drops agree exactly for `lambda = 1 / (4 L eps)`. -/
theorem lam_consistency {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) :
    1 - lam L eps * L * (1 + eps) ^ 2 = -(lam L eps * L * (1 - eps) ^ 2) := by
  have hLR : (0 : ℝ) < L := by exact_mod_cast hL
  have hne : (4 : ℝ) * L * eps ≠ 0 := by positivity
  unfold lam
  field_simp
  ring

/-- The equivalent form of `lam_consistency` used to build the node potentials. -/
theorem lam_consistency' {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) :
    (1 : ℝ) = (L : ℝ) * lam L eps * ((1 + eps) ^ 2 - (1 - eps) ^ 2) := by
  have := lam_consistency hL h0
  ring_nf at this ⊢
  linarith

/-- The mirrored consistency identity for the certificate of the lower endpoint. -/
theorem lam_consistency_neg {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) :
    (-1 : ℝ) = (L : ℝ) * lam L eps * ((1 - eps) ^ 2 - (1 + eps) ^ 2) := by
  have := lam_consistency' hL h0
  linarith [this]

/-- Node value at position `i` of path `p` for the dual potentials of the example: the sum
of the remaining prescribed drops of that path, measured from the sink. -/
def dualVal (L : ℕ) (lm : ℝ) (i0 : ℕ) (σ a b : ℝ) (p i : ℕ) : ℝ :=
  if p = 0 then σ * (if i ≤ i0 then 1 else 0) - ((L : ℝ) - i) * lm * a ^ 2
  else -(((L : ℝ) - i) * lm * b ^ 2)

/-- Value of `dualVal` on the first path. -/
theorem dualVal_zero (L : ℕ) (lm : ℝ) (i0 : ℕ) (σ a b : ℝ) (i : ℕ) :
    dualVal L lm i0 σ a b 0 i
      = σ * (if i ≤ i0 then 1 else 0) - ((L : ℝ) - i) * lm * a ^ 2 := if_pos rfl

/-- Value of `dualVal` on the second path. -/
theorem dualVal_one (L : ℕ) (lm : ℝ) (i0 : ℕ) (σ a b : ℝ) (i : ℕ) :
    dualVal L lm i0 σ a b 1 i = -(((L : ℝ) - i) * lm * b ^ 2) := if_neg one_ne_zero

/-- The dual node potentials of the example, obtained by accumulating the prescribed drops
from the sink; the source value is read off the second path. -/
def dualPotential (L : ℕ) (lm : ℝ) (i0 : ℕ) (σ a b : ℝ) : Fin (2 * L) → ℝ := fun v =>
  if (v : ℕ) = 0 then dualVal L lm i0 σ a b 1 0
  else if (v : ℕ) = 1 then 0
  else dualVal L lm i0 σ a b (((v : ℕ) - 2) / (L - 1)) (((v : ℕ) - 2) % (L - 1) + 1)

/-- Unfolding lemma for the dual node potentials. -/
theorem dualPotential_apply (L : ℕ) (lm : ℝ) (i0 : ℕ) (σ a b : ℝ) (v : Fin (2 * L)) :
    dualPotential L lm i0 σ a b v =
      if (v : ℕ) = 0 then dualVal L lm i0 σ a b 1 0
      else if (v : ℕ) = 1 then 0
      else dualVal L lm i0 σ a b (((v : ℕ) - 2) / (L - 1)) (((v : ℕ) - 2) % (L - 1) + 1) := rfl

/-- The dual potential at the node at position `i` of path `p` is the accumulated value
`dualVal`; the two paths agree at the source exactly by the consistency identity. -/
theorem dualPotential_of_val {L : ℕ} (hL : 0 < L) (lm : ℝ) {i0 : ℕ} (hi0 : i0 < L)
    {σ a b : ℝ} (hcons : σ = (L : ℝ) * lm * (a ^ 2 - b ^ 2)) {p i : ℕ} (hp : p < 2)
    (hi : i ≤ L) (v : Fin (2 * L)) (hv : (v : ℕ) = nodeIdx L p i) :
    dualPotential L lm i0 σ a b v = dualVal L lm i0 σ a b p i := by
  by_cases h0 : i = 0
  · have hn : nodeIdx L p i = 0 := by unfold nodeIdx; rw [if_pos h0]
    rw [dualPotential_apply, hv, hn, if_pos rfl, h0]
    rcases (show p = 0 ∨ p = 1 by omega) with rfl | rfl
    · rw [dualVal_zero, dualVal_one, if_pos (Nat.zero_le i0), hcons]
      push_cast
      ring
    · rw [dualVal_one]
  · by_cases h1 : i = L
    · have hn : nodeIdx L p i = 1 := by unfold nodeIdx; rw [if_neg h0, if_pos h1]
      rw [dualPotential_apply, hv, hn, if_neg one_ne_zero, if_pos rfl, h1]
      rcases (show p = 0 ∨ p = 1 by omega) with rfl | rfl
      · rw [dualVal_zero, if_neg (by omega : ¬(L ≤ i0))]
        ring
      · rw [dualVal_one]
        ring
    · have hi1 : 1 ≤ i := by omega
      have hL2 : 2 ≤ L := by omega
      have hn : nodeIdx L p i = 2 + p * (L - 1) + (i - 1) := by
        unfold nodeIdx; rw [if_neg h0, if_neg h1]
      rw [dualPotential_apply, hv, hn,
        if_neg (by omega : ¬(2 + p * (L - 1) + (i - 1) = 0)),
        if_neg (by omega : ¬(2 + p * (L - 1) + (i - 1) = 1)),
        show 2 + p * (L - 1) + (i - 1) - 2 = (L - 1) * p + (i - 1) by
          rw [Nat.mul_comm]; omega,
        Nat.mul_add_div (by omega : 0 < L - 1),
        Nat.div_eq_of_lt (by omega : i - 1 < L - 1), Nat.add_zero, Nat.mul_add_mod,
        Nat.mod_eq_of_lt (by omega : i - 1 < L - 1), show i - 1 + 1 = i by omega]

/-- **CC35.**  The prescribed drops of the dual potential are exactly `σ w - lambda t^2`. -/
theorem drops_dualPotential {L : ℕ} (hL : 0 < L) (lm : ℝ) {i0 : ℕ} (hi0 : i0 < L)
    {σ a b : ℝ} (hcons : σ = (L : ℝ) * lm * (a ^ 2 - b ^ 2)) {e0 : Fin (2 * L)}
    (he0 : (e0 : ℕ) = i0) (e : Fin (2 * L)) :
    (net L).drops (dualPotential L lm i0 σ a b) e
      = σ * sel e0 e - lm * pathFlow L a b e ^ 2 := by
  have hmlt := posNum_lt e
  rw [Network.drops,
    dualPotential_of_val hL lm hi0 hcons (pathNum_lt e) hmlt.le _ (tail_val L e),
    dualPotential_of_val hL lm hi0 hcons (pathNum_lt e) hmlt _ (head_val L e)]
  obtain ⟨q, hq⟩ : ∃ q, (e : ℕ) / L = q := ⟨_, rfl⟩
  have hdm : L * q + (e : ℕ) % L = (e : ℕ) := by rw [← hq]; exact Nat.div_add_mod _ _
  have hq2 : q < 2 := by rw [← hq]; exact pathNum_lt e
  rw [hq]
  interval_cases q
  · have hlt : (e : ℕ) < L := by omega
    have hmod : (e : ℕ) % L = (e : ℕ) := Nat.mod_eq_of_lt hlt
    have hsel : sel e0 e
        = (if (e : ℕ) ≤ i0 then (1 : ℝ) else 0)
          - (if (e : ℕ) + 1 ≤ i0 then (1 : ℝ) else 0) := by
      unfold sel
      by_cases hee : (e : ℕ) = i0
      · rw [if_pos (Fin.ext (by omega) : e = e0), if_pos (by omega : (e : ℕ) ≤ i0),
          if_neg (by omega : ¬((e : ℕ) + 1 ≤ i0))]
        norm_num
      · rw [if_neg (fun h : e = e0 => hee (by rw [h, he0]))]
        rcases Nat.lt_or_ge (e : ℕ) i0 with hlt' | hge'
        · rw [if_pos (by omega : (e : ℕ) ≤ i0), if_pos (by omega : (e : ℕ) + 1 ≤ i0)]
          norm_num
        · rw [if_neg (by omega : ¬((e : ℕ) ≤ i0)),
            if_neg (by omega : ¬((e : ℕ) + 1 ≤ i0))]
          norm_num
    rw [dualVal_zero, dualVal_zero, pathFlow_first _ _ _ hlt, hmod, hsel]
    push_cast
    ring
  · have hge : L ≤ (e : ℕ) := by omega
    have hne : e ≠ e0 := fun h => by
      have hval : (e : ℕ) = i0 := by rw [h, he0]
      omega
    rw [dualVal_one, dualVal_one, pathFlow_second _ _ _ hge,
      show sel e0 e = 0 from if_neg hne]
    push_cast
    ring

/-- Every value of a path-constant flow with positive path values is positive. -/
theorem pathFlow_pos {L : ℕ} {a b : ℝ} (ha : 0 < a) (hb : 0 < b) (e : Fin (2 * L)) :
    0 < pathFlow L a b e := by
  rw [pathFlow_apply]
  split <;> assumption

/-- **CC35.**  With the roots `R_e = lambda t_e^3` the support root test holds with
equality on every edge. -/
theorem root_test_dual {L : ℕ} (hL : 0 < L) {lm : ℝ} (hlm : 0 < lm) {i0 : ℕ} (hi0 : i0 < L)
    {σ a b : ℝ} (hcons : σ = (L : ℝ) * lm * (a ^ 2 - b ^ 2)) {e0 : Fin (2 * L)}
    (he0 : (e0 : ℕ) = i0) {w : Fin (2 * L) → ℝ} (hw : ∀ e, w e = σ * sel e0 e)
    (e : Fin (2 * L)) :
    |w e - (net L).drops (dualPotential L lm i0 σ a b) e| ^ 3
      = (lm * pathFlow L a b e ^ 3) ^ 2 *
        (lm * (if 0 ≤ w e - (net L).drops (dualPotential L lm i0 σ a b) e
          then (net L).positive e else (net L).negative e)) := by
  have hval : w e - (net L).drops (dualPotential L lm i0 σ a b) e
      = lm * pathFlow L a b e ^ 2 := by
    rw [drops_dualPotential hL lm hi0 hcons he0 e, hw e]
    ring
  have hnn : 0 ≤ lm * pathFlow L a b e ^ 2 := mul_nonneg hlm.le (sq_nonneg _)
  rw [hval, if_pos hnn, positive_apply, abs_of_nonneg hnn]
  ring

/-! #### The value of the certified bound -/

private theorem sum_pair' {N : ℕ} (f : Fin N → ℝ) (x y : Fin N) (hxy : x ≠ y)
    (h : ∀ c, c ≠ x → c ≠ y → f c = 0) : ∑ c, f c = f x + f y := by
  classical
  rw [← Finset.sum_subset (Finset.subset_univ ({x, y} : Finset (Fin N)))
    (fun c _ hc => h c (fun hcx => hc (by simp [hcx])) (fun hcy => hc (by simp [hcy])))]
  exact Finset.sum_pair hxy

private theorem sum_split (L : ℕ) (a b : ℝ) :
    ∑ e : Fin (2 * L), (if (e : ℕ) < L then a else b) = L * a + L * b := by
  have hre : ∑ e : Fin (2 * L), (if (e : ℕ) < L then a else b)
      = ∑ k ∈ Finset.range (2 * L), (if k < L then a else b) :=
    Fin.sum_univ_eq_sum_range (fun k => if k < L then a else b) (2 * L)
  have hlo : ∀ k ∈ Finset.Ico 0 L, (if k < L then a else b) = a :=
    fun k hk => if_pos (Finset.mem_Ico.mp hk).2
  have hhi : ∀ k ∈ Finset.Ico L (2 * L), (if k < L then a else b) = b := by
    intro k hk
    exact if_neg (by have := (Finset.mem_Ico.mp hk).1; omega)
  rw [hre, Finset.range_eq_Ico,
    ← Finset.sum_Ico_consecutive _ (Nat.zero_le L) (by omega : L ≤ 2 * L),
    Finset.sum_congr rfl hlo, Finset.sum_congr rfl hhi, Finset.sum_const, Finset.sum_const,
    Nat.card_Ico, Nat.card_Ico, Nat.sub_zero, show 2 * L - L = L by omega,
    nsmul_eq_mul, nsmul_eq_mul]

/-- The nomination pairing sees only the source and the sink. -/
theorem sum_nom_mul {L : ℕ} (hL : 0 < L) (p : Fin (2 * L) → ℝ) :
    ∑ v, p v * nom L v
      = 2 * p ⟨0, by omega⟩ - 2 * p ⟨1, by omega⟩ := by
  have hne : (⟨0, by omega⟩ : Fin (2 * L)) ≠ ⟨1, by omega⟩ := by
    intro h
    exact absurd (congrArg Fin.val h) (by norm_num)
  have hz : ∀ c : Fin (2 * L), c ≠ ⟨0, by omega⟩ → c ≠ ⟨1, by omega⟩ →
      p c * nom L c = 0 := by
    intro c hc0 hc1
    have h0 : (c : ℕ) ≠ 0 := fun h => hc0 (Fin.ext h)
    have h1 : (c : ℕ) ≠ 1 := fun h => hc1 (Fin.ext h)
    simp [nom, h0, h1]
  have hn0 : nom L (⟨0, by omega⟩ : Fin (2 * L)) = 2 := by simp [nom]
  have hn1 : nom L (⟨1, by omega⟩ : Fin (2 * L)) = -2 := by simp [nom]
  rw [sum_pair' (fun v => p v * nom L v) ⟨0, by omega⟩ ⟨1, by omega⟩ hne hz, hn0, hn1]
  ring

/-- The closed form of the certified support bound attached to the dual data. -/
theorem supportBound_dual {L : ℕ} (hL : 0 < L) (eps lm : ℝ) (i0 : ℕ) (σ a b : ℝ) :
    (net L).supportBound (nom L) (trial L eps) lm (dualPotential L lm i0 σ a b)
        (fun e => lm * pathFlow L a b e ^ 3)
      = lm * (net L).energy (trial L eps) - 2 * ((L : ℝ) * lm * b ^ 2)
        + 2 / 3 * (lm * ((L : ℝ) * a ^ 3 + (L : ℝ) * b ^ 3)) := by
  have hR : ∑ e : Fin (2 * L), lm * pathFlow L a b e ^ 3
      = lm * ((L : ℝ) * a ^ 3 + (L : ℝ) * b ^ 3) := by
    rw [← Finset.mul_sum, ← sum_split L (a ^ 3) (b ^ 3)]
    congr 1
    refine Finset.sum_congr rfl fun e _ => ?_
    rw [pathFlow_apply]
    split <;> rfl
  have hp0 : dualPotential L lm i0 σ a b (⟨0, by omega⟩ : Fin (2 * L))
      = -((L : ℝ) * lm * b ^ 2) := by
    rw [dualPotential_apply, if_pos rfl, dualVal_one]
    push_cast
    ring
  have hp1 : dualPotential L lm i0 σ a b (⟨1, by omega⟩ : Fin (2 * L)) = 0 := by
    rw [dualPotential_apply, if_neg one_ne_zero, if_pos rfl]
  rw [Network.supportBound, sum_nom_mul hL, hR, hp0, hp1]
  ring

/-! #### The two rational certificates of the example -/

/-- The dual potential of the certificate attaining the upper support endpoint. -/
def upperPotential (L : ℕ) (eps : ℝ) (i0 : ℕ) : Fin (2 * L) → ℝ :=
  dualPotential L (lam L eps) i0 1 (1 + eps) (1 - eps)

/-- The exact root witnesses `R_e = lambda t_e^3` of the upper certificate. -/
def upperRoots (L : ℕ) (eps : ℝ) : Fin (2 * L) → ℝ :=
  fun e => lam L eps * pathFlow L (1 + eps) (1 - eps) e ^ 3

/-- Unfolding lemma for the upper root witnesses. -/
theorem upperRoots_eq (L : ℕ) (eps : ℝ) :
    upperRoots L eps = fun e => lam L eps * pathFlow L (1 + eps) (1 - eps) e ^ 3 := rfl

/-- The dual potential of the certificate attaining the lower support endpoint, obtained
from the upper one by exchanging the two path values and negating the goal. -/
def lowerPotential (L : ℕ) (eps : ℝ) (i0 : ℕ) : Fin (2 * L) → ℝ :=
  dualPotential L (lam L eps) i0 (-1) (1 - eps) (1 + eps)

/-- The exact root witnesses of the lower certificate. -/
def lowerRoots (L : ℕ) (eps : ℝ) : Fin (2 * L) → ℝ :=
  fun e => lam L eps * pathFlow L (1 - eps) (1 + eps) e ^ 3

/-- Unfolding lemma for the lower root witnesses. -/
theorem lowerRoots_eq (L : ℕ) (eps : ℝ) :
    lowerRoots L eps = fun e => lam L eps * pathFlow L (1 - eps) (1 + eps) e ^ 3 := rfl

/-- Accumulating rational prescribed drops gives rational node potentials. -/
theorem exists_rat_dualPotential (L i0 : ℕ) (lm σ a b : ℚ) :
    ∃ v : Fin (2 * L) → ℚ,
      (fun j => (v j : ℝ)) = dualPotential L lm i0 σ a b := by
  let qval (p i : ℕ) : ℚ :=
    if p = 0 then σ * (if i ≤ i0 then 1 else 0) - ((L : ℚ) - i) * lm * a ^ 2
    else -(((L : ℚ) - i) * lm * b ^ 2)
  have hval (p i : ℕ) : (qval p i : ℝ) = dualVal L lm i0 σ a b p i := by
    simp only [qval, dualVal]
    split_ifs <;> push_cast <;> rfl
  refine ⟨fun v => if (v : ℕ) = 0 then qval 1 0 else if (v : ℕ) = 1 then 0
    else qval (((v : ℕ) - 2) / (L - 1)) (((v : ℕ) - 2) % (L - 1) + 1), ?_⟩
  funext v
  simp only [dualPotential]
  split_ifs <;> first | exact hval _ _ | exact Rat.cast_zero

/-- **CC35.** For rational `eps`, the explicit multiplier, both node potentials and
both root vectors are casts of rational data. These equalities connect rational witnesses
directly to the root tests and attainment theorems for the real-valued formulas. -/
theorem exists_rational_dual_data (L : ℕ) (eps : ℚ) (i0 : ℕ) :
    ∃ (lm : ℚ) (vp vm rp rm : Fin (2 * L) → ℚ),
      (lm : ℝ) = lam L eps ∧
      (fun v => (vp v : ℝ)) = upperPotential L eps i0 ∧
      (fun v => (vm v : ℝ)) = lowerPotential L eps i0 ∧
      (fun e => (rp e : ℝ)) = upperRoots L eps ∧
      (fun e => (rm e : ℝ)) = lowerRoots L eps := by
  let lm : ℚ := 1 / (4 * L * eps)
  have hlm : (lm : ℝ) = lam L eps := by simp [lm, lam]
  obtain ⟨vp, hvp⟩ := exists_rat_dualPotential L i0 lm 1 (1 + eps) (1 - eps)
  obtain ⟨vm, hvm⟩ := exists_rat_dualPotential L i0 lm (-1) (1 - eps) (1 + eps)
  refine ⟨lm, vp, vm,
    (fun e => lm * (if (e : ℕ) < L then 1 + eps else 1 - eps) ^ 3),
    (fun e => lm * (if (e : ℕ) < L then 1 - eps else 1 + eps) ^ 3), hlm, ?_, ?_, ?_, ?_⟩
  · simpa [upperPotential, hlm] using hvp
  · simpa [lowerPotential, hlm] using hvm
  · funext e
    by_cases he : (e : ℕ) < L <;> simp [upperRoots, pathFlow, he, hlm]
  · funext e
    by_cases he : (e : ℕ) < L <;> simp [lowerRoots, pathFlow, he, hlm]

/-- **CC35.**  The upper certificate attains the exact upper support endpoint `1 + eps`. -/
theorem supportBound_upper_eq {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) (h1 : eps < 1)
    (i0 : ℕ) :
    (net L).supportBound (nom L) (trial L eps) (lam L eps) (upperPotential L eps i0)
      (upperRoots L eps) = 1 + eps := by
  have hLR : (0 : ℝ) < L := by exact_mod_cast hL
  have hL0 : (L : ℝ) ≠ 0 := ne_of_gt hLR
  have hE : (net L).energy (trial L eps) = 2 * L / 3 + 2 * L * eps ^ 2 := energy_trial L h0 h1
  rw [upperPotential, upperRoots_eq,
    supportBound_dual hL eps (lam L eps) i0 1 (1 + eps) (1 - eps), hE]
  unfold lam
  field_simp
  ring

/-- **CC35.**  The lower certificate attains `eps - 1`, whose negative is the exact lower
support endpoint `1 - eps`. -/
theorem supportBound_lower_eq {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) (h1 : eps < 1)
    (i0 : ℕ) :
    (net L).supportBound (nom L) (trial L eps) (lam L eps) (lowerPotential L eps i0)
      (lowerRoots L eps) = eps - 1 := by
  have hLR : (0 : ℝ) < L := by exact_mod_cast hL
  have hL0 : (L : ℝ) ≠ 0 := ne_of_gt hLR
  have hE : (net L).energy (trial L eps) = 2 * L / 3 + 2 * L * eps ^ 2 := energy_trial L h0 h1
  rw [lowerPotential, lowerRoots_eq,
    supportBound_dual hL eps (lam L eps) i0 (-1) (1 - eps) (1 + eps), hE]
  unfold lam
  field_simp
  ring

/-- **CC35.**  The upper certificate is sound: its value bounds the selector goal on the
whole support set, and by `isGreatest_supportGoal` that bound is exact. -/
theorem supportBound_upper_sound {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) (h1 : eps < 1)
    {e0 : Fin (2 * L)} (he0 : (e0 : ℕ) < L) :
    ∀ x ∈ (net L).supportSet (nom L) (trial L eps), ∑ e, sel e0 e * x e ≤ 1 + eps := by
  have hlam := lam_pos hL h0
  have hcons : (1 : ℝ) = (L : ℝ) * lam L eps * ((1 + eps) ^ 2 - (1 - eps) ^ 2) :=
    lam_consistency' hL h0
  have hR : ∀ e, 0 ≤ upperRoots L eps e := fun e =>
    mul_nonneg hlam.le (pow_nonneg (pathFlow_pos (by linarith) (by linarith) e).le 3)
  have hroot : ∀ e, |sel e0 e - (net L).drops (upperPotential L eps (e0 : ℕ)) e| ^ 3 ≤
      upperRoots L eps e ^ 2 *
        (lam L eps * (if 0 ≤ sel e0 e - (net L).drops (upperPotential L eps (e0 : ℕ)) e
          then (net L).positive e else (net L).negative e)) := fun e =>
    le_of_eq (root_test_dual hL hlam he0 hcons rfl (fun _ => (one_mul _).symm) e)
  have hbound := (net L).supportBound_sound (b := nom L) (y := trial L eps) (w := sel e0)
    (net_positive L) hlam hR hroot
  rwa [supportBound_upper_eq hL h0 h1 (e0 : ℕ)] at hbound

/-- **CC35.**  The mirrored certificate is sound: it bounds the selector goal from below by
the exact lower support endpoint `1 - eps`. -/
theorem supportBound_lower_sound {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) (h1 : eps < 1)
    {e0 : Fin (2 * L)} (he0 : (e0 : ℕ) < L) :
    ∀ x ∈ (net L).supportSet (nom L) (trial L eps), 1 - eps ≤ ∑ e, sel e0 e * x e := by
  have hlam := lam_pos hL h0
  have hcons : (-1 : ℝ) = (L : ℝ) * lam L eps * ((1 - eps) ^ 2 - (1 + eps) ^ 2) :=
    lam_consistency_neg hL h0
  have hR : ∀ e, 0 ≤ lowerRoots L eps e := fun e =>
    mul_nonneg hlam.le (pow_nonneg (pathFlow_pos (by linarith) (by linarith) e).le 3)
  have hroot : ∀ e, |(-sel e0 e) - (net L).drops (lowerPotential L eps (e0 : ℕ)) e| ^ 3 ≤
      lowerRoots L eps e ^ 2 *
        (lam L eps * (if 0 ≤ (-sel e0 e) - (net L).drops (lowerPotential L eps (e0 : ℕ)) e
          then (net L).positive e else (net L).negative e)) := fun e =>
    le_of_eq (root_test_dual hL hlam he0 hcons rfl (fun _ => (neg_one_mul _).symm) e)
  have hbound := (net L).supportBound_sound (b := nom L) (y := trial L eps)
    (w := fun e => -sel e0 e) (net_positive L) hlam hR hroot
  rw [supportBound_lower_eq hL h0 h1 (e0 : ℕ)] at hbound
  intro x hx
  have hx' := hbound x hx
  have hneg : ∑ e, (-sel e0 e) * x e = -∑ e, sel e0 e * x e := by
    rw [← Finset.sum_neg_distrib]
    exact Finset.sum_congr rfl fun e _ => by ring
  rw [hneg] at hx'
  linarith

/-! ### CC36: the separate-edge Bregman width -/

/-- The separate-edge Bregman divergence at unit coefficients, as a function of the
displacement `a` from the edge value `c`. -/
def bregShape (c a : ℝ) : ℝ := c * a ^ 2 + 2 * a ^ 3 / 3

/-- The shape function vanishes at zero displacement. -/
@[simp] theorem bregShape_zero (c : ℝ) : bregShape c 0 = 0 := by
  unfold bregShape; ring

/-- **CC36.**  Exact expansion `D_e(y_e, y_e + a) = y_e a^2 + 2 a^3 / 3` of the edge
divergence at unit coefficients, valid whenever both points are positive. -/
theorem edgeBregman_one_shift {c a : ℝ} (hc : 0 < c) (hca : 0 < c + a) :
    edgeBregman 1 1 c (c + a) = bregShape c a := by
  unfold edgeBregman edgeEnergy edgeLaw bregShape
  rw [abs_of_pos hc, abs_of_pos hca]
  simp only [ite_self]
  ring

/-- The shape function is continuous. -/
theorem continuous_bregShape (c : ℝ) : Continuous (bregShape c) := by
  unfold bregShape
  fun_prop

/-- On the nonnegative axis the shape function is strictly increasing. -/
theorem strictMonoOn_bregShape {c : ℝ} (hc : 0 < c) :
    StrictMonoOn (bregShape c) (Set.Ici 0) := by
  intro x hx y hy hxy
  have hx0 : (0 : ℝ) ≤ x := hx
  have hy0 : (0 : ℝ) ≤ y := hy
  unfold bregShape
  nlinarith [sq_nonneg (x + y), sq_nonneg (x - y), mul_pos (sub_pos.mpr hxy) hc]

/-- On `[-c, 0]` the shape function is strictly decreasing: its derivative `2a(c + a)` is
negative there. -/
theorem strictAntiOn_bregShape (c : ℝ) :
    StrictAntiOn (bregShape c) (Set.Icc (-c) 0) := by
  intro x hx y hy hxy
  obtain ⟨hx1, hx2⟩ := hx
  obtain ⟨hy1, hy2⟩ := hy
  unfold bregShape
  nlinarith [mul_nonneg (by linarith : (0 : ℝ) ≤ c + x) (by linarith : (0 : ℝ) ≤ -(x + y)),
    mul_pos (by linarith : (0 : ℝ) < y - x) (by linarith : (0 : ℝ) < -(x + 2 * y))]

/-- A positive displacement solving the shape equation exists. -/
theorem exists_bregShape_pos {c d : ℝ} (hc : 0 < c) (hd : 0 < d) :
    ∃ a : ℝ, 0 < a ∧ bregShape c a = d := by
  have hdc : (0 : ℝ) ≤ d / c := by positivity
  have hs0 : 0 < Real.sqrt (d / c) := Real.sqrt_pos.mpr (by positivity)
  have hsq : Real.sqrt (d / c) ^ 2 = d / c := Real.sq_sqrt hdc
  have hcs : c * Real.sqrt (d / c) ^ 2 = d := by
    rw [hsq]; field_simp
  have hfs : d ≤ bregShape c (Real.sqrt (d / c)) := by
    unfold bregShape
    nlinarith [pow_pos hs0 3]
  have hmem : d ∈ Set.Icc (bregShape c 0) (bregShape c (Real.sqrt (d / c))) := by
    rw [bregShape_zero]
    exact ⟨hd.le, hfs⟩
  obtain ⟨a, ha, hfa⟩ :=
    intermediate_value_Icc hs0.le (continuous_bregShape c).continuousOn hmem
  refine ⟨a, lt_of_le_of_ne ha.1 (fun h => ?_), hfa⟩
  rw [← h, bregShape_zero] at hfa
  linarith

/-- A negative displacement solving the shape equation exists as soon as the right-hand
side stays below the value `c^3/3` at the left endpoint `-c`. -/
theorem exists_bregShape_neg {c d : ℝ} (hc : 0 < c) (hd : 0 < d) (hdc : d < c ^ 3 / 3) :
    ∃ a : ℝ, -c < a ∧ a < 0 ∧ bregShape c a = d := by
  have hfc : bregShape c (-c) = c ^ 3 / 3 := by unfold bregShape; ring
  have hmem : d ∈ Set.Icc (bregShape c 0) (bregShape c (-c)) := by
    rw [bregShape_zero, hfc]
    exact ⟨hd.le, hdc.le⟩
  obtain ⟨a, ha, hfa⟩ := intermediate_value_Icc' (by linarith : -c ≤ (0 : ℝ))
    (continuous_bregShape c).continuousOn hmem
  refine ⟨a, lt_of_le_of_ne ha.1 (fun h => ?_), lt_of_le_of_ne ha.2 (fun h => ?_), hfa⟩
  · rw [← h, hfc] at hfa
    linarith
  · rw [h, bregShape_zero] at hfa
    linarith

/-- **CC36.**  The shape equation has exactly one positive solution. -/
theorem existsUnique_bregShape_pos {c d : ℝ} (hc : 0 < c) (hd : 0 < d) :
    ∃! a : ℝ, 0 < a ∧ bregShape c a = d := by
  obtain ⟨a, ha, heq⟩ := exists_bregShape_pos hc hd
  refine ⟨a, ⟨ha, heq⟩, fun x hx => ?_⟩
  exact (strictMonoOn_bregShape hc).injOn (Set.mem_Ici.mpr hx.1.le) (Set.mem_Ici.mpr ha.le)
    (by rw [hx.2, heq])

/-- **CC36.**  The shape equation has exactly one solution in `(-c, 0)`, under the explicit
sufficient condition `d < c^3/3`. -/
theorem existsUnique_bregShape_neg {c d : ℝ} (hc : 0 < c) (hd : 0 < d) (hdc : d < c ^ 3 / 3) :
    ∃! a : ℝ, -c < a ∧ a < 0 ∧ bregShape c a = d := by
  obtain ⟨a, hac, ha, heq⟩ := exists_bregShape_neg hc hd hdc
  refine ⟨a, ⟨hac, ha, heq⟩, fun x hx => ?_⟩
  exact (strictAntiOn_bregShape c).injOn (Set.mem_Icc.mpr ⟨hx.1.le, hx.2.1.le⟩)
    (Set.mem_Icc.mpr ⟨hac.le, ha.le⟩) (by rw [hx.2.2, heq])

/-- The positive boundary displacement of the separate-edge Bregman interval. -/
def bregPos (c d : ℝ) : ℝ := sSup {a : ℝ | 0 < a ∧ bregShape c a = d}

/-- The negative boundary displacement of the separate-edge Bregman interval. -/
def bregNeg (c d : ℝ) : ℝ := sSup {a : ℝ | -c < a ∧ a < 0 ∧ bregShape c a = d}

/-- Any positive solution of the shape equation is the one named by `bregPos`. -/
theorem bregPos_eq {c d a : ℝ} (hc : 0 < c) (ha : 0 < a) (heq : bregShape c a = d) :
    bregPos c d = a := by
  have hset : {x : ℝ | 0 < x ∧ bregShape c x = d} = {a} :=
    Set.eq_singleton_iff_unique_mem.mpr ⟨⟨ha, heq⟩, fun x hx =>
      (strictMonoOn_bregShape hc).injOn (Set.mem_Ici.mpr hx.1.le) (Set.mem_Ici.mpr ha.le)
        (by rw [hx.2, heq])⟩
  rw [bregPos, hset, csSup_singleton]

/-- Any solution of the shape equation in `(-c, 0)` is the one named by `bregNeg`. -/
theorem bregNeg_eq {c d a : ℝ} (hac : -c < a) (ha : a < 0)
    (heq : bregShape c a = d) : bregNeg c d = a := by
  have hset : {x : ℝ | -c < x ∧ x < 0 ∧ bregShape c x = d} = {a} :=
    Set.eq_singleton_iff_unique_mem.mpr ⟨⟨hac, ha, heq⟩, fun x hx =>
      (strictAntiOn_bregShape c).injOn (Set.mem_Icc.mpr ⟨hx.1.le, hx.2.1.le⟩)
        (Set.mem_Icc.mpr ⟨hac.le, ha.le⟩) (by rw [hx.2.2, heq])⟩
  rw [bregNeg, hset, csSup_singleton]

/-- `bregPos c d` is the positive solution of the shape equation. -/
theorem bregPos_spec {c d : ℝ} (hc : 0 < c) (hd : 0 < d) :
    0 < bregPos c d ∧ bregShape c (bregPos c d) = d := by
  obtain ⟨a, ha, heq⟩ := exists_bregShape_pos hc hd
  rw [bregPos_eq hc ha heq]
  exact ⟨ha, heq⟩

/-- `bregNeg c d` is the solution of the shape equation in `(-c, 0)`. -/
theorem bregNeg_spec {c d : ℝ} (hc : 0 < c) (hd : 0 < d) (hdc : d < c ^ 3 / 3) :
    -c < bregNeg c d ∧ bregNeg c d < 0 ∧ bregShape c (bregNeg c d) = d := by
  obtain ⟨a, hac, ha, heq⟩ := exists_bregShape_neg hc hd hdc
  rw [bregNeg_eq hac ha heq]
  exact ⟨hac, ha, heq⟩

/-! #### Two-sided bounds on the boundary displacements -/

/-- Dropping the cubic term bounds the positive displacement from above. -/
theorem bregPos_le_sqrt {c d a : ℝ} (hc : 0 < c) (ha : 0 < a) (h : bregShape c a = d) :
    a ≤ Real.sqrt (d / c) := by
  unfold bregShape at h
  have hsq : a ^ 2 ≤ d / c := by
    rw [le_div_iff₀ hc]
    nlinarith [pow_pos ha 3]
  calc a = Real.sqrt (a ^ 2) := (Real.sqrt_sq ha.le).symm
    _ ≤ Real.sqrt (d / c) := Real.sqrt_le_sqrt hsq

/-- Substituting the upper bound back into `a^2 (c + 2a/3) = d` bounds the positive
displacement from below. -/
theorem sqrt_le_bregPos {c d a : ℝ} (hc : 0 < c) (ha : 0 < a) (h : bregShape c a = d) :
    Real.sqrt (d / (c + 2 / 3 * Real.sqrt (d / c))) ≤ a := by
  have hup := bregPos_le_sqrt hc ha h
  have hs0 : 0 ≤ Real.sqrt (d / c) := Real.sqrt_nonneg _
  have hM : 0 < c + 2 / 3 * Real.sqrt (d / c) := by linarith
  unfold bregShape at h
  have hsq : d / (c + 2 / 3 * Real.sqrt (d / c)) ≤ a ^ 2 := by
    rw [div_le_iff₀ hM]
    nlinarith [mul_le_mul_of_nonneg_left hup (sq_nonneg a)]
  calc Real.sqrt (d / (c + 2 / 3 * Real.sqrt (d / c))) ≤ Real.sqrt (a ^ 2) :=
        Real.sqrt_le_sqrt hsq
    _ = a := Real.sqrt_sq ha.le

/-- Dropping the cubic term bounds the negative displacement in absolute value from
below. -/
theorem sqrt_le_neg_bregNeg {c d a : ℝ} (hc : 0 < c) (ha : a < 0)
    (h : bregShape c a = d) : Real.sqrt (d / c) ≤ -a := by
  unfold bregShape at h
  have hsq : d / c ≤ (-a) ^ 2 := by
    rw [div_le_iff₀ hc]
    nlinarith [pow_pos (neg_pos.mpr ha) 3]
  calc Real.sqrt (d / c) ≤ Real.sqrt ((-a) ^ 2) := Real.sqrt_le_sqrt hsq
    _ = -a := Real.sqrt_sq (by linarith)

/-- The crude upper bound `|a| < sqrt (3 d / c)` on the negative displacement. -/
theorem neg_bregNeg_le_sqrt {c d a : ℝ} (hc : 0 < c) (hac : -c < a) (ha : a < 0)
    (h : bregShape c a = d) : -a ≤ Real.sqrt (3 * d / c) := by
  unfold bregShape at h
  have hsq : (-a) ^ 2 ≤ 3 * d / c := by
    rw [le_div_iff₀ hc]
    nlinarith [mul_nonneg (sq_nonneg a) (by linarith : (0 : ℝ) ≤ c + a)]
  calc -a = Real.sqrt ((-a) ^ 2) := (Real.sqrt_sq (by linarith)).symm
    _ ≤ Real.sqrt (3 * d / c) := Real.sqrt_le_sqrt hsq

/-- Substituting the crude bound back into `|a|^2 (c - 2|a|/3) = d` sharpens it. -/
theorem neg_bregNeg_le_sqrt' {c d a : ℝ} (hc : 0 < c) (hac : -c < a) (ha : a < 0)
    (h : bregShape c a = d) (hM : 0 < c - 2 / 3 * Real.sqrt (3 * d / c)) :
    -a ≤ Real.sqrt (d / (c - 2 / 3 * Real.sqrt (3 * d / c))) := by
  have hup := neg_bregNeg_le_sqrt hc hac ha h
  unfold bregShape at h
  have hsq : (-a) ^ 2 ≤ d / (c - 2 / 3 * Real.sqrt (3 * d / c)) := by
    rw [le_div_iff₀ hM]
    nlinarith [mul_le_mul_of_nonneg_left hup (sq_nonneg a)]
  calc -a = Real.sqrt ((-a) ^ 2) := (Real.sqrt_sq (by linarith)).symm
    _ ≤ _ := Real.sqrt_le_sqrt hsq

/-! #### The asymptotic separate-edge Bregman width -/

/-- The positive boundary displacement of a first-path edge of the example. -/
def aPos (L : ℕ) (eps : ℝ) : ℝ := bregPos (1 + eps) (2 * L * eps ^ 2)

/-- The negative boundary displacement of a first-path edge of the example. -/
def aNeg (L : ℕ) (eps : ℝ) : ℝ := bregNeg (1 + eps) (2 * L * eps ^ 2)

/-- Explicit smallness threshold: for `0 < eps < 1 / (12 L)` the exact gap
`delta = 2 L eps^2` stays below the value `c^3/3` of the shape function at `-c`, for every
edge value `c` at least `1 - eps`.  This is the sufficient condition under which the
negative Bregman boundary displacement exists and is unique. -/
theorem gap_lt_cube {L : ℕ} (hL : 0 < L) {eps c : ℝ} (h0 : 0 < eps)
    (hb : eps < 1 / (12 * L)) (hc : 1 - eps ≤ c) : 2 * L * eps ^ 2 < c ^ 3 / 3 := by
  have hLR : (1 : ℝ) ≤ L := by exact_mod_cast hL
  have hLpos : (0 : ℝ) < 12 * L := by linarith
  have h12 : eps * (12 * L) < 1 := (lt_div_iff₀ hLpos).mp hb
  have heps : eps < 1 / 12 := by nlinarith
  have hcl : (11 : ℝ) / 12 ≤ c := by linarith
  have hc3 : ((11 : ℝ) / 12) ^ 3 ≤ c ^ 3 := by gcongr
  have hnum : ((11 : ℝ) / 12) ^ 3 = 1331 / 1728 := by norm_num
  have hgap : 2 * (L : ℝ) * eps ^ 2 < eps / 6 := by nlinarith
  linarith

/-- The positive boundary displacement of the example is positive. -/
theorem aPos_pos {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) : 0 < aPos L eps := by
  have hLR : (0 : ℝ) < L := by exact_mod_cast hL
  have hc : (0 : ℝ) < 1 + eps := by linarith
  have hd : (0 : ℝ) < 2 * L * eps ^ 2 := by positivity
  exact (bregPos_spec hc hd).1

/-- Below the threshold the negative boundary displacement of the example lies strictly
between `-(1 + eps)` and `0`. -/
theorem aNeg_bounds {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps)
    (hb : eps < 1 / (12 * L)) : -(1 + eps) < aNeg L eps ∧ aNeg L eps < 0 := by
  have hLR : (0 : ℝ) < L := by exact_mod_cast hL
  have hc : (0 : ℝ) < 1 + eps := by linarith
  have hd : (0 : ℝ) < 2 * L * eps ^ 2 := by positivity
  obtain ⟨h1, h2, -⟩ := bregNeg_spec hc hd (gap_lt_cube hL h0 hb (by linarith))
  exact ⟨h1, h2⟩

/-- **CC36.**  The positive boundary displacement solves the genuine separate-edge
divergence equation `D_e(y_e, y_e + a) = delta` on a first-path edge, not merely its cubic
expansion `bregShape`. -/
theorem edgeBregman_aPos {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) :
    edgeBregman 1 1 (1 + eps) ((1 + eps) + aPos L eps) = 2 * L * eps ^ 2 := by
  have hLR : (0 : ℝ) < L := by exact_mod_cast hL
  have hc : (0 : ℝ) < 1 + eps := by linarith
  have hd : (0 : ℝ) < 2 * L * eps ^ 2 := by positivity
  rw [edgeBregman_one_shift hc (by linarith [aPos_pos hL h0])]
  exact (bregPos_spec hc hd).2

/-- **CC36.**  The negative boundary displacement solves the genuine separate-edge
divergence equation on a first-path edge. -/
theorem edgeBregman_aNeg {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps)
    (hb : eps < 1 / (12 * L)) :
    edgeBregman 1 1 (1 + eps) ((1 + eps) + aNeg L eps) = 2 * L * eps ^ 2 := by
  have hLR : (0 : ℝ) < L := by exact_mod_cast hL
  have hc : (0 : ℝ) < 1 + eps := by linarith
  have hd : (0 : ℝ) < 2 * L * eps ^ 2 := by positivity
  rw [edgeBregman_one_shift hc (by linarith [(aNeg_bounds hL h0 hb).1])]
  exact (bregNeg_spec hc hd (gap_lt_cube hL h0 hb (by linarith))).2.2

/-- **CC36.**  The upper Bregman boundary point of a first-path edge is the unique point at
or above the edge value whose divergence from it is the exact gap.  Unlike
`existsUnique_bregShape_pos` this is a statement about the divergence itself, and it needs
no window restriction. -/
theorem existsUnique_edgeBregman_ge {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) :
    ∃! z : ℝ, 1 + eps ≤ z ∧ edgeBregman 1 1 (1 + eps) z = 2 * L * eps ^ 2 := by
  have hp := aPos_pos hL h0
  refine ⟨(1 + eps) + aPos L eps, ⟨by linarith, edgeBregman_aPos hL h0⟩, ?_⟩
  rintro z ⟨hz, hzeq⟩
  exact edgeBregman_injOn_Ici one_pos one_pos (1 + eps) (Set.mem_Ici.mpr hz)
    (Set.mem_Ici.mpr (by linarith)) (by rw [hzeq, edgeBregman_aPos hL h0])

/-- **CC36.**  The lower Bregman boundary point of a first-path edge is the unique point at
or below the edge value whose divergence from it is the exact gap.  Uniqueness is global:
the window `(-c, 0)` of `existsUnique_bregShape_neg` is needed only to produce the point,
because `bregShape` — unlike the divergence — has a second root below `-c`. -/
theorem existsUnique_edgeBregman_le {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps)
    (hb : eps < 1 / (12 * L)) :
    ∃! z : ℝ, z ≤ 1 + eps ∧ edgeBregman 1 1 (1 + eps) z = 2 * L * eps ^ 2 := by
  obtain ⟨hn1, hn2⟩ := aNeg_bounds hL h0 hb
  refine ⟨(1 + eps) + aNeg L eps, ⟨by linarith, edgeBregman_aNeg hL h0 hb⟩, ?_⟩
  rintro z ⟨hz, hzeq⟩
  exact edgeBregman_injOn_Iic one_pos one_pos (1 + eps) (Set.mem_Iic.mpr hz)
    (Set.mem_Iic.mpr (by linarith)) (by rw [hzeq, edgeBregman_aNeg hL h0 hb])

private theorem sqrt_gap_div (L : ℕ) {eps : ℝ} (h0 : 0 < eps) (X : ℝ) :
    Real.sqrt (2 * L * eps ^ 2 / X) = eps * Real.sqrt (2 * L / X) := by
  rw [show 2 * (L : ℝ) * eps ^ 2 / X = eps ^ 2 * (2 * L / X) by ring,
    Real.sqrt_mul (sq_nonneg eps), Real.sqrt_sq h0.le]

private theorem sqrt_gap_div3 (L : ℕ) {eps : ℝ} (h0 : 0 < eps) (X : ℝ) :
    Real.sqrt (3 * (2 * L * eps ^ 2) / X) = eps * Real.sqrt (6 * L / X) := by
  rw [show 3 * (2 * (L : ℝ) * eps ^ 2) / X = eps ^ 2 * (6 * L / X) by ring,
    Real.sqrt_mul (sq_nonneg eps), Real.sqrt_sq h0.le]

/-- The lower comparison function of the squeeze for the separate-edge Bregman width. -/
def widthLower (L : ℕ) (t : ℝ) : ℝ :=
  Real.sqrt (2 * L / (1 + t + 2 / 3 * (t * Real.sqrt (2 * L / (1 + t)))))
    + Real.sqrt (2 * L / (1 + t))

/-- The upper comparison function of the squeeze for the separate-edge Bregman width. -/
def widthUpper (L : ℕ) (t : ℝ) : ℝ :=
  Real.sqrt (2 * L / (1 + t))
    + Real.sqrt (2 * L / (1 + t - 2 / 3 * (t * Real.sqrt (6 * L / (1 + t)))))

/-- The lower comparison function takes the limit value at zero. -/
theorem widthLower_zero (L : ℕ) : widthLower L 0 = 2 * Real.sqrt (2 * L) := by
  simp [widthLower]
  ring

/-- The upper comparison function takes the limit value at zero. -/
theorem widthUpper_zero (L : ℕ) : widthUpper L 0 = 2 * Real.sqrt (2 * L) := by
  simp [widthUpper]
  ring

private theorem continuousAt_sqrtQuot (k : ℝ) (g : ℝ → ℝ) (hg : ContinuousAt g 0)
    (h : g 0 ≠ 0) : ContinuousAt (fun t : ℝ => Real.sqrt (k / g t)) 0 :=
  (ContinuousAt.div continuousAt_const hg h).sqrt

/-- The lower comparison function converges to `2 sqrt (2 L)`. -/
theorem tendsto_widthLower (L : ℕ) :
    Tendsto (widthLower L) (𝓝[>] (0 : ℝ)) (𝓝 (2 * Real.sqrt (2 * L))) := by
  have hden : ContinuousAt (fun t : ℝ => 1 + t) 0 := by fun_prop
  have hP : ContinuousAt (fun t : ℝ => Real.sqrt (2 * L / (1 + t))) 0 :=
    continuousAt_sqrtQuot _ _ hden (by norm_num)
  have hcont : ContinuousAt (widthLower L) 0 := by
    refine ContinuousAt.add (continuousAt_sqrtQuot _ _ ?_ (by norm_num)) hP
    exact hden.add (continuousAt_const.mul (continuousAt_id.mul hP))
  have h := hcont.tendsto
  rw [widthLower_zero] at h
  exact h.mono_left nhdsWithin_le_nhds

/-- The upper comparison function converges to `2 sqrt (2 L)`. -/
theorem tendsto_widthUpper (L : ℕ) :
    Tendsto (widthUpper L) (𝓝[>] (0 : ℝ)) (𝓝 (2 * Real.sqrt (2 * L))) := by
  have hden : ContinuousAt (fun t : ℝ => 1 + t) 0 := by fun_prop
  have hP : ContinuousAt (fun t : ℝ => Real.sqrt (2 * L / (1 + t))) 0 :=
    continuousAt_sqrtQuot _ _ hden (by norm_num)
  have hQ : ContinuousAt (fun t : ℝ => Real.sqrt (6 * L / (1 + t))) 0 :=
    continuousAt_sqrtQuot _ _ hden (by norm_num)
  have hcont : ContinuousAt (widthUpper L) 0 := by
    refine ContinuousAt.add hP (continuousAt_sqrtQuot _ _ ?_ (by norm_num))
    exact hden.sub (continuousAt_const.mul (continuousAt_id.mul hQ))
  have h := hcont.tendsto
  rw [widthUpper_zero] at h
  exact h.mono_left nhdsWithin_le_nhds

/-- **CC36.**  The separate-edge Bregman width of a first-path edge, divided by `eps`,
tends to `2 sqrt (2 L)` as `eps` decreases to zero. -/
theorem tendsto_bregmanWidth (L : ℕ) (hL : 0 < L) :
    Tendsto (fun eps => (aPos L eps - aNeg L eps) / eps) (𝓝[>] (0 : ℝ))
      (𝓝 (2 * Real.sqrt (2 * L))) := by
  have hLR : (1 : ℝ) ≤ L := by exact_mod_cast hL
  have hmem : Set.Ioo (0 : ℝ) (1 / (12 * L)) ∈ 𝓝[>] (0 : ℝ) :=
    Ioo_mem_nhdsGT (by positivity)
  have hev : ∀ᶠ eps in 𝓝[>] (0 : ℝ),
      widthLower L eps ≤ (aPos L eps - aNeg L eps) / eps ∧
        (aPos L eps - aNeg L eps) / eps ≤ widthUpper L eps := by
    filter_upwards [hmem] with eps heps
    obtain ⟨h0, hb⟩ := heps
    have h12 : eps * (12 * L) < 1 := (lt_div_iff₀ (by linarith)).mp hb
    have hc : (0 : ℝ) < 1 + eps := by linarith
    have hd : (0 : ℝ) < 2 * L * eps ^ 2 := by positivity
    have hdc : 2 * (L : ℝ) * eps ^ 2 < (1 + eps) ^ 3 / 3 :=
      gap_lt_cube hL h0 hb (by linarith)
    obtain ⟨hap, haq⟩ := bregPos_spec hc hd
    obtain ⟨han1, han2, han3⟩ := bregNeg_spec hc hd hdc
    have hS1 : Real.sqrt (2 * L * eps ^ 2 / (1 + eps))
        = eps * Real.sqrt (2 * L / (1 + eps)) := sqrt_gap_div L h0 _
    have hS3 : Real.sqrt (3 * (2 * L * eps ^ 2) / (1 + eps))
        = eps * Real.sqrt (6 * L / (1 + eps)) := sqrt_gap_div3 L h0 _
    have hqhalf : Real.sqrt (3 * (2 * (L : ℝ) * eps ^ 2) / (1 + eps)) ≤ 1 / 2 := by
      have hle : Real.sqrt (3 * (2 * (L : ℝ) * eps ^ 2) / (1 + eps))
          ≤ Real.sqrt ((1 / 2 : ℝ) ^ 2) := by
        refine Real.sqrt_le_sqrt ?_
        rw [div_le_iff₀ hc]
        nlinarith
      rwa [Real.sqrt_sq (by norm_num : (0 : ℝ) ≤ 1 / 2)] at hle
    have hM : 0 < (1 + eps) - 2 / 3 * Real.sqrt (3 * (2 * L * eps ^ 2) / (1 + eps)) := by
      linarith
    have hlo1 := sqrt_le_bregPos hc hap haq
    have hhi1 := bregPos_le_sqrt hc hap haq
    have hlo2 := sqrt_le_neg_bregNeg hc han2 han3
    have hhi2 := neg_bregNeg_le_sqrt' hc han1 han2 han3 hM
    rw [hS1, sqrt_gap_div L h0] at hlo1
    rw [hS1] at hhi1 hlo2
    rw [hS3, sqrt_gap_div L h0] at hhi2
    simp only [aPos, aNeg]
    constructor
    · rw [le_div_iff₀ h0, widthLower]
      linarith
    · rw [div_le_iff₀ h0, widthUpper]
      linarith
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le' (tendsto_widthLower L)
    (tendsto_widthUpper L) (hev.mono fun _ h => h.1) (hev.mono fun _ h => h.2)

/-! ### CC37: the optimal Laplacian factor -/

/-- **CC37.**  For a single-edge selector on a first-path edge and strictly positive edge
curvatures, the optimal Laplacian factor is exactly `1 / ∑ e, h e`, attained at an
explicit potential carrying the circulation `(1 / ∑ h) • gen L`. -/
theorem optimalFactor_sel {L : ℕ} (hL : 0 < L) {e0 : Fin (2 * L)} (he0 : (e0 : ℕ) < L)
    (h : Fin (2 * L) → ℝ) (hh : ∀ e, 0 < h e) :
    ∃ v : Fin (2 * L) → ℝ, (net L).ZeroAdmissible (sel e0) h v ∧
      (net L).OptimalFactor (sel e0) h v ∧ (net L).factor (sel e0) h v = 1 / ∑ e, h e := by
  have hS : 0 < ∑ e, h e := Finset.sum_pos (fun e _ => hh e) ⟨e0, Finset.mem_univ e0⟩
  have hSne : (∑ e, h e) ≠ 0 := ne_of_gt hS
  have hhnn : ∀ e, 0 ≤ h e := fun e => (hh e).le
  have hgen2 : ∀ e : Fin (2 * L), gen L e * gen L e = 1 := fun e => by
    rw [gen_apply]; split <;> norm_num
  have hgensel : ∑ e, sel e0 e * gen L e = 1 := by
    rw [sum_sel_mul, gen_apply, if_pos he0]
  set C : ℝ := 1 / ∑ e, h e with hC
  set dd : Fin (2 * L) → ℝ := fun e => C * gen L e with hdd
  have hload : (net L).loads dd = 0 := by
    refine (circulation_iff hL dd).mpr ⟨C, ?_⟩
    funext e
    simp only [hdd, pathFlow_apply, gen_apply]
    split <;> ring
  have hstat : ∀ z : Fin (2 * L) → ℝ, (net L).loads z = 0 →
      ∑ e, (sel e0 e - h e * dd e) * z e = 0 := by
    intro z hz
    obtain ⟨t, rfl⟩ := (circulation_iff hL z).mp hz
    have hz' : ∀ e : Fin (2 * L), pathFlow L t (-t) e = t * gen L e := fun e => by
      rw [pathFlow_apply, gen_apply]; split <;> ring
    have hterm : ∀ e : Fin (2 * L), (sel e0 e - h e * dd e) * pathFlow L t (-t) e
        = t * (sel e0 e * gen L e - C * h e) := fun e => by
      simp only [hz' e, hdd]
      linear_combination (-(t * C * h e)) * hgen2 e
    rw [Finset.sum_congr rfl (fun e _ => hterm e), ← Finset.mul_sum, Finset.sum_sub_distrib,
      ← Finset.mul_sum, hgensel, hC]
    field_simp
    ring
  obtain ⟨v, hv⟩ :=
    (net L).exists_potential_of_stationary (fun e => sel e0 e - h e * dd e) hstat
  have hzadm : (net L).ZeroAdmissible (sel e0) h v := fun e he => absurd he (hh e).ne'
  have hkkt : (net L).KktCirculation (sel e0) h v dd := by
    refine ⟨hload, fun e _ => ?_⟩
    have hgr : (net L).goalResidual (sel e0) v e = sel e0 e - (net L).drops v e := rfl
    rw [hgr]
    simp only [hv]
    ring
  refine ⟨v, hzadm, (net L).optimalFactor_of_kktCirculation hhnn hzadm hkkt, ?_⟩
  rw [((net L).kktCirculation_energy hzadm hkkt).2.symm]
  have hterm : ∀ e : Fin (2 * L), h e * dd e ^ 2 = C ^ 2 * h e := fun e => by
    simp only [hdd]
    linear_combination (h e * C ^ 2) * hgen2 e
  rw [Finset.sum_congr rfl (fun e _ => hterm e), ← Finset.mul_sum, hC]
  field_simp

/-- **CC37.**  Consequently every factor-minimizing potential for the selector has factor
exactly `1 / ∑ e, h e`, so the optimal factor of the example is that number. -/
theorem factor_eq_of_optimalFactor {L : ℕ} (hL : 0 < L) {e0 : Fin (2 * L)}
    (he0 : (e0 : ℕ) < L) (h : Fin (2 * L) → ℝ) (hh : ∀ e, 0 < h e) {v : Fin (2 * L) → ℝ}
    (hadm : (net L).ZeroAdmissible (sel e0) h v)
    (hopt : (net L).OptimalFactor (sel e0) h v) :
    (net L).factor (sel e0) h v = 1 / ∑ e, h e := by
  obtain ⟨v', hadm', hopt', hval⟩ := optimalFactor_sel hL he0 h hh
  have h1 := hopt v' hadm'
  have h2 := hopt' v hadm
  rw [hval] at h1 h2
  linarith

/-! #### The optimized Laplacian width of the example -/

/-- The lower separate-edge Bregman interval endpoint of edge `e` in the example. -/
def loEnd (L : ℕ) (eps : ℝ) (e : Fin (2 * L)) : ℝ :=
  trial L eps e + bregNeg (trial L eps e) (2 * L * eps ^ 2)

/-- The upper separate-edge Bregman interval endpoint of edge `e` in the example. -/
def hiEnd (L : ℕ) (eps : ℝ) (e : Fin (2 * L)) : ℝ :=
  trial L eps e + bregPos (trial L eps e) (2 * L * eps ^ 2)

/-- The curvature floor of the Bregman interval of edge `e` in the example. -/
def hEdge (L : ℕ) (eps : ℝ) (e : Fin (2 * L)) : ℝ :=
  curvatureFloor 1 1 (loEnd L eps e) (hiEnd L eps e)

/-- Every edge value of the trial flow is at least `1 - eps`. -/
theorem trial_ge_sub {L : ℕ} {eps : ℝ} (h0 : 0 ≤ eps) (e : Fin (2 * L)) :
    1 - eps ≤ trial L eps e := by
  rw [trial_apply]
  split <;> linarith

/-- Below the threshold `1 / (12 L)` the negative Bregman boundary displacement exists on
every edge of the example. -/
theorem bregNeg_trial_spec {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps)
    (hb : eps < 1 / (12 * L)) (e : Fin (2 * L)) :
    -trial L eps e < bregNeg (trial L eps e) (2 * L * eps ^ 2) ∧
      bregNeg (trial L eps e) (2 * L * eps ^ 2) < 0 ∧
      bregShape (trial L eps e) (bregNeg (trial L eps e) (2 * L * eps ^ 2))
        = 2 * L * eps ^ 2 := by
  have hLR : (1 : ℝ) ≤ L := by exact_mod_cast hL
  have h12 : eps * (12 * L) < 1 := (lt_div_iff₀ (by linarith)).mp hb
  have heps : eps < 1 / 12 := by nlinarith
  have hc : 0 < trial L eps e := lt_of_lt_of_le (by linarith) (trial_ge_sub h0.le e)
  have hd : (0 : ℝ) < 2 * L * eps ^ 2 := by positivity
  exact bregNeg_spec hc hd (gap_lt_cube hL h0 hb (trial_ge_sub h0.le e))

/-- All interval endpoints of the example are positive, so the curvature floor is
`2 l_e`. -/
theorem hEdge_eq_two_mul {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps)
    (hb : eps < 1 / (12 * L)) (e : Fin (2 * L)) : hEdge L eps e = 2 * loEnd L eps e := by
  obtain ⟨h1, _, _⟩ := bregNeg_trial_spec hL h0 hb e
  have hpos : 0 < loEnd L eps e := by rw [loEnd]; linarith
  rw [hEdge, curvatureFloor, if_pos hpos]
  ring

/-- **CC37.**  Below the threshold every curvature floor of the example is strictly
positive, so the zero-curvature edge set is empty. -/
theorem hEdge_pos {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps) (hb : eps < 1 / (12 * L))
    (e : Fin (2 * L)) : 0 < hEdge L eps e := by
  obtain ⟨h1, -, -⟩ := bregNeg_trial_spec hL h0 hb e
  rw [hEdge_eq_two_mul hL h0 hb e, loEnd]
  linarith

/-- **CC37.**  The factor appearing in `tendsto_laplacianWidth` is the optimal Laplacian
factor of the example: for the first-path selector some zero-admissible potential minimizes
the factor, and its factor is exactly `1 / ∑ e, hEdge L eps e`. -/
theorem optimalFactor_hEdge {L : ℕ} (hL : 0 < L) {eps : ℝ} (h0 : 0 < eps)
    (hb : eps < 1 / (12 * L)) {e0 : Fin (2 * L)} (he0 : (e0 : ℕ) < L) :
    ∃ v : Fin (2 * L) → ℝ, (net L).ZeroAdmissible (sel e0) (hEdge L eps) v ∧
      (net L).OptimalFactor (sel e0) (hEdge L eps) v ∧
      (net L).factor (sel e0) (hEdge L eps) v = 1 / ∑ e, hEdge L eps e :=
  optimalFactor_sel hL he0 (hEdge L eps) fun e => hEdge_pos hL h0 hb e

/-- Every edge value of the trial flow tends to one. -/
theorem tendsto_trial (L : ℕ) (e : Fin (2 * L)) :
    Tendsto (fun eps => trial L eps e) (𝓝[>] (0 : ℝ)) (𝓝 1) := by
  have hcont : Continuous fun eps : ℝ => trial L eps e := by
    by_cases hlt : (e : ℕ) < L
    · simp only [trial_apply, if_pos hlt]; fun_prop
    · simp only [trial_apply, if_neg hlt]; fun_prop
  have hval : trial L 0 e = 1 := by rw [trial_apply]; split <;> norm_num
  have h := hcont.tendsto 0
  rw [hval] at h
  exact h.mono_left nhdsWithin_le_nhds

/-- The negative Bregman displacement of every edge tends to zero. -/
theorem tendsto_bregNeg_trial (L : ℕ) (hL : 0 < L) (e : Fin (2 * L)) :
    Tendsto (fun eps => bregNeg (trial L eps e) (2 * L * eps ^ 2)) (𝓝[>] (0 : ℝ)) (𝓝 0) := by
  have hLR : (1 : ℝ) ≤ L := by exact_mod_cast hL
  have hlow : Tendsto (fun eps : ℝ => -(eps * Real.sqrt (72 * L / 11)))
      (𝓝[>] (0 : ℝ)) (𝓝 0) := by
    have hcont : Continuous fun eps : ℝ => -(eps * Real.sqrt (72 * L / 11)) := by fun_prop
    have h := hcont.tendsto 0
    simp only [zero_mul, neg_zero] at h
    exact h.mono_left nhdsWithin_le_nhds
  have hev : ∀ᶠ eps in 𝓝[>] (0 : ℝ),
      -(eps * Real.sqrt (72 * L / 11)) ≤ bregNeg (trial L eps e) (2 * L * eps ^ 2) ∧
        bregNeg (trial L eps e) (2 * L * eps ^ 2) ≤ 0 := by
    filter_upwards [Ioo_mem_nhdsGT (show (0 : ℝ) < 1 / (12 * L) by positivity)] with eps heps
    obtain ⟨h0, hb⟩ := heps
    obtain ⟨hn1, hn2, hn3⟩ := bregNeg_trial_spec hL h0 hb e
    refine ⟨?_, hn2.le⟩
    have h12 : eps * (12 * L) < 1 := (lt_div_iff₀ (by linarith)).mp hb
    have heps : eps < 1 / 12 := by nlinarith
    have hc11 : (11 : ℝ) / 12 ≤ trial L eps e := le_trans (by linarith) (trial_ge_sub h0.le e)
    have hc : 0 < trial L eps e := by linarith
    have hup := neg_bregNeg_le_sqrt hc hn1 hn2 hn3
    have hb2 : 3 * (2 * (L : ℝ) * eps ^ 2) / trial L eps e ≤ eps ^ 2 * (72 * L / 11) := by
      rw [div_le_iff₀ hc]
      nlinarith [mul_nonneg (mul_nonneg (sq_nonneg eps) (by linarith : (0 : ℝ) ≤ (L : ℝ)))
        (by linarith : (0 : ℝ) ≤ 72 / 11 * trial L eps e - 6)]
    have hle : Real.sqrt (3 * (2 * (L : ℝ) * eps ^ 2) / trial L eps e)
        ≤ eps * Real.sqrt (72 * L / 11) := by
      calc Real.sqrt (3 * (2 * (L : ℝ) * eps ^ 2) / trial L eps e)
          ≤ Real.sqrt (eps ^ 2 * (72 * L / 11)) := Real.sqrt_le_sqrt hb2
        _ = eps * Real.sqrt (72 * L / 11) := by
            rw [Real.sqrt_mul (sq_nonneg eps), Real.sqrt_sq h0.le]
    linarith
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le' hlow tendsto_const_nhds
    (hev.mono fun _ h => h.1) (hev.mono fun _ h => h.2)

/-- **CC37.**  Every interval endpoint curvature of the example tends to two. -/
theorem tendsto_hEdge (L : ℕ) (hL : 0 < L) (e : Fin (2 * L)) :
    Tendsto (fun eps => hEdge L eps e) (𝓝[>] (0 : ℝ)) (𝓝 2) := by
  have hlim : Tendsto
      (fun eps => 2 * (trial L eps e + bregNeg (trial L eps e) (2 * L * eps ^ 2)))
      (𝓝[>] (0 : ℝ)) (𝓝 2) := by
    have hsum := (tendsto_trial L e).add (tendsto_bregNeg_trial L hL e)
    have := Filter.Tendsto.const_mul (2 : ℝ) hsum
    simpa using this
  refine hlim.congr' ?_
  filter_upwards [Ioo_mem_nhdsGT (show (0 : ℝ) < 1 / (12 * L) by positivity)] with eps heps
  rw [hEdge_eq_two_mul hL heps.1 heps.2 e, loEnd]

/-- **CC37.**  The total curvature of the example tends to `4 L`. -/
theorem tendsto_hSum (L : ℕ) (hL : 0 < L) :
    Tendsto (fun eps => ∑ e, hEdge L eps e) (𝓝[>] (0 : ℝ)) (𝓝 (4 * L)) := by
  have h := tendsto_finsetSum (Finset.univ : Finset (Fin (2 * L)))
    (fun e _ => tendsto_hEdge L hL e)
  have hval : ∑ _e : Fin (2 * L), (2 : ℝ) = 4 * L := by
    rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]
    push_cast
    ring
  rwa [hval] at h

/-- **CC37.**  With the optimal factor `C_* = 1 / ∑ e, h e` of `optimalFactor_sel`, the
optimized Laplacian width `2 sqrt (2 delta C_*)`, divided by `eps`, tends to `2`. -/
theorem tendsto_laplacianWidth (L : ℕ) (hL : 0 < L) :
    Tendsto (fun eps => 2 * Real.sqrt (2 * (2 * L * eps ^ 2) * (1 / ∑ e, hEdge L eps e)) / eps)
      (𝓝[>] (0 : ℝ)) (𝓝 2) := by
  have hLR : (0 : ℝ) < L := by exact_mod_cast hL
  have hne : (4 * (L : ℝ)) ≠ 0 := by positivity
  have hlim : Tendsto (fun eps => 2 * Real.sqrt (4 * L / ∑ e, hEdge L eps e))
      (𝓝[>] (0 : ℝ)) (𝓝 2) := by
    have hq : Tendsto (fun eps => 4 * (L : ℝ) / ∑ e, hEdge L eps e) (𝓝[>] (0 : ℝ)) (𝓝 1) := by
      have hd := Filter.Tendsto.div (tendsto_const_nhds (α := ℝ) (x := 4 * (L : ℝ)))
        (tendsto_hSum L hL) hne
      rwa [div_self hne] at hd
    have := Filter.Tendsto.const_mul (2 : ℝ) hq.sqrt
    simpa using this
  refine hlim.congr' ?_
  filter_upwards [Ioo_mem_nhdsGT (show (0 : ℝ) < 1 / (12 * L) by positivity)] with eps heps
  obtain ⟨h0, -⟩ := heps
  have hz : eps ≠ 0 := h0.ne'
  rw [show 2 * (2 * (L : ℝ) * eps ^ 2) * (1 / ∑ e, hEdge L eps e)
      = eps ^ 2 * (4 * L / ∑ e, hEdge L eps e) by ring,
    Real.sqrt_mul (sq_nonneg eps), Real.sqrt_sq h0.le]
  field_simp

/-! ### Stability under rational rounding

These hypotheses express errors `o(eps)` by dividing by `eps` and taking a zero
limit. They hold for arbitrary real functions, including casts of rational outer
endpoints and upward rational roots. Rationality and the direction of rounding
are needed for certification, but not for limit stability.
-/

/-- Adding an error `o(eps)` preserves a width or radius divided by `eps`. -/
theorem tendsto_scaled_of_error {f g : ℝ → ℝ} {c : ℝ}
    (hf : Tendsto (fun eps => f eps / eps) (𝓝[>] (0 : ℝ)) (𝓝 c))
    (herr : Tendsto (fun eps => (g eps - f eps) / eps)
      (𝓝[>] (0 : ℝ)) (𝓝 0)) :
    Tendsto (fun eps => g eps / eps) (𝓝[>] (0 : ℝ)) (𝓝 c) := by
  have h := hf.add herr
  simpa only [add_zero, ← add_div, add_sub_cancel] using h

/-- **CC36, rounded endpoints.** Perturbing both actual first-path Bregman
endpoints by `o(eps)` preserves the separate-edge width asymptotic. -/
theorem tendsto_bregmanWidth_of_endpoint_errors (L : ℕ) (hL : 0 < L)
    (e : Fin (2 * L)) (he : (e : ℕ) < L) (lo hi : ℝ → ℝ)
    (hlo : Tendsto (fun eps => (lo eps - loEnd L eps e) / eps)
      (𝓝[>] (0 : ℝ)) (𝓝 0))
    (hhi : Tendsto (fun eps => (hi eps - hiEnd L eps e) / eps)
      (𝓝[>] (0 : ℝ)) (𝓝 0)) :
    Tendsto (fun eps => (hi eps - lo eps) / eps)
      (𝓝[>] (0 : ℝ)) (𝓝 (2 * Real.sqrt (2 * L))) := by
  have hexact : Tendsto (fun eps => (hiEnd L eps e - loEnd L eps e) / eps)
      (𝓝[>] (0 : ℝ)) (𝓝 (2 * Real.sqrt (2 * L))) := by
    simpa [hiEnd, loEnd, trial_apply, he, aPos, aNeg] using tendsto_bregmanWidth L hL
  apply tendsto_scaled_of_error hexact
  convert hhi.sub hlo using 1 <;> try simp only [sub_self]
  funext eps
  ring

/-- An `o(eps)` perturbation also tends to zero without scaling. -/
private theorem tendsto_error_of_scaled {f : ℝ → ℝ}
    (h : Tendsto (fun eps => f eps / eps) (𝓝[>] (0 : ℝ)) (𝓝 0)) :
    Tendsto f (𝓝[>] (0 : ℝ)) (𝓝 0) := by
  have ht : Tendsto (fun eps : ℝ => eps) (𝓝[>] (0 : ℝ)) (𝓝 0) :=
    tendsto_id.mono_left nhdsWithin_le_nhds
  have hm := h.mul ht
  simp only [zero_mul] at hm
  refine hm.congr' ?_
  filter_upwards [self_mem_nhdsWithin] with eps heps
  exact div_mul_cancel₀ _ (ne_of_gt heps)

/-- **CC37, rounded endpoints.** The curvature recomputed from perturbed
endpoints tends to two. Only the lower-endpoint error matters once it is positive. -/
theorem tendsto_curvatureFloor_of_endpoint_error (L : ℕ) (hL : 0 < L)
    (e : Fin (2 * L)) (lo hi : ℝ → ℝ)
    (hlo : Tendsto (fun eps => (lo eps - loEnd L eps e) / eps)
      (𝓝[>] (0 : ℝ)) (𝓝 0)) :
    Tendsto (fun eps => curvatureFloor 1 1 (lo eps) (hi eps))
      (𝓝[>] (0 : ℝ)) (𝓝 2) := by
  have hexact : Tendsto (fun eps => loEnd L eps e) (𝓝[>] (0 : ℝ)) (𝓝 1) := by
    simpa only [loEnd, add_zero] using
      (tendsto_trial L e).add (tendsto_bregNeg_trial L hL e)
  have hl : Tendsto lo (𝓝[>] (0 : ℝ)) (𝓝 1) := by
    simpa only [add_zero, add_sub_cancel] using
      hexact.add (tendsto_error_of_scaled hlo)
  have hmul := hl.const_mul 2
  simp only [mul_one] at hmul
  refine hmul.congr' ?_
  filter_upwards [hl.eventually_const_lt (by norm_num : (0 : ℝ) < 1)] with eps heps
  simp [curvatureFloor, heps]

/-- **CC37, rounded endpoints and root.** Recompute the optimal factor from the
perturbed interval curvatures, then approximate its square-root radius with error
`o(eps)`. The doubled radius has normalized limit `2`. This applies to rational
outer endpoints and upward rational square roots. -/
theorem tendsto_laplacianWidth_of_endpoint_root_errors (L : ℕ) (hL : 0 < L)
    (lo hi : ℝ → Fin (2 * L) → ℝ) (radius : ℝ → ℝ)
    (hlo : ∀ e, Tendsto (fun eps => (lo eps e - loEnd L eps e) / eps)
      (𝓝[>] (0 : ℝ)) (𝓝 0))
    (hradius : Tendsto (fun eps => (radius eps -
      Real.sqrt (2 * (2 * L * eps ^ 2) *
        (1 / ∑ e, curvatureFloor 1 1 (lo eps e) (hi eps e)))) / eps)
      (𝓝[>] (0 : ℝ)) (𝓝 0)) :
    Tendsto (fun eps => 2 * radius eps / eps) (𝓝[>] (0 : ℝ)) (𝓝 2) := by
  let hs := fun eps => ∑ e, curvatureFloor 1 1 (lo eps e) (hi eps e)
  have hsum : Tendsto hs (𝓝[>] (0 : ℝ)) (𝓝 (4 * L)) := by
    have h := tendsto_finsetSum (Finset.univ : Finset (Fin (2 * L)))
      (fun e _ => tendsto_curvatureFloor_of_endpoint_error L hL e
        (fun eps => lo eps e) (fun eps => hi eps e) (hlo e))
    have hval : ∑ _e : Fin (2 * L), (2 : ℝ) = 4 * L := by
      simp only [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]
      push_cast
      ring
    simpa only [hval] using h
  have hLR : (0 : ℝ) < L := by exact_mod_cast hL
  have hne : (4 * (L : ℝ)) ≠ 0 := by positivity
  have hquot : Tendsto (fun eps => 4 * L / hs eps) (𝓝[>] (0 : ℝ)) (𝓝 1) := by
    have hd := Filter.Tendsto.div
      (tendsto_const_nhds (α := ℝ) (x := (4 * (L : ℝ)))) hsum hne
    rwa [div_self hne] at hd
  have hexact : Tendsto
      (fun eps => Real.sqrt (2 * (2 * L * eps ^ 2) * (1 / hs eps)) / eps)
      (𝓝[>] (0 : ℝ)) (𝓝 1) := by
    have h := hquot.sqrt
    simp only [Real.sqrt_one] at h
    refine h.congr' ?_
    filter_upwards [self_mem_nhdsWithin] with eps heps
    have h0 : 0 < eps := heps
    rw [show 2 * (2 * (L : ℝ) * eps ^ 2) * (1 / hs eps) =
      eps ^ 2 * (4 * L / hs eps) by ring,
      Real.sqrt_mul (sq_nonneg eps), Real.sqrt_sq h0.le]
    field_simp
  have h := (tendsto_scaled_of_error hexact hradius).const_mul 2
  simpa only [mul_one, ← mul_div_assoc] using h

/-! ### CC38: a support point violating a separate-edge Bregman constraint -/

/-- **CC38.**  The exact rational value `D_1(11/10, 9/10) = 29/750`. -/
theorem edgeBregman_warning : edgeBregman 1 1 (11 / 10) (9 / 10) = 29 / 750 := by
  rw [show (9 : ℝ) / 10 = 11 / 10 + -(1 / 5) by norm_num,
    edgeBregman_one_shift (by norm_num) (by norm_num), bregShape]
  norm_num

/-- **CC38.**  The exact gap of the trial flow for `L = 1` and `eps = 1/10` is `1/50`. -/
theorem gap_warning :
    (net 1).energy (trial 1 (1 / 10)) - (net 1).energy (pathFlow 1 1 1) = 1 / 50 := by
  have h := gap_eq 1 (by norm_num : (0 : ℝ) < 1 / 10) (by norm_num : (1 / 10 : ℝ) < 1)
  rw [trial, h]
  norm_num

/-- **CC38.**  The gap is strictly below the separate-edge divergence at the opposite
support endpoint. -/
theorem delta_lt_edgeBregman_warning : (1 : ℝ) / 50 < 29 / 750 := by norm_num

/-- **CC38.**  The opposite support endpoint belongs to the support set of the trial
flow. -/
theorem mem_supportSet_warning :
    pathFlow 1 (9 / 10) (11 / 10) ∈ (net 1).supportSet (nom 1) (trial 1 (1 / 10)) := by
  refine (mem_supportSet_iff (by norm_num) (by norm_num : (0 : ℝ) ≤ 1 / 10) _).mpr
    ⟨9 / 10, ?_, ?_⟩
  · rw [abs_le]
    constructor <;> norm_num
  · congr 1
    norm_num

/-- The first-path edge value of the trial flow of the warning is `11/10`. -/
theorem trial_warning_first (e : Fin (2 * 1)) (he : (e : ℕ) < 1) :
    trial 1 (1 / 10) e = 11 / 10 := by
  rw [trial, pathFlow_first _ _ _ he]
  norm_num

/-- The first-path edge value of the opposite support endpoint is `9/10`. -/
theorem pathFlow_warning_first (e : Fin (2 * 1)) (he : (e : ℕ) < 1) :
    pathFlow 1 (9 / 10) (11 / 10) e = 9 / 10 := pathFlow_first _ _ _ he

/-- **CC38.**  A point of the support set can violate a separate-edge physical Bregman
constraint: for `L = 1` and `eps = 1/10` the flow with first-path value `9/10` lies in
`S(y)` although its divergence from `y` on a first-path edge exceeds the exact gap. -/
theorem supportSet_violates_edgeBregman (e : Fin (2 * 1)) (he : (e : ℕ) < 1) :
    pathFlow 1 (9 / 10) (11 / 10) ∈ (net 1).supportSet (nom 1) (trial 1 (1 / 10)) ∧
      (net 1).energy (trial 1 (1 / 10)) - (net 1).energy (pathFlow 1 1 1)
        < edgeBregman 1 1 (trial 1 (1 / 10) e) (pathFlow 1 (9 / 10) (11 / 10) e) := by
  refine ⟨mem_supportSet_warning, ?_⟩
  rw [trial_warning_first e he, pathFlow_warning_first e he, edgeBregman_warning, gap_warning]
  norm_num

end

end PotentialFlow.TwoPath
