import Formal.DAGSpectral.ProfileDP
import Formal.DAGSpectral.ProfileCount

namespace DAGSpectral.ExplicitDAG
open scoped BigOperators
variable {v m : ℕ} {κ : Type*} [Fintype κ]

abbrev BoundedState (required : Finset (Fin m)) (window : Finset ℤ) (κ : Type*) :=
  {mask : Finset (Fin m) // mask ∈ required.powerset} × (κ → {z : ℤ // z ∈ window})

noncomputable instance boundedStateFintype (required : Finset (Fin m)) (window : Finset ℤ) :
    Fintype (BoundedState required window κ) := by
  classical
  exact inferInstanceAs (Fintype ({mask : Finset (Fin m) // mask ∈ required.powerset} ×
    (κ → {z : ℤ // z ∈ window})))

theorem boundedState_card (required : Finset (Fin m)) (window : Finset ℤ) :
    Fintype.card (BoundedState required window κ) =
      2 ^ required.card * window.card ^ Fintype.card κ := by
  classical
  change Fintype.card ({mask : Finset (Fin m) // mask ∈ required.powerset} ×
    (κ → {z : ℤ // z ∈ window})) = _
  rw [Fintype.card_prod, Fintype.card_coe, Finset.card_powerset,
    Fintype.card_fun, Fintype.card_coe]

theorem profile_list_length_bound (required : Finset (Fin m))
    (label : Fin m → κ → ℤ) (window : Finset ℤ) (xs : List (List (Fin m)))
    (hn : (xs.map (stateKey required label)).Nodup)
    (hw : ∀ es ∈ xs, ∀ i, profile label es i ∈ window) :
    xs.length ≤
      2 ^ required.card * window.card ^ Fintype.card κ := by
  classical
  let encode : {es // es ∈ xs} → BoundedState required window κ := fun es =>
    (⟨ownerMask required es.val, Finset.mem_powerset.mpr (ownerMask_subset _ _)⟩,
      fun i => ⟨profile label es.val i, hw es.val es.property i⟩)
  let forget : BoundedState required window κ → Finset (Fin m) × (κ → ℤ) :=
    fun st => (st.1.val, fun i => (st.2 i).val)
  have he : (xs.attach.map encode).map forget = xs.map (stateKey required label) := by
    simp [List.map_map, encode, forget, stateKey, funext_iff]
  have hh : (xs.attach.map encode).Nodup := by
    apply List.Nodup.of_map forget
    rw [he]
    exact hn
  have hb := hh.length_le_card
  simpa only [List.length_map, List.length_attach, boundedState_card] using hb

/-- The actual extension list before representative merging at one vertex. -/
def transitionCandidates (G : ExplicitDAG v m) (allowed : Fin m → Bool) (t : Fin v)
    (table : PathTable v m) : List (List (Fin m)) :=
  ((List.finRange m).filter (fun e => decide (G.dst e = t) && allowed e)).flatMap
    (fun e => (table (G.src e)).map (fun es => es ++ [e]))

theorem candidates_decomposition (G : ExplicitDAG v m) (allowed : Fin m → Bool)
    (s t : Fin v) (table : PathTable v m) :
    candidates G allowed s t table = (if t = s then [[]] else []) ++
      transitionCandidates G allowed t table := rfl

theorem transitionCandidates_length (G : ExplicitDAG v m) (allowed : Fin m → Bool)
    (t : Fin v) (table : PathTable v m) :
    (transitionCandidates G allowed t table).length =
      ∑ e : Fin m, if G.dst e = t ∧ allowed e = true then (table (G.src e)).length else 0 := by
  simp only [transitionCandidates, List.length_flatMap, List.length_map]
  rw [← List.sum_toFinset _ ((List.nodup_finRange m).filter _)]
  simp [List.toFinset_filter, Finset.sum_filter]

variable (G : ExplicitDAG v m) (allowed : Fin m → Bool) (s : Fin v)
  (required : Finset (Fin m)) (label : Fin m → κ → ℤ) (window : Finset ℤ)
  (hw : ∀ t es, G.AllowedPath allowed s t es → ∀ i, profile label es i ∈ window)

include hw

theorem run_state_bound (n : ℕ) (t : Fin v) :
    (run G allowed s required label n t).length ≤
      2 ^ required.card * window.card ^ Fintype.card κ := by
  exact profile_list_length_bound required label window _
    (run_unique G allowed s required label n t)
    (fun es hes => hw t es (run_sound G allowed s required label n t es hes))

/-- Number of stored representatives, without charging an entire path as one bit. -/
def storedStates (n : ℕ) : ℕ :=
  ∑ t : Fin v, (run G allowed s required label n t).length

theorem storedStates_bound (n : ℕ) :
    storedStates G allowed s required label n ≤
      v * (2 ^ required.card * window.card ^ Fintype.card κ) := by
  unfold storedStates
  calc
    _ ≤ ∑ _t : Fin v, (2 ^ required.card * window.card ^ Fintype.card κ) :=
      Finset.sum_le_sum fun t _ => run_state_bound G allowed s required label window hw n t
    _ = _ := by simp

/-- Each allowed edge is extended once for every stored predecessor representative
when its destination vertex is processed. This counts generated transitions,
not dictionary comparisons or the scan that forms the incoming-edge lists. -/
def edgeExtensions : ℕ :=
  ∑ e : Fin m, if allowed e then
    (run G allowed s required label (G.dst e).val (G.src e)).length else 0

omit hw in
/-- The edge-extension count is exactly the sum of the lists generated by the
algorithm's vertex steps, before deduplication. -/
theorem edgeExtensions_eq_generated : edgeExtensions G allowed s required label =
    ∑ t : Fin v, (transitionCandidates G allowed t
      (run G allowed s required label t.val)).length := by
  simp only [edgeExtensions, transitionCandidates_length]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro e _
  by_cases ha : allowed e = true
  · simp [ha, eq_comm]
  · simp [ha]

theorem edgeExtensions_bound :
    edgeExtensions G allowed s required label ≤
      m * (2 ^ required.card * window.card ^ Fintype.card κ) := by
  unfold edgeExtensions
  calc
    _ ≤ ∑ _e : Fin m, (2 ^ required.card * window.card ^ Fintype.card κ) := by
      apply Finset.sum_le_sum
      intro e _
      split_ifs
      · exact run_state_bound G allowed s required label window hw _ _
      · exact Nat.zero_le _
    _ = _ := by simp

theorem output_length_bound (t : Fin v) :
    (output G allowed s t required label).length ≤
      2 ^ required.card * window.card ^ Fintype.card κ := by
  exact (List.length_filter_le _ _).trans
    (run_state_bound G allowed s required label window hw v t)

end DAGSpectral.ExplicitDAG
