"""Verify the r2 non-root claims from stored matrices and exact arithmetic.

Rebuild neighbours without importing the stream rationalization. Obtain the
integer kernel with independent SymPy graph LLL, following the reviewer.
For the four completed low-rank searches, enumerate all minimizing images
with rational LDL and integer square roots, then bound every maximizing
coset by projection onto the last two Gram-Schmidt directions. This improves
the reviewer's one-direction bound enough to check the 1.5% statement.
Usage from split-practice/: python3 code/check_nonroot_r2.py
"""
import json
import math
from fractions import Fraction as F
from pathlib import Path

import numpy as np
from sympy import Matrix, QQ, ZZ
from sympy.polys.matrices import DomainMatrix

from lattice import col_hnf, lll_gram_exact

ROOT = Path(__file__).resolve().parents[1]
FORCED = {
    'dm_QUTO_t2_n30_p25_s0__DM__cut.npz',
    'dm_QUTO_t2_n30_p25_s0__DM__cut_trace.npz',
    'bt_n20_p16_s2__BT__cut.npz',
    'bt_n50_p25_s0__BT__cut.npz',
}


def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def neighbour(Y, r):
    eig, V = np.linalg.eigh(Y)
    order = np.argsort(eig)[::-1]
    Yr = (V[:, order[:r]] * eig[order[:r]]) @ V[:, order[:r]].T
    N = len(Y)
    residual = np.diag(Yr).copy()
    L = np.zeros((N, r))
    pivots = []
    for j in range(r):
        p = int(np.argmax(residual))
        pivots.append(p)
        L[:, j] = (Yr[:, p] - L[:, :j] @ L[p, :j]) / np.sqrt(residual[p])
        residual -= L[:, j] ** 2
        residual[pivots] = -np.inf
    P = [[F(round(float(a) * 10**6), 10**6) for a in Yr[p]] for p in pivots]
    for i in range(r):
        for j in range(i):
            P[i][pivots[j]] = P[j][pivots[i]]
    C = Matrix([[P[i][pivots[j]] for j in range(r)] for i in range(r)])
    Ci = [[F(a) for a in row] for row in C.inv().tolist()]
    p0 = [row[0] for row in P]
    scale = sum(p0[i] * Ci[i][j] * p0[j] for i in range(r) for j in range(r))
    G = [[a / scale for a in row] for row in Ci]
    return P, G, eig, V, order


def q_factor(P, G, v):
    image = [dot(row, v) for row in P]
    return sum(image[i] * G[i][j] * (image[j] + P[j][0])
               for i in range(len(P)) for j in range(len(P)))


def q_stored(Y, v):
    nz = [i for i, a in enumerate(v) if a]
    return (sum(F(float(Y[i, j])) * v[i] * v[j] for i in nz for j in nz)
            + sum(F(float(Y[i, 0])) * v[i] for i in nz))


def lll(rows):
    D = DomainMatrix([[ZZ(a) for a in row] for row in rows],
                     (len(rows), len(rows[0])), ZZ)
    return [[int(a) for a in row] for row in D.lll(delta=QQ(99, 100)).to_list()]


def gso(rows):
    orthogonal, norms = [], []
    for row in rows:
        b = list(map(F, row))
        for bs, norm in zip(orthogonal, norms):
            mu = dot(row, bs) / norm
            b = [a - mu * c for a, c in zip(b, bs)]
        orthogonal.append(b)
        norms.append(dot(b, b))
    return orthogonal, norms


def exact_ball(A, c, radius):
    """All integer z with (z-c)^T A (z-c) <= radius; no floating bounds."""
    n = len(c)
    L = [[F(int(i == j)) for j in range(n)] for i in range(n)]
    D = [F(0)] * n
    for j in range(n):
        D[j] = A[j][j] - sum(L[j][k] ** 2 * D[k] for k in range(j))
        assert D[j] > 0
        for i in range(j + 1, n):
            L[i][j] = (A[i][j] - sum(L[i][k] * L[j][k] * D[k] for k in range(j))) / D[j]
    found, z = [], [0] * n
    nodes = 0

    def visit(k, partial):
        nonlocal nodes
        nodes += 1
        assert nodes <= 100000, 'exact verification node limit'
        room = radius - partial
        if room < 0:
            return
        center = c[k] - sum(L[j][k] * (z[j] - c[j]) for j in range(k + 1, n))
        p, d = center.numerator, center.denominator
        width2 = room / D[k] * d * d
        width = math.isqrt(width2.numerator // width2.denominator)
        lo, hi = -(-(p - width) // d), (p + width) // d
        for a in range(lo, hi + 1):
            nodes += 1
            assert nodes <= 100000, 'exact verification node limit'
            z[k] = a
            value = partial + D[k] * (a - center) ** 2
            if k:
                visit(k - 1, value)
            else:
                found.append((value, z[:]))

    visit(n - 1, F(0))
    return found


def coset_bound(v, kernel, bs, norms):
    t = [dot(v, b) / norm for b, norm in zip(bs, norms)]
    one = (t[-1] - round(t[-1])) ** 2 * norms[-1]
    # Project away the first d-2 vectors. Any integer kernel combination
    # projects into the 2-D lattice generated by the last two kernel rows.
    mu = dot(kernel[-1], bs[-2]) / norms[-2]
    a, b = norms[-2:]
    A = [[a, mu * a], [mu * a, mu * mu * a + b]]
    c = [-t[-2] + mu * t[-1], -t[-1]]
    m1 = round(-t[-1])
    m0 = round(-t[-2] - mu * m1)
    radius = a * (t[-2] + m0 + mu * m1) ** 2 + b * (t[-1] + m1) ** 2
    candidates = exact_ball(A, c, radius)
    assert candidates
    return one, min(value for value, _ in candidates)


def all_maximizers(P, G, q):
    """Enumerate minimizing images, then lift one vector in each coset."""
    r, N = len(P), len(P[0])
    den = math.lcm(*(a.denominator for row in P for a in row))
    M = [[int(a * den) for a in row] for row in P]
    H, U = col_hnf(M)
    assert abs(Matrix(U).det()) == 1
    assert Matrix(M) * Matrix(U) == Matrix(H).row_join(Matrix.zeros(r, N - r))
    W = Matrix(H) / den
    A = [[F(a) for a in row] for row in (W.T * Matrix(G) * W).tolist()]
    R = Matrix(lll_gram_exact(A))
    A2 = [[F(a) for a in row] for row in (R.T * Matrix(A) * R).tolist()]
    c = [F(a) for a in (W * R).inv() * (-Matrix([row[0] for row in P]) / 2)]
    candidates = exact_ball(A2, c, q + F(1, 4))
    assert candidates and min(value for value, _ in candidates) == q + F(1, 4)
    T = Matrix([row[:r] for row in U])
    vectors = [[int(a) for a in T * R * Matrix(z)] for value, z in candidates
               if value == q + F(1, 4)]
    assert all(q_factor(P, G, v) == q for v in vectors)
    return vectors


def main():
    rows = [json.loads(line) for line in (ROOT / 'logs/thm3_r1.jsonl').read_text().splitlines()]
    records = []
    with (ROOT / 'logs/nonroot_r2.jsonl').open('w') as out:
        for d in rows:
            t, f = d['thm3'], d['file']
            if f.endswith('root.npz') or t['v'] is None:
                continue
            r, v = d['rank'], t['v']
            n = f.split('_n')[1].split('_')[0]
            family = 'BT' if f.startswith('bt') else 'DM'
            Y = np.load(ROOT / f'data/points_{family}{n}/{f}')['Y']
            Y = (Y + Y.T) / 2
            P, G, eig, V, order = neighbour(Y, r)
            q = q_factor(P, G, v)
            assert q == F(t['q_exact'])
            qY = q_stored(Y, v)
            assert qY == F(t['q_at_Y_exact'])
            den = math.lcm(*(a.denominator for row in P for a in row))
            M = [[int(a * den) for a in row] for row in P]
            content = math.gcd(*(a for row in M for a in row))
            M = [[a // content for a in row] for row in M]
            N = len(v)
            graph = lll([[int(i == j) for j in range(N)] + [10**40 * M[k][i] for k in range(r)]
                         for i in range(N)])
            # LLL's integer unimodular graph transform gives the full kernel.
            assert abs(Matrix([row[:N] for row in graph]).det()) == 1
            kernel = lll([row[:N] for row in graph if not any(row[N:])])
            assert len(kernel) == N - r
            assert all(dot(row, k) == 0 for row in M for k in kernel)
            bs, norms = gso(kernel)
            one, two = coset_bound(v, kernel, bs, norms)
            u = 2 * np.array(v, float)
            u[0] += 1
            projection = V.T @ u
            parts = eig * projection ** 2 / 4
            top, tail = float(sum(parts[order[:r]]) - Y[0, 0] / 4), float(sum(parts[order[r:]]))
            assert abs(top + tail - float(qY)) <= 1e-5 * max(1, abs(float(qY)))
            rec = dict(file=f, q_exact=str(q), q_at_Y_exact=str(qY), q_at_Y=float(qY),
                       vmax=max(map(abs, v)), norm2=dot(v, v),
                       ratio_at_Y=float(-qY / dot(v[1:], v[1:])),
                       both_complete=t['first_complete'] and t['second_complete'],
                       coset_bound_one=math.sqrt(float(one)), coset_bound_two=math.sqrt(float(two)),
                       lambda_r1=float(eig[order[r]]), top_part=top, tail_part=tail)
            if f in FORCED:
                assert rec['both_complete']
                maximizers = all_maximizers(P, G, q)
                lower2 = min(coset_bound(w, kernel, bs, norms)[1] for w in maximizers)
                assert F(dot(v, v)) <= F(1015, 1000) ** 2 * lower2
                rec.update(maximizing_images=len(maximizers), all_maximizers_bound2=str(lower2),
                           all_maximizers_bound=math.sqrt(float(lower2)),
                           returned_over_shortest_bound=math.sqrt(float(F(dot(v, v)) / lower2)))
            records.append(rec)
            out.write(json.dumps(rec) + '\n')
            out.flush()
            print(json.dumps(rec), flush=True)
    violated = [d for d in records if d['q_at_Y'] < 0]
    assert len(records) == 13 and len(violated) == 5
    assert min(d['vmax'] for d in records) == 30 and max(d['vmax'] for d in records) == 69618975
    assert max(d['ratio_at_Y'] for d in violated) <= 8.2e-6
    assert sum('maximizing_images' in d for d in records) == 4
    print('PASS: 13 exact neighbour/stored values; 8 unviolated, 5 ratios <= 8.2e-6; '
          'all maximizing cosets at 4 completed points have long-vector bounds within 1.5%.')


if __name__ == '__main__':
    main()
