"""Generate manuscript tables directly from the complete repeated benchmark."""
import hashlib
import json
from pathlib import Path
from statistics import median

PAPER = Path(__file__).resolve().parents[1]
source = PAPER/'verification/stage06-benchmarks.json'
data = json.loads(source.read_text())
assert not data['quick'] and data['repetitions'] == 5
assert len(data['flat']) == 16 and len(data['membership']) == 3 and len(data['optimization']) == 3
for case in data['flat']+data['membership']+data['optimization']:
    assert len(case['runs']) == 5
    for method, stats in case['summary'].items():
        for key, value in stats.items():
            raw = [run['measurements'][method][key] for run in case['runs']]
            assert value == {'minimum':min(raw), 'median':median(raw), 'maximum':max(raw)}

folder = PAPER/'tables'; folder.mkdir(exist_ok=True)
header = '% Generated by verification/stage06-tables.py; data SHA256 '+hashlib.sha256(source.read_bytes()).hexdigest()+'\n'
names = {'full':'Full', 'global':'Global merge', 'initial':'Initial compression', 'eliminated':'Observed elimination',
         'network_states':'Independent networks', 'cuts':'Repeated cuts', 'separator':'Exact separator',
         'flat':'Reduced exact', 'unreduced':'Unreduced exact', 'two_state':'One-flow LP'}


def ms(case, method, field='total_seconds', ranges=False):
    if method not in case['summary']: return '--'
    stat = case['summary'][method][field]
    value = f"{1000*stat['median']:.2f}"
    return value+f" [{1000*stat['minimum']:.2f},{1000*stat['maximum']:.2f}]" if ranges else value


def write(name, body):
    (folder/name).write_text(header+body+'\n')


case = data['optimization'][0]
rows = []
for method, warm in case['warmup'].items():
    stat = warm['stats']
    rows.append(' & '.join([names[method], str(stat['variables']), str(stat['rows']), str(stat['nonzeros']),
                            ms(case, method, ranges=True), ms(case, method, 'build_seconds'), ms(case, method, 'solve_seconds')])+r' \\')
write('08-optimization.tex', '\n'.join([
    r'\begin{table}[tb]\centering\footnotesize',
    r'\caption{The 43-arc, 128-label optimization case. Times are milliseconds; total reports median [minimum,maximum] over five runs. The network baseline reuses one matrix for sequential solves. Repeated-cut build/solve columns exclude its separately recorded separator and reconstruction work, which the total includes.}',
    r'\label{tab:computation-opt}', r'\setlength{\tabcolsep}{3pt}',
    r'\begin{tabular}{lrrr rrr}\toprule',
    r'Method & Vars. & Rows & Nonzeros & Total & Build & Solve\\\midrule',
    *rows, r'\bottomrule\end{tabular}\end{table}']))

rows = []
for case in data['membership']:
    rows.append(' & '.join([str(case['states'])]+[ms(case, method) for method in ('full','global','initial','eliminated','separator')])+r' \\')
write('08-membership.tex', '\n'.join([
    r'\begin{table}[tb]\centering\small',
    r'\caption{Feasible membership on the 51-arc, 36-observation family: median construction-plus-query milliseconds. The exact-separator column is membership without requested decomposition; the raw data separately record constructive queries and all timing ranges.}',
    r'\label{tab:computation-member}', r'\begin{tabular}{rrrrrr}\toprule',
    r'Labels & Full & Global merge & Initial & Eliminated & Exact separator\\\midrule',
    *rows,r'\bottomrule\end{tabular}\end{table}']))

rows = []
for case in data['flat']:
    rows.append(' & '.join([str(case['gadgets']), 'Interior' if case['weights']=='interior' else 'Boundary',
                            'In' if case['feasible'] else 'Out']+
                           [ms(case, method) for method in ('full','two_state','unreduced','flat')])+r' \\')
write('08-flat.tex', '\n'.join([
    r'\begin{table}[tb]\centering\small',
    r'\caption{Flat-chain membership: median construction-plus-query milliseconds. Boundary weights are $(1/2,1/2)$; interior weights are $(1/3,1/3)$. Full retains only positive states. The one-flow reduction applies only with two positive states. Exact columns exclude optional decomposition; all ranges and constructive workloads are retained in the data.}',
    r'\label{tab:computation-flat}',r'\begin{tabular}{rllrrrr}\toprule',
    r'$L$ & Weights & Point & Full & One-flow LP & Unreduced exact & Reduced exact\\\midrule',
    *rows,r'\bottomrule\end{tabular}\end{table}']))

rows = []
for case in data['optimization'][1:]:
    label = 'Aggregate budget' if 'budget' in case['name'] else 'All labels observed'
    rows.append(' & '.join([label]+[ms(case, method) for method in ('full','global','initial','eliminated','network_states','cuts')])+r' \\')
write('08-ablations.tex', '\n'.join([
    r'\begin{table}[tb]\centering\small',
    r'\caption{Two controls: median total optimization milliseconds. Independent network optimization is inapplicable with the aggregate budget. Repeated cutting was measured on the original and budgeted instance, not on the all-labels-observed control.}',
    r'\label{tab:computation-ablations}',r'\setlength{\tabcolsep}{3pt}',
    r'\begin{tabular}{lrrrrrr}\toprule',
    r'Case & Full & Global & Initial & Eliminated & Networks & Cuts\\\midrule',
    *rows,r'\bottomrule\end{tabular}\end{table}']))

macro = [r'\newcommand{\BenchPython}{'+data['versions']['python']+'}',
         r'\newcommand{\BenchNumpy}{'+data['versions']['numpy']+'}',
         r'\newcommand{\BenchScipy}{'+data['versions']['scipy']+'}']
case = data['optimization'][0]
for macro_name, value in [('BenchHullObjective',case['objective']),
                          ('BenchMcObjective',case['warmup']['cuts']['mccormick_objective']),
                          ('BenchBudgetObjective',data['optimization'][1]['objective'])]:
    macro.append('\\newcommand{\\'+macro_name+'}{'+f'{value:.6f}'+'}')
macro.append(r'\newcommand{\BenchCutCount}{'+str(case['warmup']['cuts']['cuts'])+'}')
for name, key in [('BenchOldCold','unreduced_three_coordinate_circuits_seconds'),
                  ('BenchNewThreeCold','reduced_three_observed_label_circuits_seconds'),
                  ('BenchNewThreeBases','reduced_three_observed_label_bases_seconds')]:
    macro.append('\\newcommand{\\'+name+'}{'+f"{1000*data['cold'][key]:.2f}"+'}')
write('08-values.tex', '\n'.join(macro))
print(json.dumps({'tables':5,'data_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'status':'PASS'},indent=2))
