"""Exact independent checks for review 1; no manuscript implementation imports."""
import itertools as it
import json
import random
from pathlib import Path
import sympy as s

counts = dict(graphs=0, cycle_blocks=0, observation_sets=0, minors=0,
              schur_systems=0, reconstruction_checks=0, refinements=0,
              degenerate_refinements=0)

def incidence(n, edges):
    a=s.zeros(n,len(edges))
    for e,(u,v) in enumerate(edges):
        a[u,e]-=1; a[v,e]+=1
    return a

def cycle_components(n,edges):
    # Independent definition: equivalence generated by common simple cycles.
    parent=list(range(len(edges))); cyclic=set()
    def root(i):
        while parent[i]!=i: i=parent[i]
        return i
    for mask in range(1,1<<len(edges)):
        es=[i for i in range(len(edges)) if mask>>i&1]
        deg=[0]*n; adj=[set() for _ in range(n)]
        for i in es:
            u,v=edges[i]; deg[u]+=1;deg[v]+=1;adj[u].add(v);adj[v].add(u)
        vs={i for i,d in enumerate(deg) if d}
        if any(deg[i]!=2 for i in vs): continue
        todo=[next(iter(vs))]; seen=set(todo)
        while todo:
            for v in adj[todo.pop()]-seen: seen.add(v);todo.append(v)
        if seen!=vs: continue
        cyclic.update(es)
        for i in es: parent[root(i)]=root(es[0])
    groups={}
    for e in cyclic:groups.setdefault(root(e),[]).append(e)
    return list(groups.values()), set(range(len(edges)))-cyclic

def components(n,edges):
    groups=[{i} for i in range(n)]
    for u,v in edges:
        a=next(g for g in groups if u in g); b=next(g for g in groups if v in g)
        if a is not b:a.update(b);groups.remove(b)
    return len(groups)

rng=random.Random(901)
all_edges=list(it.combinations(range(4),2))
graphs=[]
for mask in [0,1,7,11,15,23,31,39,47,55,59,61,63]:
    edges=[(v,u) if rng.randrange(2) else (u,v) for e,(u,v) in enumerate(all_edges) if mask>>e&1]
    graphs.append((4,edges))
graphs += [(2,[(0,1),(1,0),(0,1),(1,0)]),
           (7,[(0,1),(2,1),(2,0),(2,3),(4,3),(2,4),(4,4),(4,5)]),
           (4,[(0,0),(1,1),(0,1),(2,3),(3,2)]),
           (5,[(0,1),(1,2),(2,0),(0,3),(3,4),(4,0),(1,3),(2,4)])]
for n,edges in graphs:
    A=incidence(n,edges); E=len(edges); ns=A.nullspace()
    C=s.Matrix.hstack(*ns) if ns else s.zeros(E,0); r=C.cols
    assert A*C==s.zeros(n,r)
    assert r==E-n+components(n,edges)
    blocks,bridges=cycle_components(n,edges)
    for B in blocks:
        counts['cycle_blocks']+=1
        assert A[:,B]*C[B,:]==s.zeros(n,r)
    assert all(C[e,:]==s.zeros(1,r) for e in bridges)
    assert sum(len(B)-len(set(v for e in B for v in edges[e]))+1 for B in blocks)==r
    for d in range(1,r+1):
        for rr in it.combinations(range(E),d):
            for cc in it.combinations(range(r),d):
                assert C.extract(rr,cc).det() in (-1,0,1)
                counts['minors']+=1
    for mask in range(1<<E):
        obs=[e for e in range(E) if mask>>e&1]; unobs=[e for e in range(E) if not mask>>e&1]
        Dall=C[obs,:]; d=Dall.rank()
        assert r-d==len(unobs)-n+components(n,[edges[e] for e in unobs])
        counts['observation_sets']+=1
        # Every available coordinate raises rank by at most one; directly check
        # the minimum by an exhaustive search for small residual dimensions.
        if r-d<=2:
            for k in range(r-d):
                assert all(C[obs+list(add),:].rank()<r for add in it.combinations(unobs,k))
            assert any(C[obs+list(add),:].rank()==r for add in it.combinations(unobs,r-d))
        # RREF of Dall.T chooses independent actual observed rows.
        selected=list(Dall.T.rref()[1]); D=Dall[selected,:]
        for I in it.combinations(range(r),d):
            B=D[:,I]
            if B.det()==0:continue
            F=[k for k in range(r) if k not in I]
            W=C[:,I]*B.inv(); R=C[:,F]-W*D[:,F]
            assert set(W)|set(R)<=set(map(s.Integer,[-1,0,1]))
            t=s.Matrix([s.Rational(2*k-3,7) for k in range(r)])
            assert W*(D*t)+R*t[F,:]==C*t
            counts['schur_systems']+=1; counts['reconstruction_checks']+=1
    counts['graphs']+=1

# Articulation blocks, differently merged labels, a bridge, and zero capacity.
n,edges=graphs[14]; A=incidence(n,edges); blocks,bridges=cycle_components(n,edges)
C=s.Matrix.hstack(*A.nullspace()); E=len(edges)
weight_sets=[list(map(s.Rational,w)) for w in
             [(1,0,0,0,0),(0,s.Rational(1,4),s.Rational(1,2),s.Rational(1,4),0),
              (s.Rational(1,5),s.Rational(1,5),0,s.Rational(3,5),0)]]
for degenerate in (False,True):
    u=s.ones(E,1); center=s.ones(E,1)/2
    if degenerate:u[6]=center[6]=0
    b=A*center
    # The reference obeys equality only; it deliberately violates capacities.
    v=center+C*s.ones(C.cols,1)*3
    assert A*v==b and any(v[e]<0 or v[e]>u[e] for e in range(E))
    vertices=[]
    for k in range(5):
        t=s.Matrix([s.Rational((k+i)%3-1,10) for i in range(C.cols)])
        if degenerate:
            # The loop is an independent nullspace coordinate.
            for j in range(C.cols):
                if C[6,j]:t[j]=0
        f=center+C*t
        assert A*f==b and all(0<=f[e]<=u[e] for e in range(E))
        vertices.append(f)
    for weights in weight_sets:
        raw=[weights[k]*vertices[k] for k in range(5)]
        x=sum(raw,s.zeros(E,1))
        for observed_sets in it.product([set(),{1},{2,3},{1,2,3,4}],repeat=len(blocks)):
            rebuilt=[weights[k]*v for k in range(5)]
            for block,J in zip(blocks,observed_sets):
                omitted=set(range(5))-J
                mu=sum(weights[k] for k in omitted)
                merged=sum((raw[k][block,:]-weights[k]*v[block,:] for k in omitted),s.zeros(len(block),1))
                for k in range(5):
                    g=raw[k][block,:]-weights[k]*v[block,:] if k in J else (weights[k]*merged/mu if mu else s.zeros(len(block),1))
                    for i,e in enumerate(block):rebuilt[k][e]+=g[i]
                for k in J:assert rebuilt[k][block,:]==raw[k][block,:]
            assert sum(rebuilt,s.zeros(E,1))==x
            for k,f in enumerate(rebuilt):
                assert A*f==weights[k]*b
                assert all(0<=f[e]<=weights[k]*u[e] for e in range(E))
                if not weights[k]:assert f==s.zeros(E,1)
            counts['refinements']+=1
            counts['degenerate_refinements']+=int(degenerate)

Path(__file__).with_suffix('.json').write_text(json.dumps(counts,indent=2)+'\n')
print(json.dumps(counts,indent=2))
