"""Exact check that Corollary 3.12 of Kilinc-Karzan-Yang (author draft, rev. Oct. 2017, p. 17),
read as printed, has counterexamples (review round 1, issue M2).

Printed hypotheses: D_1 in cl(B_2) cap cone(A), D_2 in (cl(R_++(B_2)) minus cl(B_2)) cap cone(A),
(i) R_++(D_1 u D_2) u {0} contains cl(R_++(B_2)) cap cone(A), (ii) t d not in cl(B_2) for d in D_1,
0 <= t < 1, (iii) sigma(d) > 1 on D_1 and sigma(d) > 0 on D_2, where for A = I and c >= 0,
sigma(d) = sigma_{D_c}(d) = max{lambda^T d : lambda <= c} = c^T d for d >= 0.

In both examples A = I (2x2), c = (1, 1), D_1 = empty, and D_2 consists of points on the
coordinate axes.  For A = I in R^2 every nonzero point of cl(R_++(B_2)) cap R^2_+ lies on an
axis (a limit of t_n b_n with b_n outside R^2_+ has a zero coordinate), so (i) holds once D_2
has a point on each axis that is needed.  The printed corollary would then say that c is
generated by a CGF; both examples show that it is not.

Example 1: KY Example 4.3 (draft p. 22), B_2 = {(1 - 1/sqrt(n), -1/n) : n >= 1}, cl(B_2) = B_2 u {(1, 0)};
   D_2 = {(1/2, 0)}.  (Only the e_1 axis is needed: KY state cl(R_++(B_2)) cap cone(A) = cone(e_1).)
Example 2: sfree Proposition 2(b), B = {lam : q(lam) <= 0}, q = l1 - l1^2 + (1 - l2)^2;
   D_2 = {(1/2, 0), (0, 1/2)} (neither point is in B, hence not in cl(B_2), since B is closed).
   A CGF generating c = (1, 1) would give an S-free set attaining z_K = 1 (note Section 4.1),
   which Proposition 2(b) excludes.
"""
from fractions import Fraction as Fr

c = (Fr(1), Fr(1))
sigma = lambda d: c[0] * d[0] + c[1] * d[1]          # valid for d >= 0, A = I

print("Example 1 (KY Ex. 4.3):")
d = (Fr(1, 2), Fr(0))
# Distance from d to b_n = (1 - 1/sqrt(n), -1/n):
#   n <= 8: |b_n2 - d2| = 1/n >= 1/8;   n >= 9: b_n1 - d1 = 1/2 - 1/sqrt(n) >= 1/2 - 1/3 = 1/6.
# Both bounds use only rational arithmetic (1/sqrt(n) <= 1/3 iff n >= 9).
# The case split is a hand proof; the script only evaluates the two rational bounds it uses.
lb_small = min(Fr(1, n) for n in range(1, 9))          # n <= 8: second coordinates differ by 1/n
lb_large = Fr(1, 2) - Fr(1, 3)                          # n >= 9: first coordinates differ by >= 1/6
print("  D_2 point", d, ": hand case split (n <= 8: |2nd coord diff| = 1/n >=", lb_small,
      "; n >= 9: 1st coord diff >=", lb_large, ") gives distance to B_2 >=", min(lb_small, lb_large))
# Numerical sanity check of the hand bound (floating point, finitely many n; not a proof).
import math
mind = min(math.hypot(1 - 1 / math.sqrt(n) - 0.5, -1 / n) for n in range(1, 10**5 + 1))
print("  numerical check: min over n <= 10^5 of the distance to b_n = %.6f (>= 1/8)" % mind)
print("  distance to the limit point (1,0) = 1/2 > 0; so d not in cl(B_2); sigma =", sigma(d), "> 0")
print("  KY prove in Ex. 4.3 that c = (1,1) is NOT generated -> printed Cor. 3.12 fails")
print("  KY's proof uses 2d/sigma(d) =", tuple(2 * x / sigma(d) for x in d),
      "; the segment (0, 2d/sigma) contains (1,0) in cl(B_2), so Prop. 3.11(ii) fails for it")

print("Example 2 (sfree Prop. 2(b)):")
q = lambda l: l[0] - l[0]**2 + (1 - l[1])**2
for d in [(Fr(1, 2), Fr(0)), (Fr(0), Fr(1, 2))]:
    print("  D_2 point", d, ": q =", q(d), "> 0 (not in B, so not in cl(B_2)); sigma =", sigma(d), "> 0")
for s in [Fr(1, 10), Fr(1, 1000)]:
    pt = (-s * s, 1 - s)
    print("  s =", s, ": q(-s^2, 1-s) =", q(pt), "= -s^4 :", q(pt) == -s**4, "(points of B_2 -> (0,1))")
print("  first point of B on ray e_2: q(0,t) = (1-t)^2 vanishes only at t = 1 -> (0,1) in cl(B_2),")
print("  so in the corrected reading ray e_2 needs D_1 = {(0,1)} with sigma =", sigma((Fr(0), Fr(1))),
      "(not > 1): corrected Cor. 3.12 does not apply, consistent with Prop. 2(b)")
