#!/usr/bin/env python3
"""Translate the saved JSON into kernel-checkable rational Lean data."""

import argparse
from fractions import Fraction
import hashlib
import json
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "code/potential_flow_mpd/envelope_certificate_example.json"
TARGET = ROOT / "formal/Formal/PotentialFlow/Example.lean"


def rational(value):
    if not isinstance(value, str) or not re.fullmatch(r"-?\d+(?:/[1-9]\d*)?", value):
        raise ValueError(f"Expected an exact rational string, got {value!r}")
    Fraction(value)  # Reject malformed rational data before generating Lean.
    return "(" + value.replace("/", " / ") + " : ℚ)"


def vector(values):
    return "![" + ",\n    ".join(values) + "]"


def render():
    raw = SOURCE.read_bytes()
    data = json.loads(raw)
    required = {"edges", "b", "positive", "negative", "flow", "potentials", "root_upper", "gap", "radius"}
    if set(data) != required:
        raise ValueError("Unexpected certificate fields")
    n, m = len(data["b"]), len(data["edges"])
    if n == 0 or m == 0:
        raise ValueError("The example must have nodes and edges")
    for name in ("positive", "negative", "flow", "root_upper"):
        if len(data[name]) != m:
            raise ValueError(f"Wrong edge-vector dimension: {name}")
    if len(data["potentials"]) != n:
        raise ValueError("Wrong potential-vector dimension")
    for edge in data["edges"]:
        if len(edge) != 2 or any(type(v) is not int or not 0 <= v < n for v in edge):
            raise ValueError("Invalid edge endpoints")

    def qvector(name):
        return vector([rational(value) for value in data[name]])

    tails = vector([f"⟨{e[0]}, by decide⟩" for e in data["edges"]])
    heads = vector([f"⟨{e[1]}, by decide⟩" for e in data["edges"]])
    gap = rational(data["gap"]).replace(" / ", " /\n      ")
    return f'''import Formal.PotentialFlow.RationalData

/-! Generated by `topics/03-potential-flow/generate_example.py`.
Source: `code/potential_flow_mpd/envelope_certificate_example.json`.
SHA-256: {hashlib.sha256(raw).hexdigest()}
The generator only translates data; Lean proves all certificate conditions.
-/

namespace PotentialFlow.Example

def network : RationalNetwork {n} {m} where
  tail := {tails}
  head := {heads}
  positive := {qvector("positive")}
  negative := {qvector("negative")}

def nominations : Fin {n} → ℚ := {qvector("b")}

def certificate : RationalCertificate {n} {m} where
  flow := {qvector("flow")}
  potentials := {qvector("potentials")}
  rootUpper := {qvector("root_upper")}
  gap :=
    {gap}
  radius := {rational(data["radius"])}

set_option maxRecDepth 10000 in
theorem accepted : network.Accepted (by decide : 0 < {m}) nominations certificate := by
  decide +kernel

theorem radius_lt_one_five_thousandth : certificate.radius < (1 / 5000 : ℚ) := by
  norm_num [certificate]

end PotentialFlow.Example
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check that the committed Lean file matches the JSON")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != content:
            raise SystemExit("Generated PotentialFlow/Example.lean differs; rerun this generator")
        print("PASS: PotentialFlow/Example.lean exactly matches the saved JSON")
    else:
        TARGET.write_text(content)


if __name__ == "__main__":
    main()
