import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.LinearAlgebra.LinearIndependent.Lemmas

open Set Finset Topology

namespace QuadraticAggregation

variable {ι E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- The cone generated by a finite indexed family. -/
def finiteCone (v : ι → E) (s : Finset ι) : Set E :=
  {y | ∃ w : ι → ℝ, (∀ i ∈ s, 0 ≤ w i) ∧ ∑ i ∈ s, w i • v i = y}

private theorem finiteCone_mono (v : ι → E) {s t : Finset ι} (hst : s ⊆ t) :
    finiteCone v s ⊆ finiteCone v t := by
  classical
  rintro y ⟨w, hw, rfl⟩
  refine ⟨fun i => if i ∈ s then w i else 0, ?_, ?_⟩
  · intro i hi
    dsimp
    split_ifs with h
    · exact hw i h
    · exact le_rfl
  · simp only [ite_smul, zero_smul]
    rw [sum_ite_mem]
    simp [Finset.inter_eq_right.mpr hst]

private theorem finiteCone_closed_of_independent (v : ι → E) (s : Finset ι)
    (hv : LinearIndependent ℝ (fun i : s => v i)) : IsClosed (finiteCone v s) := by
  classical
  let L : (s → ℝ) →ₗ[ℝ] E := Fintype.linearCombination ℝ (fun i : s => v i)
  have hL : IsClosedEmbedding L := LinearMap.isClosedEmbedding_of_injective
    (LinearMap.ker_eq_bot.mpr hv.fintypeLinearCombination_injective)
  have hc : IsClosed {w : s → ℝ | ∀ i, 0 ≤ w i} :=
    by
      simpa only [Set.ofPred_forall] using
        (isClosed_iInter fun i : s =>
          isClosed_le (continuous_const : Continuous (fun _ : s → ℝ => (0 : ℝ)))
            (continuous_apply i))
  have heq : finiteCone v s = L '' {w : s → ℝ | ∀ i, 0 ≤ w i} := by
    ext y
    constructor
    · rintro ⟨w, hw, hsum⟩
      refine ⟨fun i => w i, fun i => hw i i.property, ?_⟩
      change ∑ i : s, w i • v i = y
      rw [Finset.sum_coe_sort s (fun i => w i • v i)]
      exact hsum
    · rintro ⟨w, hw, rfl⟩
      refine ⟨fun i => if hi : i ∈ s then w ⟨i, hi⟩ else 0, ?_, ?_⟩
      · intro i hi
        simpa [hi] using hw ⟨i, hi⟩
      · simp [L, Fintype.linearCombination_apply, ← Finset.sum_attach s]
  rw [heq]
  exact hL.isClosedMap _ hc

private theorem exists_positive_relation (v : ι → E) (s : Finset ι)
    (hv : ¬ LinearIndependent ℝ (fun i : s => v i)) :
    ∃ g : ι → ℝ, (∑ i ∈ s, g i • v i = 0) ∧ ∃ i ∈ s, 0 < g i := by
  classical
  obtain ⟨g, hg, i, hi⟩ := Fintype.not_linearIndependent_iff.mp hv
  have hex : ∃ g : s → ℝ, (∑ i, g i • v i = 0) ∧ ∃ i, 0 < g i := by
    rcases lt_or_gt_of_ne hi with hn | hp
    · refine ⟨fun j => - g j, ?_, i, neg_pos.mpr hn⟩
      simp only [neg_smul, Finset.sum_neg_distrib, hg, neg_zero]
    · exact ⟨g, hg, i, hp⟩
  obtain ⟨g, hg, i, hi⟩ := hex
  refine ⟨fun i => if hi : i ∈ s then g ⟨i, hi⟩ else 0, ?_, i, i.property, ?_⟩
  · simpa [← Finset.sum_attach s] using hg
  · simpa using hi

private theorem finiteCone_mem_erase [DecidableEq ι] (v : ι → E) (s : Finset ι)
    (hv : ¬ LinearIndependent ℝ (fun i : s => v i)) {y : E}
    (hy : y ∈ finiteCone v s) : ∃ i ∈ s, y ∈ finiteCone v (s.erase i) := by
  classical
  obtain ⟨w, hw, rfl⟩ := hy
  obtain ⟨g, hg, j, hj, hgj⟩ := exists_positive_relation v s hv
  let p := s.filter (fun i => 0 < g i)
  obtain ⟨i₀, hi₀, hmin⟩ := p.exists_min_image (fun i => w i / g i)
    ⟨j, by simp [p, hj, hgj]⟩
  have his : i₀ ∈ s := (Finset.mem_filter.mp hi₀).1
  have hgi : 0 < g i₀ := (Finset.mem_filter.mp hi₀).2
  let k : ι → ℝ := fun i => w i - w i₀ / g i₀ * g i
  have hk : k i₀ = 0 := by simp [k, ne_of_gt hgi]
  refine ⟨i₀, his, k, ?_, ?_⟩
  · intro i hi
    have his' := (Finset.mem_erase.mp hi).2
    change 0 ≤ w i - w i₀ / g i₀ * g i
    rw [sub_nonneg]
    by_cases hgp : 0 < g i
    · exact (le_div_iff₀ hgp).mp (hmin i (by simp [p, his', hgp]))
    · exact (mul_nonpos_of_nonneg_of_nonpos
        (div_nonneg (hw i₀ his) hgi.le) (le_of_not_gt hgp)).trans (hw i his')
  · calc
      ∑ i ∈ s.erase i₀, k i • v i = ∑ i ∈ s, k i • v i :=
        Finset.sum_erase _ (by simp [hk])
      _ = ∑ i ∈ s, w i • v i := by
        simp [k, sub_smul, mul_smul, Finset.sum_sub_distrib, ← Finset.smul_sum, hg]

/-- A finitely generated cone is closed. -/
theorem isClosed_finiteCone (v : ι → E) (s : Finset ι) :
    IsClosed (finiteCone v s) := by
  classical
  induction s using Finset.strongInductionOn
  rename_i s ih
  by_cases hv : LinearIndependent ℝ (fun i : s => v i)
  · exact finiteCone_closed_of_independent v s hv
  · have heq : finiteCone v s = ⋃ i : s, finiteCone v (s.erase i) := by
      ext y
      simp only [Set.mem_iUnion]
      constructor
      · intro hy
        obtain ⟨i, hi, hy⟩ := finiteCone_mem_erase v s hv hy
        exact ⟨⟨i, hi⟩, hy⟩
      · rintro ⟨i, hi⟩
        exact finiteCone_mono v (Finset.erase_subset _ _) hi
    rw [heq]
    exact isClosed_iUnion_of_finite fun i => ih (s.erase i) (Finset.erase_ssubset i.property)

/-- Closedness of all nonnegative linear combinations of a finite family. -/
theorem isClosed_nonnegative_span [Fintype ι] (v : ι → E) :
    IsClosed {y | ∃ w : ι → ℝ, (∀ i, 0 ≤ w i) ∧ ∑ i, w i • v i = y} := by
  simpa [finiteCone] using isClosed_finiteCone v Finset.univ

end QuadraticAggregation
