"""Discovery: alternating ascent  y <- argmin_R <p,y>,  p <- argmin_{p in B} <p,y>.
phi(y) = -min_{p in B} <p,y> increases monotonically.  phi > 0 means y in R
is outside H3plus and the final p is a valid quadratic missing from the cone
generated by D3 and the family copies.  Numerical only."""
import sys, json, time, warnings
import numpy as np
warnings.filterwarnings("ignore")
from cube3 import *
from sdp3 import *

seed = int(sys.argv[1]); starts = int(sys.argv[2])
use_family = (sys.argv[3] == 'family') if len(sys.argv) > 3 else True
rng = np.random.default_rng(seed)
S = Separation(); R = Relaxation(use_family=use_family)
found = []
t0 = time.time()
for s in range(starts):
    c = rng.normal(size=10)
    c[4:7] = np.abs(c[4:7]) * rng.random(3)
    val, st, y = R.solve(c)
    if y is None or val is None: continue
    best = None
    for it in range(12):
        yq = np.array([y[MINDEX[k]] for k in QKEYS])
        sv, sst, p = S.solve(yq)
        if p is None: break
        if best is not None and sv > best - 1e-9: break
        best = sv
        rv, rst, y = R.solve(p)
        if y is None: break
    if best is not None and best < -1e-6:
        p = p / np.abs(p).max()
        found.append(dict(start=s, phi=-best, p=p.tolist(), y=yq.tolist()))
        print('FOUND', s, -best, np.round(p, 4).tolist(), flush=True)
print('starts', starts, 'found', len(found), 'time', time.time() - t0, flush=True)
json.dump(found, open(f'../logs/ascent_{"family" if use_family else "d3"}_{seed}.json', 'w'))
