"""Build the sample selections for the waterno2_06 record re-bounding.

Input: the full certB selection regenerated by the review's make_selection.py
(order and groups as in the review: path, near0.05, near0.5, leaf0.05/leaf0.5,
leaf-random-corrected, rest; 'rest' is already shuffled with seed 20261001) and
the sepbranch review's sel_cert3.json.

Outputs (written to OUTDIR given as argv[3]):
  sel_vbb2_certB.json : review-driver tasks: all path, near0.05, leaf* tasks,
                        the first 300 near0.5 records, the first 500 rest records;
  sel_rbb_certB.json  : record ids for the authors' rbb re-run: path, near0.05,
                        first 300 near0.5, first 1000 rest;
  sel_rbb_cert3.json  : the 330 records of the sepbranch review's sel_cert3.json
                        (cert3 record i is record i of certB_cert.pkl.gz; checked
                        by the driver through the stored 'src' field).

usage: python3 make_samples.py full_sel_certB.json sel_cert3.json OUTDIR
"""
import collections
import json
import sys


def main():
    full = json.load(open(sys.argv[1]))
    c3 = json.load(open(sys.argv[2]))
    out = sys.argv[3]
    by = collections.defaultdict(list)
    for s in full:
        by[s["group"]].append(s)
    vb = by["path"] + by["near0.05"] + by["leaf0.05"] + by["leaf0.5"] + by["leaf-random-corrected"] \
        + by["near0.5"][:300] + by["rest"][:500]
    json.dump(vb, open(f"{out}/sel_vbb2_certB.json", "w"))
    rb = [dict(rid=s["rid"], group=s["group"]) for s in
          by["path"] + by["near0.05"] + by["near0.5"][:300] + by["rest"][:1000]]
    json.dump(rb, open(f"{out}/sel_rbb_certB.json", "w"))
    json.dump([dict(rid=s["rid"], group="cert3-" + s["group"]) for s in c3], open(f"{out}/sel_rbb_cert3.json", "w"))
    print("vbb2 tasks", collections.Counter(s["group"] for s in vb), len(vb))
    print("rbb certB records", collections.Counter(s["group"] for s in rb), len(rb))
    print("rbb cert3 records", len(c3))


if __name__ == "__main__":
    main()
