"""Summaries of the branching-point study; writes results/summary.md.

    python3 analyze.py

Inputs: selected.txt, candidates.csv (MINLPLib metadata), results/runs.jsonl
(main runs), results/trace.jsonl (diagnostic runs with --trace),
results/features.json.
"""
import csv
import json
import math
import os
import random
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results")
SHIFT_N, SHIFT_T = 10.0, 1.0
THRESH = 1.1
CORE = ["default", "lp", "lp_noclamp", "mix_noclamp", "mid"]
OPTIONAL = ["trig0", "couenne", "lp_c05"]
REF = {}  # comparison baseline if not default
SEEDS = [0, 1, 2]


def load_jsonl(path):
    return [json.loads(ln) for ln in open(path)] if os.path.exists(path) else []


def sgm(vals, shift):
    return math.exp(sum(math.log(v + shift) for v in vals) / len(vals)) - shift


def meta():
    return {r["name"]: r for r in csv.DictReader(open(os.path.join(HERE, "candidates.csv")))}


def solved(r):
    return r["status"] in ("optimal", "gaplimit")


def obj_check(r, m):
    """Relative deviation of SCIP's primal/dual bound from the MINLPLib best known value,
    signed so that positive primal deviation = worse than best known."""
    pb = float(m["primalbound"])
    sgn = 1.0 if m["objsense"] == "min" else -1.0
    sc = max(1.0, abs(pb))
    out = {}
    if r.get("primal") is not None:
        out["dprimal"] = sgn * (r["primal"] - pb) / sc
    if r.get("dual") is not None:
        out["ddual"] = sgn * (r["dual"] - pb) / sc  # > 0 means dual bound cuts off the best known value
    return out


def per_inst(runs, settings, insts):
    """D[inst][setting] = list of runs (seed order)."""
    D = defaultdict(dict)
    for r in runs:
        if r["inst"] in insts and r["setting"] in settings:
            D[r["inst"]].setdefault(r["setting"], {})[r["seed"]] = r
    return D


def inst_value(rs, key, shift, tlim_default):
    vals = []
    for r in rs:
        if key == "time":
            vals.append(r["time"] if solved(r) else r.get("tlim", tlim_default))
        elif "nodes" in r:  # crashed runs have no node count; they count as unsolved for time
            vals.append(r["nodes"])
    return sgm(vals, shift)


def wilcoxon_p(x):
    """Two-sided Wilcoxon signed-rank p-value (normal approximation with tie correction)."""
    x = [v for v in x if abs(v) > 1e-12]
    n = len(x)
    if n < 6:
        return float("nan")
    order = sorted(range(n), key=lambda i: abs(x[i]))
    ranks = [0.0] * n
    i = 0
    ties = 0.0
    while i < n:
        j = i
        while j + 1 < n and abs(abs(x[order[j + 1]]) - abs(x[order[i]])) < 1e-12:
            j += 1
        for k in range(i, j + 1):
            ranks[order[k]] = (i + j) / 2 + 1
        t = j - i + 1
        ties += t ** 3 - t
        i = j + 1
    wplus = sum(rk for rk, v in zip(ranks, x) if v > 0)
    mu = n * (n + 1) / 4
    var = n * (n + 1) * (2 * n + 1) / 24 - ties / 48
    z = (wplus - mu) / math.sqrt(var)
    return math.erfc(abs(z) / math.sqrt(2))


def boot_ci(logs, reps=5000, seed=1):
    rng = random.Random(seed)
    n = len(logs)
    ms = sorted(sum(logs[rng.randrange(n)] for _ in range(n)) / n for _ in range(reps))
    return math.exp(ms[int(0.025 * reps)]), math.exp(ms[int(0.975 * reps)])


def fmt(x, nd=1):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "-"
    if isinstance(x, float):
        return f"{x:.{nd}f}"
    return str(x)


def main():
    M = meta()
    sel = [ln.split()[0] for ln in open(os.path.join(HERE, "selected.txt")) if ln.strip()]
    runs = load_jsonl(os.path.join(RES, "runs.jsonl"))
    feats = json.load(open(os.path.join(RES, "features.json"))) if os.path.exists(os.path.join(RES, "features.json")) else {}
    traces = load_jsonl(os.path.join(RES, "trace.jsonl"))
    settings = [s for s in CORE + OPTIONAL if any(r["setting"] == s for r in runs)]
    D = per_inst(runs, settings, set(sel))
    tlim = max((r["tlim"] for r in runs if r["setting"] in settings), default=0)
    T = {(t["inst"], t["setting"]): t for t in traces if "trace" in t}
    cshare = {}  # share of branchings on continuous variables, default seed-0 trace
    for i in sel:
        t = T.get((i, "default"))
        if t:
            tr = t["trace"]
            c = tr["n"] + tr.get("n_infbound", 0)
            cshare[i] = c / (c + tr["nint"]) if c + tr["nint"] else 0.0
    L = []
    P = L.append

    # ---------------- run inventory and correctness -----------------
    P("# Summary tables (generated by analyze.py)\n")
    P(f"Instances: {len(sel)}. Settings with runs: {', '.join(settings)}. Time limit {tlim:g} s (CPU).\n")
    P("## Run status\n")
    P("| setting | runs | optimal | timelimit | other (status: count) |")
    P("|---|---|---|---|---|")
    for s in settings:
        rs = [D[i][s][k] for i in sel for k in D[i].get(s, {})]
        st = defaultdict(int)
        for r in rs:
            st[r["status"]] += 1
        other = ", ".join(f"{k}: {v}" for k, v in st.items() if k not in ("optimal", "timelimit"))
        P(f"| {s} | {len(rs)} | {st['optimal']} | {st['timelimit']} | {other or '-'} |")
    P("")
    P("## Objective checks against MINLPLib best known values\n")
    P("Relative deviation `d = (value - best known) / max(1, |best known|)`, signed so that d > 0 means "
      "worse than the best known value (for the dual bound: d > 0 means the dual bound excludes the best "
      "known value). Primal deviations are taken over runs with status optimal, dual deviations over all runs "
      "(all settings, seeds and optional runs). Listed: instances with some |d_primal| > 1e-6 or d_dual > 1e-6.\n")
    per = defaultdict(list)
    dual_bad = []
    for i in sel:
        for s in settings:
            for k, r in D[i].get(s, {}).items():
                c = obj_check(r, M[i])
                if solved(r) and "dprimal" in c:
                    per[i].append(c["dprimal"])
                if c.get("ddual", -1) > 1e-6:
                    dual_bad.append((i, s, k, c["ddual"]))
    P("| instance | optimal runs | min d_primal | max d_primal | MINLPLib primal | MINLPLib dual |")
    P("|---|---|---|---|---|---|")
    for i in sel:
        v = per.get(i, [])
        if v and max(abs(x) for x in v) > 1e-6:
            P(f"| {i} | {len(v)} | {min(v):.2e} | {max(v):.2e} | {M[i]['primalbound']} | {M[i]['dualbound']} |")
    allv = [x for v in per.values() for x in v]
    P(f"\nOptimal runs: {len(allv)}. Largest d_primal (worse than best known): {max(allv):.2e}; "
      f"smallest (better than best known): {min(allv):.2e}. Dual bounds excluding the best known value "
      f"by more than 1e-6: {len(dual_bad)}.\n")
    for f in dual_bad:
        P(f"- {f[0]} {f[1]} seed {f[2]}: d_dual = {f[3]:.2e}")
    P("")

    # ---------------- seed variability -----------------
    P("## Seed variability\n")
    P("Per instance and setting: ratio max/min of node counts over the 3 seeds (shifted by 10). "
      "Distribution over instances where all 3 seeds solved.\n")
    P("| setting | instances | median | 75th pct | 90th pct | share with ratio > 1.1 |")
    P("|---|---|---|---|---|---|")
    seedratio = {}
    for s in settings:
        rat = []
        for i in sel:
            rs = D[i].get(s, {})
            if all(k in rs and solved(rs[k]) for k in SEEDS):
                v = [rs[k]["nodes"] + SHIFT_N for k in SEEDS]
                rat.append(max(v) / min(v))
        seedratio[s] = rat
        if rat:
            rat.sort()
            q = lambda p: rat[min(len(rat) - 1, int(p * len(rat)))]
            P(f"| {s} | {len(rat)} | {q(0.5):.2f} | {q(0.75):.2f} | {q(0.9):.2f} | "
              f"{sum(x > THRESH for x in rat) / len(rat):.0%} |")
    P("")
    # null comparison: default seed k vs default seed 0
    P("Null comparison (same setting, different seed): default seed 1 and seed 2 against default "
      "seed 0, per instance, where both solved.\n")
    P("| comparison | instances | wins >10% | losses >10% | ratio of SGM nodes |")
    P("|---|---|---|---|---|")
    for k in (1, 2):
        lr = []
        for i in sel:
            rs = D[i].get("default", {})
            if 0 in rs and k in rs and solved(rs[0]) and solved(rs[k]):
                lr.append(math.log((rs[k]["nodes"] + SHIFT_N) / (rs[0]["nodes"] + SHIFT_N)))
        if lr:
            P(f"| default s{k} vs s0 | {len(lr)} | {sum(x < -math.log(THRESH) for x in lr)} | "
              f"{sum(x > math.log(THRESH) for x in lr)} | {math.exp(sum(lr) / len(lr)):.3f} |")
    P("")

    # ---------------- aggregate comparison -----------------
    def compare(s, base, insts, key, shift):
        """Per instance, both settings are averaged over the seeds run for the setting."""
        a = [inst_value(list(D[i][s].values()), key, shift, tlim) for i in insts]
        b = [inst_value([D[i][base][k] for k in D[i][s] if k in D[i][base]], key, shift, tlim) for i in insts]
        logs = [math.log((x + shift) / (y + shift)) for x, y in zip(a, b)]
        return a, b, logs

    spatial = {i for i in sel if cshare.get(i, 0) >= 0.5}
    for label, need_all, subset in (
            ("all selected instances (unsolved runs: nodes at the limit, time = limit)", False, set(sel)),
            ("instances where every run of every compared setting solved", True, set(sel)),
            (f"the {len(spatial)} instances where at least half of the branchings in the default seed-0 trace "
             "are on continuous variables (unsolved runs at the limit)", False, spatial)):
        P(f"## Aggregate over {label}\n")
        P("Per instance: shifted geometric mean over the seeds run for that setting; then shifted geometric "
          "mean over instances (shift 10 nodes / 1 s); the baseline is averaged over the same seeds as the setting "
          "(seed 0 only for trig0, couenne, lp_c05). Ratio = setting / baseline; 95% CI by bootstrap over "
          "instances; p = two-sided Wilcoxon signed-rank test on per-instance log ratios. Wins/losses: "
          "per-instance ratio beyond 10%. 'Sep.' counts instances where every seed of one setting is beyond "
          "every seed of the baseline by >10% (3 vs 3 seeds; by chance about 10% of instances would separate "
          "in one of the two directions without the 10% margin).\n")
        P("| setting | baseline | seeds | inst | solved runs | SGM nodes | base | ratio | 95% CI | p | wins | losses "
          "| sep. wins | sep. losses | SGM time | base | ratio |")
        P("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for s in settings:
            base = REF.get(s, "default")
            if s == base:
                continue
            insts = [i for i in sel if s in D[i] and base in D[i] and i in subset]
            seeds = sorted({k for i in insts for k in D[i][s]})
            if need_all:
                insts = [i for i in insts if all(solved(r) for r in list(D[i][s].values()) + list(D[i][base].values()))]
            if not insts:
                continue
            a, b, logs = compare(s, base, insts, "nodes", SHIFT_N)
            ta, tb, tlogs = compare(s, base, insts, "time", SHIFT_T)
            nsol = sum(solved(r) for i in insts for r in D[i][s].values())
            nrun = sum(1 for i in insts for r in D[i][s].values())
            lo, hi = boot_ci(logs)
            sepw = sepl = 0
            for i in insts:
                ks = [k for k in D[i][s] if k in D[i][base] and "nodes" in D[i][s][k] and "nodes" in D[i][base][k]]
                if len(ks) >= 2:
                    xs = [D[i][s][k]["nodes"] + SHIFT_N for k in ks]
                    ys = [D[i][base][k]["nodes"] + SHIFT_N for k in ks]
                    if max(xs) * THRESH < min(ys):
                        sepw += 1
                    if min(xs) > THRESH * max(ys):
                        sepl += 1
            P(f"| {s} | {base} | {','.join(map(str, seeds))} | {len(insts)} | {nsol}/{nrun} | {sgm(a, SHIFT_N):.0f} | "
              f"{sgm(b, SHIFT_N):.0f} | {math.exp(sum(logs) / len(logs)):.3f} | {lo:.2f}-{hi:.2f} | "
              f"{wilcoxon_p(logs):.3f} | {sum(x < -math.log(THRESH) for x in logs)} | "
              f"{sum(x > math.log(THRESH) for x in logs)} | {sepw if len(seeds) > 1 else '-'} | "
              f"{sepl if len(seeds) > 1 else '-'} | {sgm(ta, SHIFT_T):.1f} | "
              f"{sgm(tb, SHIFT_T):.1f} | {math.exp(sum(tlogs) / len(tlogs)):.3f} |")
        P("")

    # ---------------- per-instance table -----------------
    P("## Per-instance node counts\n")
    P("Seed-wise node counts `s0/s1/s2`; `*` marks a run that did not finish (limit or failure). "
      "Features: t = MINLPLib problem type; nlc = continuous variables in nonlinear terms "
      "(u = with an infinite bound); bil = bilinear pairs; k = kink operator (abs/min/max); "
      "atb = share of nlc at a bound in the default seed-0 solution; cb = share of branchings on continuous "
      "variables in the default seed-0 trace.\n")
    cols = [s for s in CORE if s in settings]
    P("| instance | t | nlc (u) | bil | k | atb | cb | " + " | ".join(cols) + " |")
    P("|---|---|---|---|---|---|---|" + "---|" * len(cols))
    for i in sel:
        f = feats.get(i, {})
        cells = []
        for s in cols:
            rs = D[i].get(s, {})
            cells.append("/".join((f"{rs[k].get('nodes', rs[k]['status'])}" + ("" if solved(rs[k]) else "*"))
                                  if k in rs else "-" for k in SEEDS))
        P(f"| {i} | {M[i]['probtype']} | {f.get('nl_cont', '-')} ({f.get('nl_cont_unb', '-')}) | "
          f"{f.get('bilin', '-')} | {'y' if f.get('kink') else ''} | {fmt(f.get('at_bound'), 2)} | "
          f"{fmt(cshare.get(i), 2)} | " + " | ".join(cells) + " |")
    P("")

    # ---------------- traces -----------------
    if traces:
        P("## Branching-point traces (seed 0, diagnostic runs)\n")
        P("Continuous spatial branchings recorded at NODEBRANCHED events. n = branchings on bounded "
          "domains; inf = on a domain with an infinite bound; LP@bd = LP value within 1e-6 relative of a "
          "bound; clamp = split at exactly 20% or 80% of the domain; degen = split within 1e-6 of a bound; "
          "w<0.5 = local/global width below 0.5 (midpull scaled down).\n")
        P("| instance | setting | status | nodes | n | inf | int br. | LP@bd | clamp | degen | mid | w<0.5 |")
        P("|---|---|---|---|---|---|---|---|---|---|---|---|")
        agg = defaultdict(lambda: defaultdict(float))
        for i in sel:
            for s in CORE:
                t = T.get((i, s))
                if not t or "trace" not in t:
                    continue
                tr = t["trace"]
                n = tr["n"]
                sh = (lambda x: f"{x / n:.0%}") if n else (lambda x: "-")
                P(f"| {i} | {s} | {t['status']} | {t['nodes']} | {n} | {tr.get('n_infbound', 0)} | {tr['nint']} | "
                  f"{sh(tr['lp_at_bound'])} | {sh(tr['split_at_clamp'])} | {sh(tr['split_degenerate'])} | "
                  f"{sh(tr['split_mid'])} | {sh(tr['relwidth_small'])} |")
                for kk in ("n", "lp_at_bound", "split_at_clamp", "split_degenerate", "relwidth_small"):
                    agg[s][kk] += tr[kk]
                agg[s]["n_infbound"] += tr.get("n_infbound", 0)
                agg[s]["nint"] += tr["nint"]
        P("")
        P("Pooled over instances:\n")
        P("| setting | n | inf | int br. | LP@bd | clamp | degen | w<0.5 |")
        P("|---|---|---|---|---|---|---|---|")
        for s in CORE:
            a = agg.get(s)
            if a and a["n"]:
                n = a["n"]
                P(f"| {s} | {n:.0f} | {a['n_infbound']:.0f} | {a['nint']:.0f} | {a['lp_at_bound'] / n:.0%} | "
                  f"{a['split_at_clamp'] / n:.0%} | {a['split_degenerate'] / n:.0%} | {a['relwidth_small'] / n:.0%} |")
        P("")

    tr2 = load_jsonl(os.path.join(RES, "trace2.jsonl"))
    if tr2:
        P("## Re-trace of the lp_noclamp failures (seed 0, 30 s)\n")
        P("Instances with at least one unsolved lp_noclamp run. degen-wide = split within 1e-6 (relative "
          "position) of a bound on a domain wider than 1e-6 * max(1, |l|, |u|).\n")
        P("| instance | status | nodes | max depth | n | inf | LP@bd | degen | degen-wide |")
        P("|---|---|---|---|---|---|---|---|---|")
        for t in sorted(tr2, key=lambda t: t["inst"]):
            tr = t["trace"]
            n = tr["n"]
            sh = (lambda x: f"{x / n:.0%}") if n else (lambda x: "-")
            P(f"| {t['inst']} | {t['status']} | {t['nodes']} | {t.get('max_depth')} | {n} | {tr['n_infbound']} | "
              f"{sh(tr['lp_at_bound'])} | {sh(tr['split_degenerate'])} | {sh(tr['split_degenerate_wide'])} |")
        P("")

    # ---------------- feature association -----------------
    P("## Per-instance ratios by instance characteristic\n")
    P("Median and SGM of the per-instance node ratio setting/default (seed-averaged, all instances, "
      "unsolved runs at the limit), by group.\n")

    def groups(i):
        f = feats.get(i, {})
        m = M[i]
        g = {}
        g["kink (abs/min/max)"] = bool(f.get("kink"))
        g["nonlinear var with infinite bound"] = f.get("nl_cont_unb", 0) > 0
        g["integer/binary variables"] = int(m["nbinvars"]) + int(m["nintvars"]) > 0
        g["only quadratic nonlinearities"] = bool(f.get("quad_only"))
        if f.get("at_bound") is not None:
            g["at_bound >= 0.5"] = f["at_bound"] >= 0.5
        if i in cshare:
            g["continuous branching share >= 0.5"] = cshare[i] >= 0.5
        t = T.get((i, "lp"))
        if t and t["trace"]["n"] >= 10:
            g["LP value at a bound in >= 10% of bounded continuous branchings (lp trace)"] = \
                t["trace"]["lp_at_bound"] / t["trace"]["n"] >= 0.1
        return g

    comp = [s for s in settings if s in CORE and s != "default"]
    P("| characteristic | value | inst | " + " | ".join(f"{s} median / SGM" for s in comp) + " |")
    P("|---|---|---|" + "---|" * len(comp))
    ratios = {}
    for s in comp:
        for i in sel:
            if s in D[i] and "default" in D[i]:
                a = inst_value(list(D[i][s].values()), "nodes", SHIFT_N, tlim)
                b = inst_value(list(D[i]["default"].values()), "nodes", SHIFT_N, tlim)
                ratios[(i, s)] = (a + SHIFT_N) / (b + SHIFT_N)
    gnames = sorted({k for i in sel for k in groups(i)})
    for gname in gnames:
        for val in (True, False):
            insts = [i for i in sel if groups(i).get(gname) is val]
            if not insts:
                continue
            cells = []
            for s in comp:
                rr = sorted(ratios[(i, s)] for i in insts if (i, s) in ratios)
                if rr:
                    med = rr[len(rr) // 2] if len(rr) % 2 else math.sqrt(rr[len(rr) // 2 - 1] * rr[len(rr) // 2])
                    cells.append(f"{med:.2f} / {math.exp(sum(map(math.log, rr)) / len(rr)):.2f}")
                else:
                    cells.append("-")
            P(f"| {gname} | {'yes' if val else 'no'} | {len(insts)} | " + " | ".join(cells) + " |")
    P("")
    # ---------------- absolute-gap sweep -----------------
    sw = defaultdict(dict)  # sw[inst][(base, delta)] = run
    for r in runs:
        if "@abs" in r["setting"] and r["inst"] in sel:
            base, _, eps = r["setting"].partition("@abs")
            delta = float(eps) / max(1.0, abs(float(M[r["inst"]]["primalbound"])))
            sw[r["inst"]][(base, float(f"{delta:.0e}"))] = r
    if sw:
        swset = ["default", "lp", "lp_noclamp", "mid"]
        deltas = sorted({k[1] for v in sw.values() for k in v}, reverse=True)
        for i in sw:  # the gap-0 point comes from the main seed-0 runs
            for s in swset:
                if 0 in D[i].get(s, {}):
                    sw[i][(s, 0.0)] = D[i][s][0]
        deltas.append(0.0)
        insts = sorted(sw)
        swtl = max(r["tlim"] for v in sw.values() for r in v.values() if "@abs" in r["setting"])
        P("## Absolute-gap sweep (seed 0)\n")
        P(f"{len(insts)} continuous instances with at most 20 variables. `limits/absgap = delta * max(1, |best known|)`; "
          f"delta = 0 is the main run (SCIP default gap limits, time limit {tlim:g} s); the other runs have a "
          f"{swtl:g} s limit. Ratio = SGM nodes of the setting / SGM nodes of default over the instances; "
          "unsolved runs enter with their node count at the limit.\n")
        allsolved = [i for i in insts if all((s, d) in sw[i] and solved(sw[i][(s, d)]) for s in swset for d in deltas)]
        for label, pool in ((f"all {len(insts)} instances", insts),
                            (f"the {len(allsolved)} instances solved by all four settings at every delta", allsolved)):
            P(f"Over {label}:\n")
            P("| delta | " + " | ".join(f"SGM {s}" for s in swset) + " | lp/default | lp_noclamp/default | "
              "mid/default | mid/lp | unsolved (default, lp, lp_noclamp, mid) |")
            P("|---|" + "---|" * (len(swset) + 5))
            for d in deltas:
                ii = [i for i in pool if all((s, d) in sw[i] and "nodes" in sw[i][(s, d)] for s in swset)]
                if not ii:
                    continue
                g = {s: sgm([sw[i][(s, d)]["nodes"] for i in ii], SHIFT_N) for s in swset}
                uns = ", ".join(str(sum(not solved(sw[i][(s, d)]) for i in ii)) for s in swset)
                rat = lambda a, b: (g[a] + SHIFT_N) / (g[b] + SHIFT_N)
                P(f"| {d:g} | " + " | ".join(f"{g[s]:.0f}" for s in swset) +
                  f" | {rat('lp', 'default'):.2f} | {rat('lp_noclamp', 'default'):.2f} | {rat('mid', 'default'):.2f} | "
                  f"{rat('mid', 'lp'):.2f} | {uns} |")
            P("")
        P("Per-instance node counts for delta = 1e-2 / 1e-4 / 1e-6 / 0 (`*` = not solved):\n")
        P("| instance | " + " | ".join(swset) + " |")
        P("|---|" + "---|" * len(swset))
        for i in insts:
            cells = []
            for s in swset:
                cells.append(" / ".join((f"{sw[i][(s, d)].get('nodes', '-')}" + ("" if solved(sw[i][(s, d)]) else "*"))
                                        if (s, d) in sw[i] else "-" for d in deltas))
            P(f"| {i} | " + " | ".join(cells) + " |")
        P("")

    with open(os.path.join(RES, "summary.md"), "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
